version: '3.7'

services:
  docker.postgres:
    image: postgres
    port:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_PASSWORD=12345
    network:
      - ms-net

    docker.redis:
    iamge: redis
    port:
      - "6379:6379"
    restart: always

  ms.site:
    build: /usr/wwwroot/ms/
    restart: always
    depend_on:
      - docker.postgres
    network:
      - ms-net

  docker.ngnix:
    image: ngnix
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    links:
      - ms.site
    network:
      - ms.net

network:
  ms-net:
    driver: bridge
