// <auto-generated />
using System;
using AspNetCore.Entity.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace AspNetCore.Entity.Migrations
{
    [DbContext(typeof(MsContext))]
    [Migration("20190416070626_Migration15")]
    partial class Migration15
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:PostgresExtension:uuid-ossp", ",,")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("AspNetCore.Entity.AdminDivision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AreaNumber");

                    b.Property<int>("CountyNumber");

                    b.Property<int>("GovernmentLevel");

                    b.Property<string>("GovernmentName");

                    b.Property<string>("HighLevelAreaNumber");

                    b.Property<int>("TownNumber");

                    b.Property<int>("VillageGroupNumber");

                    b.Property<int>("VillageNumber");

                    b.HasKey("Id");

                    b.ToTable("AdminDivisions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d83522e6-ca8b-40dc-b033-f1eee0672318"),
                            AreaNumber = "320583000000",
                            CountyNumber = 0,
                            GovernmentLevel = 3,
                            GovernmentName = "昆山市",
                            HighLevelAreaNumber = "",
                            TownNumber = 0,
                            VillageGroupNumber = 2205,
                            VillageNumber = 10
                        },
                        new
                        {
                            Id = new Guid("14df9c40-50b4-46d0-9317-1ea632dc8a78"),
                            AreaNumber = "320583102000",
                            CountyNumber = 0,
                            GovernmentLevel = 4,
                            GovernmentName = "周市镇",
                            HighLevelAreaNumber = "320583000000",
                            TownNumber = 0,
                            VillageGroupNumber = 240,
                            VillageNumber = 29
                        },
                        new
                        {
                            Id = new Guid("22b3da99-ec6e-4660-a814-41585acf1a42"),
                            AreaNumber = "320583400000",
                            CountyNumber = 0,
                            GovernmentLevel = 4,
                            GovernmentName = "开发区",
                            HighLevelAreaNumber = "320583000000",
                            TownNumber = 12,
                            VillageGroupNumber = 312,
                            VillageNumber = 7
                        },
                        new
                        {
                            Id = new Guid("c90b9fa5-b7cc-4036-9679-c6a1e6a725bf"),
                            AreaNumber = "320583104000",
                            CountyNumber = 0,
                            GovernmentLevel = 4,
                            GovernmentName = "花桥镇",
                            HighLevelAreaNumber = "320583000000",
                            TownNumber = 0,
                            VillageGroupNumber = 123,
                            VillageNumber = 13
                        },
                        new
                        {
                            Id = new Guid("9d814319-b024-4985-8cbe-6e5f927dab84"),
                            AreaNumber = "320583106000",
                            CountyNumber = 0,
                            GovernmentLevel = 4,
                            GovernmentName = "张浦镇",
                            HighLevelAreaNumber = "320583000000",
                            TownNumber = 0,
                            VillageGroupNumber = 221,
                            VillageNumber = 12
                        },
                        new
                        {
                            Id = new Guid("25a097e8-56df-4e81-a07b-8d1336582f13"),
                            AreaNumber = "320583103000",
                            CountyNumber = 0,
                            GovernmentLevel = 4,
                            GovernmentName = "陆家镇",
                            HighLevelAreaNumber = "320583000000",
                            TownNumber = 0,
                            VillageGroupNumber = 231,
                            VillageNumber = 13
                        },
                        new
                        {
                            Id = new Guid("43742ef5-7264-4003-a168-d28766fa488b"),
                            AreaNumber = "320583101000",
                            CountyNumber = 0,
                            GovernmentLevel = 4,
                            GovernmentName = "巴城镇",
                            HighLevelAreaNumber = "320583000000",
                            TownNumber = 0,
                            VillageGroupNumber = 216,
                            VillageNumber = 13
                        },
                        new
                        {
                            Id = new Guid("71d2ee88-5855-432f-88f3-4c6ae5080944"),
                            AreaNumber = "320583108000",
                            CountyNumber = 0,
                            GovernmentLevel = 4,
                            GovernmentName = "千灯镇",
                            HighLevelAreaNumber = "320583000000",
                            TownNumber = 0,
                            VillageGroupNumber = 213,
                            VillageNumber = 41
                        },
                        new
                        {
                            Id = new Guid("50d0c700-3eff-4f39-bacc-05fb749c5f4d"),
                            AreaNumber = "320583105000",
                            CountyNumber = 0,
                            GovernmentLevel = 4,
                            GovernmentName = "淀山湖镇",
                            HighLevelAreaNumber = "320583000000",
                            TownNumber = 0,
                            VillageGroupNumber = 173,
                            VillageNumber = 11
                        },
                        new
                        {
                            Id = new Guid("9f35d26e-bcde-4006-9450-53f3f2729402"),
                            AreaNumber = "320583107000",
                            CountyNumber = 0,
                            GovernmentLevel = 4,
                            GovernmentName = "周庄镇",
                            HighLevelAreaNumber = "320583000000",
                            TownNumber = 0,
                            VillageGroupNumber = 123,
                            VillageNumber = 31
                        },
                        new
                        {
                            Id = new Guid("0ef3a9bb-958a-42ee-a10b-a45034e7ffdc"),
                            AreaNumber = "320583109000",
                            CountyNumber = 0,
                            GovernmentLevel = 4,
                            GovernmentName = "锦溪镇",
                            HighLevelAreaNumber = "320583000000",
                            TownNumber = 0,
                            VillageGroupNumber = 256,
                            VillageNumber = 22
                        },
                        new
                        {
                            Id = new Guid("2c566e52-6a3a-4556-8004-bc124097617f"),
                            AreaNumber = "320583106001",
                            CountyNumber = 0,
                            GovernmentLevel = 5,
                            GovernmentName = "张浦社区",
                            HighLevelAreaNumber = "320583106000",
                            TownNumber = 0,
                            VillageGroupNumber = 12,
                            VillageNumber = 0
                        },
                        new
                        {
                            Id = new Guid("b051bcf6-a842-4d34-8ea1-443be60fd9f5"),
                            AreaNumber = "320583106002",
                            CountyNumber = 0,
                            GovernmentLevel = 5,
                            GovernmentName = "花园社区",
                            HighLevelAreaNumber = "320583106000",
                            TownNumber = 0,
                            VillageGroupNumber = 12,
                            VillageNumber = 0
                        },
                        new
                        {
                            Id = new Guid("fd5f0f96-9b99-42af-b28a-ba85d1dc2294"),
                            AreaNumber = "320583106003",
                            CountyNumber = 0,
                            GovernmentLevel = 5,
                            GovernmentName = "振苏社区",
                            HighLevelAreaNumber = "320583106000",
                            TownNumber = 0,
                            VillageGroupNumber = 12,
                            VillageNumber = 0
                        },
                        new
                        {
                            Id = new Guid("d820683d-16a7-4bf4-9ddc-796b26a4ac87"),
                            AreaNumber = "320583106004",
                            CountyNumber = 0,
                            GovernmentLevel = 5,
                            GovernmentName = "南港社区",
                            HighLevelAreaNumber = "320583106000",
                            TownNumber = 0,
                            VillageGroupNumber = 12,
                            VillageNumber = 0
                        });
                });

            modelBuilder.Entity("AspNetCore.Entity.Core.Villager", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AnnualIncome");

                    b.Property<DateTime>("Birthday");

                    b.Property<string>("Education")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(3);

                    b.Property<bool>("HavingCriminalRecord");

                    b.Property<bool>("HavingIllegalRecord");

                    b.Property<string>("HomeAddress")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("MaritalStatus")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Villagers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5fd68ac1-0e2f-4c33-b5dc-59514c4a9f7c"),
                            AnnualIncome = 20000,
                            Birthday = new DateTime(1984, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Education = "高中",
                            Gender = "男",
                            HavingCriminalRecord = false,
                            HavingIllegalRecord = false,
                            HomeAddress = "向阳村3组14号",
                            MaritalStatus = "已婚",
                            Name = "张东"
                        },
                        new
                        {
                            Id = new Guid("0e046201-f17d-40ed-822c-f53ffe8193d2"),
                            AnnualIncome = 17000,
                            Birthday = new DateTime(1972, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Education = "初中",
                            Gender = "男",
                            HavingCriminalRecord = false,
                            HavingIllegalRecord = false,
                            HomeAddress = "向阳村5组17号",
                            MaritalStatus = "已婚",
                            Name = "刘项"
                        },
                        new
                        {
                            Id = new Guid("a1b4a387-47a9-45ef-826f-3676a72d86dc"),
                            AnnualIncome = 50000,
                            Birthday = new DateTime(1990, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Education = "本科",
                            Gender = "男",
                            HavingCriminalRecord = false,
                            HavingIllegalRecord = false,
                            HomeAddress = "向阳村1组2号",
                            MaritalStatus = "未婚",
                            Name = "马伦"
                        });
                });

            modelBuilder.Entity("AspNetCore.Entity.DataCategroy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CategroyCode");

                    b.Property<string>("CategroyName");

                    b.HasKey("Id");

                    b.ToTable("DataCategroys");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6416b4f7-e24d-46f4-9c26-1f5e0bdd64c6"),
                            CategroyCode = "001",
                            CategroyName = "城乡分类"
                        },
                        new
                        {
                            Id = new Guid("f92032ad-1f02-41ab-a08f-419aea2d630d"),
                            CategroyCode = "002",
                            CategroyName = "行政级别"
                        },
                        new
                        {
                            Id = new Guid("64a5ff46-15ea-437d-bfeb-e144ae783c92"),
                            CategroyCode = "003",
                            CategroyName = "政治面貌"
                        });
                });

            modelBuilder.Entity("AspNetCore.Entity.DataItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CategroyCode");

                    b.Property<string>("Content");

                    b.Property<string>("ItemCode");

                    b.HasKey("Id");

                    b.ToTable("DataItems");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c67b6544-f466-49c6-8902-b0dd7e0b3569"),
                            CategroyCode = "001",
                            Content = "主城区",
                            ItemCode = "001"
                        },
                        new
                        {
                            Id = new Guid("5ea96ad3-cf9c-4578-96ad-7b525e18d9e9"),
                            CategroyCode = "001",
                            Content = "城乡结合区",
                            ItemCode = "002"
                        },
                        new
                        {
                            Id = new Guid("16e0ff5f-f906-4dde-94fe-f101e47c3fd1"),
                            CategroyCode = "001",
                            Content = "镇中心区",
                            ItemCode = "003"
                        },
                        new
                        {
                            Id = new Guid("b8b104ed-63f0-4e61-8cd1-1396c40852a9"),
                            CategroyCode = "001",
                            Content = "特殊区域",
                            ItemCode = "004"
                        },
                        new
                        {
                            Id = new Guid("d2c8e9ca-29da-4263-b051-b9913b509101"),
                            CategroyCode = "001",
                            Content = "乡中心区",
                            ItemCode = "005"
                        },
                        new
                        {
                            Id = new Guid("1fb5b48e-f8d0-46c7-ba0d-667fac29d96c"),
                            CategroyCode = "001",
                            Content = "村庄",
                            ItemCode = "006"
                        },
                        new
                        {
                            Id = new Guid("cf108d71-3308-42f9-ae2c-e7e40857aaa0"),
                            CategroyCode = "002",
                            Content = "省级行政区",
                            ItemCode = "001"
                        },
                        new
                        {
                            Id = new Guid("8a1adc3f-cb98-4004-a5e6-0235c0997b57"),
                            CategroyCode = "002",
                            Content = "地级行政区",
                            ItemCode = "001"
                        },
                        new
                        {
                            Id = new Guid("10944ce6-78fe-43d1-bb06-8f486c799481"),
                            CategroyCode = "002",
                            Content = "县级行政区",
                            ItemCode = "003"
                        },
                        new
                        {
                            Id = new Guid("a45334e9-54b3-4a89-b588-20952c35c7c1"),
                            CategroyCode = "002",
                            Content = "乡级行政区",
                            ItemCode = "004"
                        },
                        new
                        {
                            Id = new Guid("74e224eb-fad6-406e-a2c9-52ade906da0b"),
                            CategroyCode = "002",
                            Content = "村级行政区",
                            ItemCode = "005"
                        },
                        new
                        {
                            Id = new Guid("f3e79a0f-233c-4d98-9fdb-c8e3a48fe044"),
                            CategroyCode = "003",
                            Content = "中共党员",
                            ItemCode = "001"
                        },
                        new
                        {
                            Id = new Guid("d29d4717-cb48-4342-93fb-bedc31617eec"),
                            CategroyCode = "003",
                            Content = "中共预备党员",
                            ItemCode = "002"
                        },
                        new
                        {
                            Id = new Guid("d63c9ac9-6b83-4d15-9413-6f74a239cf26"),
                            CategroyCode = "003",
                            Content = "共青团员",
                            ItemCode = "003"
                        },
                        new
                        {
                            Id = new Guid("fea2f27e-87fb-49d4-a5f7-3d9c92aa8a62"),
                            CategroyCode = "003",
                            Content = "民革党员",
                            ItemCode = "004"
                        },
                        new
                        {
                            Id = new Guid("dd997a7a-d80c-45b3-a899-dce898254fe2"),
                            CategroyCode = "003",
                            Content = "民盟盟员",
                            ItemCode = "005"
                        },
                        new
                        {
                            Id = new Guid("a2bec436-c64a-4b37-8ec6-21ab71be5174"),
                            CategroyCode = "003",
                            Content = "民建会员",
                            ItemCode = "006"
                        },
                        new
                        {
                            Id = new Guid("4d79a216-506f-4af7-8890-db90d7d1c1f2"),
                            CategroyCode = "003",
                            Content = "民进会员",
                            ItemCode = "007"
                        },
                        new
                        {
                            Id = new Guid("ab163f1c-9130-4ba4-9279-1bf3194fc4b7"),
                            CategroyCode = "003",
                            Content = "农工党党员",
                            ItemCode = "008"
                        },
                        new
                        {
                            Id = new Guid("43ee3d07-e3d0-4339-8b84-8ea579517379"),
                            CategroyCode = "003",
                            Content = "致公党党员",
                            ItemCode = "009"
                        },
                        new
                        {
                            Id = new Guid("353fd378-fe51-4814-b4b0-83ef11cd79e0"),
                            CategroyCode = "003",
                            Content = "九三学社社员",
                            ItemCode = "010"
                        },
                        new
                        {
                            Id = new Guid("af5737ad-6317-458e-921a-227566d2649a"),
                            CategroyCode = "003",
                            Content = "台盟盟员",
                            ItemCode = "011"
                        },
                        new
                        {
                            Id = new Guid("b3f71409-b93c-4047-adf8-395cdee26b61"),
                            CategroyCode = "003",
                            Content = "无党派人士",
                            ItemCode = "012"
                        },
                        new
                        {
                            Id = new Guid("b38a78e6-7163-43a7-bf4e-56835d3dd61e"),
                            CategroyCode = "003",
                            Content = "群众",
                            ItemCode = "013"
                        });
                });

            modelBuilder.Entity("AspNetCore.Entity.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<string>("ContactPhone");

                    b.Property<string>("DepartmentCode");

                    b.Property<string>("DepartmentName");

                    b.Property<string>("Email");

                    b.Property<string>("Fax");

                    b.Property<string>("Notes");

                    b.Property<string>("PrincipalName");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("49babda7-9b5f-4f68-a448-0204d7f2f7d8"),
                            Address = "京东路469号",
                            ContactPhone = "0512-57623451",
                            DepartmentCode = "001",
                            DepartmentName = "张浦社区党支部委员会",
                            Email = "zhenxinguo@kszpzp.gov.cn",
                            Fax = "0512-54123412",
                            Notes = "",
                            PrincipalName = "郑兴国"
                        },
                        new
                        {
                            Id = new Guid("aad55b7e-afda-437e-89e8-4dd775275b8f"),
                            Address = "京东路469号",
                            ContactPhone = "0512-58289432",
                            DepartmentCode = "002",
                            DepartmentName = "张浦社区居民委员会",
                            Email = "chenlecheng@kszpzp.gov.cn",
                            Fax = "0512-59283414",
                            Notes = "临时兼任",
                            PrincipalName = "陈乐成"
                        },
                        new
                        {
                            Id = new Guid("50adc1bd-097a-43a9-bbcd-cc2b2925fbe1"),
                            Address = "花苑路与京东路交叉口西侧",
                            ContactPhone = "0512-54128123",
                            DepartmentCode = "003",
                            DepartmentName = "花园社区党支部委员会",
                            Email = "xugaoyi@kszpzp.gov.cn",
                            Fax = "0512-564178314",
                            PrincipalName = "许高义"
                        });
                });

            modelBuilder.Entity("AspNetCore.Entity.Family", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AccountCharacter");

                    b.Property<int>("AverageAnnualIncome");

                    b.Property<float>("AverageHousingArea");

                    b.Property<string>("FamilyCode");

                    b.Property<string>("Householder");

                    b.Property<float>("HousingArea");

                    b.Property<bool>("IsLowIncome");

                    b.Property<bool>("IsPoor");

                    b.Property<int>("PeopleNumber");

                    b.Property<string>("VillageGroupCode");

                    b.Property<string>("VillageName");

                    b.HasKey("Id");

                    b.ToTable("Families");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3d545eae-6ba8-428b-859d-8ce9e8fc776e"),
                            AccountCharacter = "非农业",
                            AverageAnnualIncome = 5000,
                            AverageHousingArea = 20.84f,
                            FamilyCode = "001000",
                            Householder = "秦博厚",
                            HousingArea = 104.2f,
                            IsLowIncome = false,
                            IsPoor = false,
                            PeopleNumber = 5,
                            VillageGroupCode = "001"
                        });
                });

            modelBuilder.Entity("AspNetCore.Entity.Member", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Birthday");

                    b.Property<string>("DepartmentCode");

                    b.Property<string>("Education");

                    b.Property<DateTime>("EntryTime");

                    b.Property<string>("Gender");

                    b.Property<string>("HomeAddress");

                    b.Property<string>("IdCardNumber");

                    b.Property<DateTime>("LeaveTime");

                    b.Property<string>("LengthOfService");

                    b.Property<string>("MaritalStatus");

                    b.Property<string>("MemberCode");

                    b.Property<string>("MemberName");

                    b.Property<string>("Nationality");

                    b.Property<string>("PersonnelNature");

                    b.Property<string>("PoliticalStatus");

                    b.Property<string>("Position");

                    b.Property<string>("Status");

                    b.HasKey("Id");

                    b.ToTable("Members");

                    b.HasData(
                        new
                        {
                            Id = new Guid("eeafdeb0-bede-4ad6-8bb0-a8d1622bf6e0"),
                            Birthday = new DateTime(1974, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentCode = "002",
                            Education = "本科",
                            EntryTime = new DateTime(2007, 2, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = "男",
                            HomeAddress = "张浦镇江北新村14号",
                            IdCardNumber = "320583197407056857",
                            LeaveTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LengthOfService = "12年",
                            MaritalStatus = "已婚",
                            MemberCode = "002000",
                            MemberName = "陈乐成",
                            Nationality = "汉族",
                            PoliticalStatus = "中共党员",
                            Position = "主任",
                            Status = "在职"
                        },
                        new
                        {
                            Id = new Guid("84e3a12a-922d-4b24-8268-ed7ed5c157ca"),
                            Birthday = new DateTime(1977, 7, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentCode = "002",
                            Education = "本科",
                            EntryTime = new DateTime(2002, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = "男",
                            HomeAddress = "张浦镇浦江北新村112号",
                            IdCardNumber = "320583197707087692",
                            LeaveTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LengthOfService = "17年",
                            MaritalStatus = "已婚",
                            MemberCode = "002001",
                            MemberName = "姜兴安",
                            Nationality = "汉族",
                            PoliticalStatus = "中共党员",
                            Position = "副主任",
                            Status = "在职"
                        },
                        new
                        {
                            Id = new Guid("9f8f3d28-1ffc-40e9-9271-e20bd0d92def"),
                            Birthday = new DateTime(1985, 4, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentCode = "002",
                            Education = "高中",
                            EntryTime = new DateTime(2010, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = "男",
                            HomeAddress = "张浦镇江北新村56号",
                            IdCardNumber = "320583198504178937",
                            LeaveTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LengthOfService = "9年",
                            MaritalStatus = "丧偶",
                            MemberCode = "002002",
                            MemberName = "于君昊",
                            Nationality = "汉族",
                            PoliticalStatus = "中共党员",
                            Position = "治调委员",
                            Status = "在职"
                        },
                        new
                        {
                            Id = new Guid("f5e780ff-5194-4f49-8090-8b1b91d4a7a7"),
                            Birthday = new DateTime(1979, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentCode = "002",
                            Education = "硕士研究生",
                            EntryTime = new DateTime(2005, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = "男",
                            HomeAddress = "张浦镇江北新村12号",
                            IdCardNumber = "320583197910154878",
                            LeaveTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LengthOfService = "14年",
                            MaritalStatus = "离异",
                            MemberCode = "002003",
                            MemberName = "康志国",
                            Nationality = "汉族",
                            PoliticalStatus = "群众",
                            Position = "财经委员",
                            Status = "在职"
                        },
                        new
                        {
                            Id = new Guid("d91e0f65-8a82-442d-afc7-979830a3afd3"),
                            Birthday = new DateTime(1987, 4, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentCode = "002",
                            Education = "本科",
                            EntryTime = new DateTime(2007, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = "女",
                            HomeAddress = "张浦镇江北新村17号",
                            IdCardNumber = "320583198704187965",
                            LeaveTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LengthOfService = "12年",
                            MaritalStatus = "已婚",
                            MemberCode = "002004",
                            MemberName = "赵陈红",
                            Nationality = "汉族",
                            PoliticalStatus = "群众",
                            Position = "妇女计生委员",
                            Status = "在职"
                        });
                });

            modelBuilder.Entity("AspNetCore.Entity.NonOperatingAssets", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("LibaryCollectionsNumber");

                    b.Property<int>("LibraryNumber");

                    b.Property<float>("OfficeBuildingArea");

                    b.Property<int>("OfficeBuildingNumber");

                    b.Property<float>("SeniorCitizenCenterArea");

                    b.Property<int>("SeniorCitizenCenterNumber");

                    b.Property<int>("ServiceStationNumber");

                    b.Property<float>("SportActivityRoomArea");

                    b.Property<int>("SportsActivityRoomNumber");

                    b.Property<float>("StaffQuarterArea");

                    b.Property<int>("StaffQuartersNumber");

                    b.Property<string>("VillageName");

                    b.HasKey("Id");

                    b.ToTable("NonOperatingAssets");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3006cfce-b528-424b-9147-462df565e01a"),
                            LibaryCollectionsNumber = 3000,
                            LibraryNumber = 1,
                            OfficeBuildingArea = 105f,
                            OfficeBuildingNumber = 1,
                            SeniorCitizenCenterArea = 450f,
                            SeniorCitizenCenterNumber = 1,
                            ServiceStationNumber = 4,
                            SportActivityRoomArea = 1000f,
                            SportsActivityRoomNumber = 2,
                            StaffQuarterArea = 1000f,
                            StaffQuartersNumber = 1,
                            VillageName = "张浦社区"
                        },
                        new
                        {
                            Id = new Guid("3faa9bfe-5d69-482f-af35-7ce311de1ee3"),
                            LibaryCollectionsNumber = 2500,
                            LibraryNumber = 1,
                            OfficeBuildingArea = 172f,
                            OfficeBuildingNumber = 1,
                            SeniorCitizenCenterArea = 380f,
                            SeniorCitizenCenterNumber = 1,
                            ServiceStationNumber = 2,
                            SportActivityRoomArea = 800f,
                            SportsActivityRoomNumber = 1,
                            StaffQuarterArea = 1200f,
                            StaffQuartersNumber = 1,
                            VillageName = "花园社区"
                        },
                        new
                        {
                            Id = new Guid("b377efb2-425d-4a16-b529-93631ad92cb2"),
                            LibaryCollectionsNumber = 5000,
                            LibraryNumber = 1,
                            OfficeBuildingArea = 250f,
                            OfficeBuildingNumber = 2,
                            SeniorCitizenCenterArea = 700f,
                            SeniorCitizenCenterNumber = 2,
                            ServiceStationNumber = 1,
                            SportActivityRoomArea = 1500f,
                            SportsActivityRoomNumber = 3,
                            StaffQuarterArea = 2000f,
                            StaffQuartersNumber = 2,
                            VillageName = "振苏社区"
                        });
                });

            modelBuilder.Entity("AspNetCore.Entity.PartyMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Birthday");

                    b.Property<string>("ContactPhone");

                    b.Property<string>("DepartmentCode");

                    b.Property<string>("Education");

                    b.Property<string>("Gender");

                    b.Property<bool?>("IsFullMember");

                    b.Property<string>("MemberCode");

                    b.Property<string>("Nationality");

                    b.Property<string>("PartyMemberName");

                    b.Property<string>("PartyOrganizationName");

                    b.Property<string>("PartyPosition");

                    b.Property<string>("VillageName");

                    b.HasKey("Id");

                    b.ToTable("PartyMembers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ca574965-c413-4955-a04a-c262404af7dd"),
                            Birthday = new DateTime(1974, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ContactPhone = "13057134712",
                            DepartmentCode = "001",
                            Education = "本科",
                            Gender = "男",
                            IsFullMember = true,
                            MemberCode = "001000",
                            Nationality = "汉族",
                            PartyMemberName = "陈乐成",
                            PartyOrganizationName = "张浦社区党支部委员会",
                            PartyPosition = "无",
                            VillageName = "张浦社区"
                        });
                });

            modelBuilder.Entity("AspNetCore.Entity.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("RoleName")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("63f7381a-4bf4-4b66-a6c4-b8d04aec011d"),
                            RoleName = "Admin"
                        },
                        new
                        {
                            Id = new Guid("c317d1b2-b25d-4f9f-87ba-4aad0c467457"),
                            RoleName = "Client"
                        },
                        new
                        {
                            Id = new Guid("f356ef37-d955-4c51-b00a-a0891e269090"),
                            RoleName = "System"
                        });
                });

            modelBuilder.Entity("AspNetCore.Entity.Town", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<string>("AreaNumber");

                    b.Property<string>("ChairmanName");

                    b.Property<string>("ContactPhone");

                    b.Property<int>("GovernmentLevel");

                    b.Property<string>("MayorName");

                    b.Property<string>("SecretaryName");

                    b.Property<string>("TownName");

                    b.HasKey("Id");

                    b.ToTable("Towns");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8f1d7e1f-e9ca-4ce1-9a33-c603a116605a"),
                            Address = "前进西路168号",
                            AreaNumber = "320583102000",
                            ChairmanName = "祖冲之",
                            ContactPhone = "0512-57621053",
                            GovernmentLevel = 4,
                            MayorName = "陆机",
                            SecretaryName = "陆云",
                            TownName = "周市镇"
                        },
                        new
                        {
                            Id = new Guid("5a0bfb88-2a4e-4a2a-8ee6-27367087d7e0"),
                            Address = "前进东路",
                            AreaNumber = "320583400000",
                            ChairmanName = "邢栋祥",
                            ContactPhone = "0512-57329416",
                            GovernmentLevel = 4,
                            MayorName = "逢建德",
                            SecretaryName = "匡俊智",
                            TownName = "开发区"
                        },
                        new
                        {
                            Id = new Guid("b9d5d3bb-9990-4c63-bd94-f1017df51914"),
                            Address = "花溪路358号",
                            AreaNumber = "320583104000",
                            ChairmanName = "武财章",
                            ContactPhone = "0512-57698733",
                            GovernmentLevel = 4,
                            MayorName = "王班",
                            SecretaryName = "吴启河",
                            TownName = "花桥镇"
                        },
                        new
                        {
                            Id = new Guid("96089568-74fb-4a4d-81f7-5f29d3167fc9"),
                            Address = "华杨路188号",
                            AreaNumber = "320583106000",
                            ChairmanName = "成梦昆",
                            ContactPhone = "0512-57452503",
                            GovernmentLevel = 4,
                            MayorName = "刘赫伯",
                            SecretaryName = "蒋信迟",
                            TownName = "张浦镇"
                        },
                        new
                        {
                            Id = new Guid("2e40cafc-80ef-483e-b3d5-dd0e20ba9af5"),
                            Address = "菉溪路22号",
                            AreaNumber = "	320583103000",
                            ChairmanName = "李迪尉",
                            ContactPhone = "0512-57671003",
                            GovernmentLevel = 4,
                            MayorName = "梁灶慈",
                            SecretaryName = "刘群胜",
                            TownName = "陆家镇"
                        },
                        new
                        {
                            Id = new Guid("8b66fb80-379e-4f06-91a1-44dcc4825d1a"),
                            Address = "新澄路918号",
                            AreaNumber = "320583101000",
                            ChairmanName = "周伟",
                            ContactPhone = "0521-57656330",
                            GovernmentLevel = 4,
                            MayorName = "李迪尉",
                            SecretaryName = "钟开桦",
                            TownName = "巴城镇"
                        },
                        new
                        {
                            Id = new Guid("a629cb4f-bac7-44b2-a756-f8b31e4e882d"),
                            Address = "炎东路",
                            AreaNumber = "320583108000",
                            ChairmanName = "林修胜",
                            ContactPhone = "0512-36620396",
                            GovernmentLevel = 4,
                            MayorName = "张弥成",
                            SecretaryName = "时可北",
                            TownName = "千灯镇"
                        },
                        new
                        {
                            Id = new Guid("019300df-f788-46f3-9c22-b7f363a95c12"),
                            Address = "府前路78号",
                            AreaNumber = "320583105000",
                            ChairmanName = "常般业",
                            ContactPhone = "0512-57488358",
                            GovernmentLevel = 4,
                            MayorName = "冯便磊",
                            SecretaryName = "颜尚冲",
                            TownName = "淀山湖镇"
                        },
                        new
                        {
                            Id = new Guid("5e17e133-b526-4892-b0ca-a8d00dd529d4"),
                            Address = "淀南路100号",
                            AreaNumber = "320583107000",
                            ChairmanName = "陆先",
                            ContactPhone = "0521-57211236",
                            GovernmentLevel = 4,
                            MayorName = "王翱桦",
                            SecretaryName = "江衷力",
                            TownName = "周庄镇"
                        },
                        new
                        {
                            Id = new Guid("6055bbfd-46d2-4bf6-89e5-5f245ee5a68f"),
                            Address = "普庆路1号",
                            AreaNumber = "320583109000",
                            ChairmanName = "邹鉴夕",
                            ContactPhone = "0521-57231290",
                            GovernmentLevel = 4,
                            MayorName = "倪御奋",
                            SecretaryName = "姬道生",
                            TownName = "锦溪镇"
                        });
                });

            modelBuilder.Entity("AspNetCore.Entity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(150);

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("41637668-eecd-4f83-b90d-c5aa3a34bb01"),
                            Password = "fu1Enyt+Hrdo9BNpDnSy5qb0tM7noN4WtRZwYUtkfpc=",
                            UserName = "admin"
                        },
                        new
                        {
                            Id = new Guid("6cf92601-97e9-4a8e-b759-ba52a597b8bb"),
                            Password = "/uQH4FsnsFGBmvRluYOYHKDjUWimJiwnOV9WCRuEHQE=",
                            UserName = "user1"
                        },
                        new
                        {
                            Id = new Guid("67ff3583-b9ba-4533-a72c-c6ba06e82846"),
                            Password = "vuQZWjwJouGCACBNyNwxQoSZc+8sK51nsCv34XSgelE=",
                            UserName = "user2"
                        },
                        new
                        {
                            Id = new Guid("500c7ed5-e589-42ab-9f81-f714f83d0e93"),
                            Password = "h3fPS6qc1oAs9EImA3iGSZ9fH6Zl1yZJtFa6T3tiQko=",
                            UserName = "user3"
                        });
                });

            modelBuilder.Entity("AspNetCore.Entity.UserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("RoleId");

                    b.Property<Guid>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("95d9b284-3f38-4e06-be73-3945485e6911"),
                            RoleId = new Guid("63f7381a-4bf4-4b66-a6c4-b8d04aec011d"),
                            UserId = new Guid("41637668-eecd-4f83-b90d-c5aa3a34bb01")
                        },
                        new
                        {
                            Id = new Guid("eef50480-c4cd-4bb4-ad3f-9a7632a670e6"),
                            RoleId = new Guid("c317d1b2-b25d-4f9f-87ba-4aad0c467457"),
                            UserId = new Guid("6cf92601-97e9-4a8e-b759-ba52a597b8bb")
                        },
                        new
                        {
                            Id = new Guid("980a2b96-5c37-4b37-a370-a250eafdb1dc"),
                            RoleId = new Guid("c317d1b2-b25d-4f9f-87ba-4aad0c467457"),
                            UserId = new Guid("67ff3583-b9ba-4533-a72c-c6ba06e82846")
                        },
                        new
                        {
                            Id = new Guid("344df75c-1879-44b3-95bb-04063949187c"),
                            RoleId = new Guid("63f7381a-4bf4-4b66-a6c4-b8d04aec011d"),
                            UserId = new Guid("500c7ed5-e589-42ab-9f81-f714f83d0e93")
                        },
                        new
                        {
                            Id = new Guid("64f3d7d4-a2a7-455e-a53a-19b3e46a6b13"),
                            RoleId = new Guid("f356ef37-d955-4c51-b00a-a0891e269090"),
                            UserId = new Guid("41637668-eecd-4f83-b90d-c5aa3a34bb01")
                        });
                });

            modelBuilder.Entity("AspNetCore.Entity.Village", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("AreaNumber")
                        .IsRequired()
                        .HasMaxLength(12);

                    b.Property<string>("ContactPhone")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("GovernmentLevel");

                    b.Property<int?>("GroupCount");

                    b.Property<string>("HighLevelAreaNumber")
                        .IsRequired()
                        .HasMaxLength(12);

                    b.Property<string>("SecretaryName")
                        .IsRequired();

                    b.Property<int>("UrbanRuralClassification");

                    b.Property<string>("VillageHeadName")
                        .IsRequired();

                    b.Property<string>("VillageName")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Villages");

                    b.HasData(
                        new
                        {
                            Id = new Guid("72b5ddd6-1817-4e06-af53-fc5a4b0427dc"),
                            Address = "京东路469号",
                            AreaNumber = "320583106001",
                            ContactPhone = "0512-57441175",
                            GovernmentLevel = 5,
                            GroupCount = 12,
                            HighLevelAreaNumber = "320583106000",
                            SecretaryName = "尹乐和",
                            UrbanRuralClassification = 111,
                            VillageHeadName = "赵乐欣",
                            VillageName = "张浦社区"
                        },
                        new
                        {
                            Id = new Guid("7bddc87f-fa2e-4ad6-826c-7722d6ddadd3"),
                            Address = "花苑路与京东路交叉口西侧",
                            AreaNumber = "320583106002",
                            ContactPhone = "0512-36863123",
                            GovernmentLevel = 5,
                            GroupCount = 26,
                            HighLevelAreaNumber = "320583106000",
                            SecretaryName = "汤振海",
                            UrbanRuralClassification = 111,
                            VillageHeadName = "杜向阳",
                            VillageName = "花园社区"
                        },
                        new
                        {
                            Id = new Guid("1a2d4dfb-53b4-44dd-9a5a-36bf58066172"),
                            Address = "振苏六村",
                            AreaNumber = "320583106003",
                            ContactPhone = "0512-55270465",
                            GovernmentLevel = 5,
                            HighLevelAreaNumber = "320583106000",
                            SecretaryName = "廖景天",
                            UrbanRuralClassification = 111,
                            VillageHeadName = "崔泰宁",
                            VillageName = "振苏社区"
                        },
                        new
                        {
                            Id = new Guid("11306d33-7b5d-4dd5-a0ba-851e66a8bd16"),
                            Address = "震阳路126号",
                            AreaNumber = "320583106004",
                            ContactPhone = "0512-57428835",
                            GovernmentLevel = 5,
                            HighLevelAreaNumber = "320583106000",
                            SecretaryName = "阎乐池",
                            UrbanRuralClassification = 121,
                            VillageHeadName = "尹和蔼",
                            VillageName = "南港社区"
                        },
                        new
                        {
                            Id = new Guid("8258ef09-9140-40a6-8b30-70f6e60dd45b"),
                            Address = "淞沪西路36号",
                            AreaNumber = "320583106005",
                            ContactPhone = "0512-57256550",
                            GovernmentLevel = 5,
                            HighLevelAreaNumber = "320583106000",
                            SecretaryName = "许宏畅",
                            UrbanRuralClassification = 220,
                            VillageHeadName = "薛兴为",
                            VillageName = "大市社区"
                        },
                        new
                        {
                            Id = new Guid("715e4955-da65-4e7a-bc11-3702465a8d28"),
                            Address = "俱巷路894号",
                            AreaNumber = "320583106006",
                            ContactPhone = "0512-36691258",
                            GovernmentLevel = 5,
                            HighLevelAreaNumber = "320583106000",
                            SecretaryName = "孔浩思",
                            UrbanRuralClassification = 111,
                            VillageHeadName = "王康胜",
                            VillageName = "新巷社区"
                        },
                        new
                        {
                            Id = new Guid("e7bad1f0-2a19-4375-9abc-a05b3234727d"),
                            Address = "商秧路178号",
                            AreaNumber = "320583106007",
                            ContactPhone = "0512-55272500",
                            GovernmentLevel = 5,
                            GroupCount = 26,
                            HighLevelAreaNumber = "320583106000",
                            SecretaryName = "吴俊晤",
                            UrbanRuralClassification = 111,
                            VillageHeadName = "石欣德",
                            VillageName = "新吴社区"
                        },
                        new
                        {
                            Id = new Guid("25e77b28-4dfd-4a68-85a7-989582082aa4"),
                            Address = "大直路504号",
                            AreaNumber = "320583106008",
                            ContactPhone = "0512-55272500",
                            GovernmentLevel = 5,
                            GroupCount = 23,
                            HighLevelAreaNumber = "320583106000",
                            SecretaryName = "梁奇希",
                            UrbanRuralClassification = 112,
                            VillageHeadName = "吕勇男",
                            VillageName = "大直社区"
                        },
                        new
                        {
                            Id = new Guid("12046932-b923-4c1b-9311-a61376c734ce"),
                            Address = "周巷路",
                            AreaNumber = "320583106009",
                            ContactPhone = "0512-57294577",
                            GovernmentLevel = 5,
                            GroupCount = 40,
                            HighLevelAreaNumber = "320583106000",
                            SecretaryName = "姜永昌",
                            UrbanRuralClassification = 111,
                            VillageHeadName = "吴凯凯",
                            VillageName = "周巷社区"
                        },
                        new
                        {
                            Id = new Guid("757635ce-8670-4e65-832e-40bd6949963c"),
                            Address = "京东路588号",
                            AreaNumber = "320583106012",
                            ContactPhone = "0512-57883298",
                            GovernmentLevel = 5,
                            HighLevelAreaNumber = "320583106000",
                            SecretaryName = "龙澔",
                            UrbanRuralClassification = 111,
                            VillageHeadName = "汤烨磊",
                            VillageName = "亲和社区"
                        },
                        new
                        {
                            Id = new Guid("32a70622-8276-4552-816c-e00eee2d8929"),
                            Address = "京东路731号",
                            AreaNumber = "320583106013",
                            ContactPhone = "0512-57278938",
                            GovernmentLevel = 5,
                            HighLevelAreaNumber = "320583106000",
                            SecretaryName = "李段",
                            UrbanRuralClassification = 111,
                            VillageHeadName = "吕尊",
                            VillageName = "锦和社区"
                        },
                        new
                        {
                            Id = new Guid("6bb77758-8908-4d00-b364-e5e4cdcd8399"),
                            Address = "金华路1号",
                            AreaNumber = "320583106200",
                            ContactPhone = "0512-57293702",
                            GovernmentLevel = 5,
                            GroupCount = 26,
                            HighLevelAreaNumber = "320583106000",
                            SecretaryName = "宋翰学",
                            UrbanRuralClassification = 112,
                            VillageHeadName = "龙昊焱",
                            VillageName = "金华村"
                        },
                        new
                        {
                            Id = new Guid("8c9276a3-3932-4908-81c1-682638163101"),
                            Address = "商鞅路1号",
                            AreaNumber = "320583106204",
                            ContactPhone = "0512-50310612",
                            GovernmentLevel = 5,
                            GroupCount = 20,
                            HighLevelAreaNumber = "320583106000",
                            SecretaryName = "汤明亮",
                            UrbanRuralClassification = 112,
                            VillageHeadName = "吴咏德",
                            VillageName = "七桥村"
                        },
                        new
                        {
                            Id = new Guid("799abf8b-a0a8-4eaf-af94-7b6586947329"),
                            Address = "机场路与兴陵路交叉口往南200米",
                            AreaNumber = "320583106205",
                            ContactPhone = "0512-57441476",
                            GovernmentLevel = 5,
                            GroupCount = 27,
                            HighLevelAreaNumber = "320583106000",
                            SecretaryName = "邹俊雄",
                            UrbanRuralClassification = 220,
                            VillageHeadName = "程飞虎",
                            VillageName = "赵陵村"
                        },
                        new
                        {
                            Id = new Guid("32992e6f-66e4-4609-b13b-8691cbd620c5"),
                            Address = "川浩路22号",
                            AreaNumber = "320583106206",
                            ContactPhone = "0512-57441101",
                            GovernmentLevel = 5,
                            HighLevelAreaNumber = "320583106000",
                            SecretaryName = "丁弘亮",
                            UrbanRuralClassification = 220,
                            VillageHeadName = "龚炎彬",
                            VillageName = "吴加村"
                        },
                        new
                        {
                            Id = new Guid("8e289bac-8ba4-4028-a28d-5b111466e43c"),
                            Address = "港浦东路8号",
                            AreaNumber = "320583106207",
                            ContactPhone = "0512-5736863220",
                            GovernmentLevel = 5,
                            GroupCount = 33,
                            HighLevelAreaNumber = "320583106000",
                            SecretaryName = "史光临",
                            UrbanRuralClassification = 111,
                            VillageHeadName = "陈浦和",
                            VillageName = "三家村"
                        },
                        new
                        {
                            Id = new Guid("dabdf1ee-9bac-40b5-a179-7496e6ffa5fa"),
                            Address = "盛巷花园门卫北侧",
                            AreaNumber = "320583106209",
                            ContactPhone = "0512-57441616",
                            GovernmentLevel = 5,
                            GroupCount = 20,
                            HighLevelAreaNumber = "320583106000",
                            SecretaryName = "韩华藏",
                            UrbanRuralClassification = 111,
                            VillageHeadName = "萧泰河",
                            VillageName = "新塘村"
                        },
                        new
                        {
                            Id = new Guid("a6aaef6f-0bfe-4857-ae75-2dc0aa802f3e"),
                            Address = "震阳路与双娄路交叉口",
                            AreaNumber = "320583106210",
                            ContactPhone = "0512-57421150",
                            GovernmentLevel = 5,
                            GroupCount = 35,
                            HighLevelAreaNumber = "320583106000",
                            SecretaryName = "贺博艺",
                            UrbanRuralClassification = 122,
                            VillageHeadName = "冯鹏赋",
                            VillageName = "星金村"
                        },
                        new
                        {
                            Id = new Guid("0e40da36-e22e-4fe8-9876-87b3f9a8ecbc"),
                            Address = "陈邱家浜58号",
                            AreaNumber = "320583106211",
                            ContactPhone = "0512-50331469",
                            GovernmentLevel = 5,
                            GroupCount = 44,
                            HighLevelAreaNumber = "320583106000",
                            SecretaryName = "孙明杰",
                            UrbanRuralClassification = 220,
                            VillageHeadName = "谭睿诚",
                            VillageName = "新龙村"
                        },
                        new
                        {
                            Id = new Guid("d2842690-a338-45f5-bc0e-facaaa00004c"),
                            Address = "建林路往北到底向西100米",
                            AreaNumber = "320583106212",
                            ContactPhone = "0512-57120550",
                            GovernmentLevel = 5,
                            HighLevelAreaNumber = "320583106000",
                            SecretaryName = "万安怡",
                            UrbanRuralClassification = 220,
                            VillageHeadName = "萧波峻",
                            VillageName = "白米村"
                        },
                        new
                        {
                            Id = new Guid("9a2b7b4c-c7d2-45cf-9e1b-19db5afdfe91"),
                            Address = "南港文体站",
                            AreaNumber = "320583106214",
                            ContactPhone = "0512-57428327",
                            GovernmentLevel = 5,
                            GroupCount = 28,
                            HighLevelAreaNumber = "320583106000",
                            SecretaryName = "蒋英卓",
                            UrbanRuralClassification = 220,
                            VillageHeadName = "冯兴庆",
                            VillageName = "林庄村"
                        },
                        new
                        {
                            Id = new Guid("b7b0fc8c-cfd7-4e3b-8312-3d4896a7f188"),
                            Address = "安头村公交站台往南60米处",
                            AreaNumber = "320583106215",
                            ContactPhone = "0512-57428927",
                            GovernmentLevel = 5,
                            GroupCount = 25,
                            HighLevelAreaNumber = "320583106000",
                            SecretaryName = "郝嘉慕",
                            UrbanRuralClassification = 220,
                            VillageHeadName = "史意蕴",
                            VillageName = "安头村"
                        },
                        new
                        {
                            Id = new Guid("b4a8d870-3f08-4620-9699-1a9a670a1c5a"),
                            Address = "江浦南路与C325交叉处",
                            AreaNumber = "320583106219",
                            ContactPhone = "0512-57272133",
                            GovernmentLevel = 5,
                            GroupCount = 23,
                            HighLevelAreaNumber = "320583106000",
                            SecretaryName = "漕文彦",
                            UrbanRuralClassification = 220,
                            VillageHeadName = "许高岑",
                            VillageName = "姜杭村"
                        },
                        new
                        {
                            Id = new Guid("d88fcf93-0008-44f0-a19d-e87758f7f866"),
                            Address = "长江南路东侧与锦溪北交界",
                            AreaNumber = "320583106220",
                            ContactPhone = "0512-57256590",
                            GovernmentLevel = 5,
                            GroupCount = 21,
                            HighLevelAreaNumber = "320583106000",
                            SecretaryName = "汤英耀",
                            UrbanRuralClassification = 220,
                            VillageHeadName = "蒋嘉许",
                            VillageName = "尚明甸村"
                        },
                        new
                        {
                            Id = new Guid("be0f85d4-d6db-45fb-ab2d-da368c78bae0"),
                            Address = "姚家港北首",
                            AreaNumber = "320583106221",
                            ContactPhone = "0512-57117756",
                            GovernmentLevel = 5,
                            GroupCount = 22,
                            HighLevelAreaNumber = "320583106000",
                            SecretaryName = "杨成仁",
                            UrbanRuralClassification = 220,
                            VillageHeadName = "谢高义",
                            VillageName = "南姚村"
                        },
                        new
                        {
                            Id = new Guid("414b3a72-eb56-4011-9f77-58872c15bd37"),
                            Address = "淞沪西路与江浦南路交叉口",
                            AreaNumber = "320583106226",
                            ContactPhone = "0512-57255236",
                            GovernmentLevel = 5,
                            GroupCount = 49,
                            HighLevelAreaNumber = "320583106000",
                            SecretaryName = "顾绍祺",
                            UrbanRuralClassification = 220,
                            VillageHeadName = "金和怡",
                            VillageName = "大市村"
                        },
                        new
                        {
                            Id = new Guid("f8086c8a-b6aa-4293-9403-1444a20d2844"),
                            Address = "淞沪东路12号",
                            AreaNumber = "320583106227",
                            ContactPhone = "0512-57251131",
                            GovernmentLevel = 5,
                            HighLevelAreaNumber = "320583106000",
                            SecretaryName = "朱嘉石",
                            UrbanRuralClassification = 220,
                            VillageHeadName = "顾飞羽",
                            VillageName = "南吉山村"
                        });
                });

            modelBuilder.Entity("AspNetCore.Entity.VillagerGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("MemberNumber");

                    b.Property<string>("PrincipalAddress");

                    b.Property<string>("PrincipalEmail");

                    b.Property<string>("PrincipalName");

                    b.Property<string>("PrincipalPhone");

                    b.Property<string>("VillageGroupCode");

                    b.Property<string>("VillageName");

                    b.HasKey("Id");

                    b.ToTable("VillagerGroups");

                    b.HasData(
                        new
                        {
                            Id = new Guid("98d87d13-90e6-4ce7-b79b-492abe7c12a3"),
                            MemberNumber = 356,
                            PrincipalAddress = "张浦镇望江新村6幢206室",
                            PrincipalEmail = "wuxuefei@kszpwz.gov.cn",
                            PrincipalName = "吴雪峰",
                            PrincipalPhone = "0512-57841234",
                            VillageGroupCode = "001",
                            VillageName = "南港社区"
                        },
                        new
                        {
                            Id = new Guid("66431bd2-1caf-4124-9625-179b8f6bc648"),
                            MemberNumber = 412,
                            PrincipalAddress = "张浦镇富都新村3幢204室",
                            PrincipalEmail = "fangjitong@kszpfd.gov.cn",
                            PrincipalName = "方季同",
                            VillageGroupCode = "002",
                            VillageName = "南港社区"
                        },
                        new
                        {
                            Id = new Guid("0ebb8163-bff4-41f0-8648-51343aa89cc6"),
                            MemberNumber = 532,
                            PrincipalAddress = "张浦镇茶风新村1幢206室",
                            PrincipalEmail = "caogao@kszpcf.gov.cn",
                            PrincipalName = "蔡高",
                            VillageGroupCode = "003",
                            VillageName = "花园社区"
                        },
                        new
                        {
                            Id = new Guid("cd4e925b-8c1d-4eae-96e9-5e43a4e73220"),
                            MemberNumber = 253,
                            PrincipalAddress = "张浦镇富仁小区5幢102室",
                            PrincipalEmail = "changgaohan@kszpfr.gov.cn",
                            PrincipalName = "常高翰",
                            VillageGroupCode = "004",
                            VillageName = "大市社区"
                        },
                        new
                        {
                            Id = new Guid("ef65563f-9630-48f0-abd8-3ecec7f34fd3"),
                            MemberNumber = 512,
                            PrincipalAddress = "张浦镇风和日丽5幢1102室",
                            PrincipalEmail = "qianyancheng@kszpfhrl.gov.cn",
                            PrincipalName = "钱阳成",
                            VillageGroupCode = "005",
                            VillageName = "南港社区"
                        },
                        new
                        {
                            Id = new Guid("0c88f9fb-d72f-4c92-b75f-8e593fb00b85"),
                            MemberNumber = 567,
                            PrincipalAddress = "张浦镇枫情佳苑3幢306室",
                            PrincipalEmail = "kongzhiwen@kszpfqjy.gov.cn",
                            PrincipalName = "孔志文",
                            VillageGroupCode = "006",
                            VillageName = "新吴社区"
                        },
                        new
                        {
                            Id = new Guid("270ad27a-24bf-4705-8aa5-01aad7a69423"),
                            MemberNumber = 476,
                            PrincipalAddress = "张浦镇张浦村14号",
                            PrincipalEmail = "huhaorang@kszpzp.gov.cn",
                            PrincipalName = "胡浩壤",
                            VillageGroupCode = "007",
                            VillageName = "张浦社区"
                        },
                        new
                        {
                            Id = new Guid("b23b2eed-5782-41a8-9cef-69344163013d"),
                            MemberNumber = 345,
                            PrincipalAddress = "张浦镇张浦村142号",
                            PrincipalEmail = "xuexiuxian@kszpzp.gov.cn",
                            PrincipalName = "薛修贤",
                            VillageGroupCode = "008",
                            VillageName = "张浦社区"
                        },
                        new
                        {
                            Id = new Guid("184412b3-9b8a-47f2-b4f7-0da7bf3c48bd"),
                            MemberNumber = 452,
                            PrincipalAddress = "张浦镇银鹿新城3幢802室",
                            PrincipalEmail = "heliren@kszpylxc.gov.cn",
                            PrincipalName = "何立人",
                            VillageGroupCode = "009",
                            VillageName = "张浦社区"
                        },
                        new
                        {
                            Id = new Guid("3352edd9-4625-4069-af69-9702d3e89ccd"),
                            MemberNumber = 662,
                            PrincipalAddress = "张浦镇牡丹苑7幢502",
                            PrincipalEmail = "zhongjunde@kszpmdy.gov.cn",
                            PrincipalName = "钟俊德",
                            VillageGroupCode = "010",
                            VillageName = "周巷社区"
                        },
                        new
                        {
                            Id = new Guid("d6edc43f-f3e2-45b8-bd44-91248d6b0a6f"),
                            MemberNumber = 341,
                            PrincipalAddress = "张浦镇江南春堤14号",
                            PrincipalEmail = "jiatianzong@kszpjnkd.gov.cn",
                            PrincipalName = "贾天纵",
                            VillageGroupCode = "011",
                            VillageName = "新巷社区"
                        },
                        new
                        {
                            Id = new Guid("79c8f3c2-404b-4666-b2da-9d26c723df78"),
                            MemberNumber = 543,
                            PrincipalAddress = "张浦镇安居小区24号",
                            PrincipalEmail = "duanxuehai@kszpanxq.gov.cn",
                            PrincipalName = "段学海",
                            VillageGroupCode = "012",
                            VillageName = "大市社区"
                        });
                });

            modelBuilder.Entity("AspNetCore.Entity.UserRole", b =>
                {
                    b.HasOne("AspNetCore.Entity.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AspNetCore.Entity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
