// <auto-generated />
using System;
using AspNetCore.Entity.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace AspNetCore.Entity.Migrations
{
    [DbContext(typeof(MsContext))]
    [Migration("20190416141752_Migration17")]
    partial class Migration17
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:PostgresExtension:uuid-ossp", ",,")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("AspNetCore.Entity.AdminDivision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AreaNumber")
                        .IsRequired()
                        .HasMaxLength(15);

                    b.Property<int>("CountyNumber");

                    b.Property<int>("GovernmentLevel");

                    b.Property<string>("GovernmentName")
                        .IsRequired();

                    b.Property<string>("HighLevelAreaNumber");

                    b.Property<int>("TownNumber");

                    b.Property<int>("VillageGroupNumber");

                    b.Property<int>("VillageNumber");

                    b.HasKey("Id");

                    b.ToTable("AdminDivisions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5bb4638c-2f22-4ff1-823b-590ef4f19880"),
                            AreaNumber = "320583000000",
                            CountyNumber = 0,
                            GovernmentLevel = 3,
                            GovernmentName = "昆山市",
                            HighLevelAreaNumber = "",
                            TownNumber = 0,
                            VillageGroupNumber = 2205,
                            VillageNumber = 10
                        },
                        new
                        {
                            Id = new Guid("d372ad92-76d3-464a-bcb1-f24a93070b68"),
                            AreaNumber = "320583102000",
                            CountyNumber = 0,
                            GovernmentLevel = 4,
                            GovernmentName = "周市镇",
                            HighLevelAreaNumber = "320583000000",
                            TownNumber = 0,
                            VillageGroupNumber = 240,
                            VillageNumber = 29
                        },
                        new
                        {
                            Id = new Guid("56cb531f-8dca-4a5f-8810-74cc034aba1f"),
                            AreaNumber = "320583400000",
                            CountyNumber = 0,
                            GovernmentLevel = 4,
                            GovernmentName = "开发区",
                            HighLevelAreaNumber = "320583000000",
                            TownNumber = 12,
                            VillageGroupNumber = 312,
                            VillageNumber = 7
                        },
                        new
                        {
                            Id = new Guid("7354828e-6894-4ac7-bc52-f035975dd10a"),
                            AreaNumber = "320583104000",
                            CountyNumber = 0,
                            GovernmentLevel = 4,
                            GovernmentName = "花桥镇",
                            HighLevelAreaNumber = "320583000000",
                            TownNumber = 0,
                            VillageGroupNumber = 123,
                            VillageNumber = 13
                        },
                        new
                        {
                            Id = new Guid("22463c94-0d5d-482b-8b39-393f531ff908"),
                            AreaNumber = "320583106000",
                            CountyNumber = 0,
                            GovernmentLevel = 4,
                            GovernmentName = "张浦镇",
                            HighLevelAreaNumber = "320583000000",
                            TownNumber = 0,
                            VillageGroupNumber = 221,
                            VillageNumber = 12
                        },
                        new
                        {
                            Id = new Guid("90f1fd5d-bd2f-400a-8f92-82bfab5fbbfd"),
                            AreaNumber = "320583103000",
                            CountyNumber = 0,
                            GovernmentLevel = 4,
                            GovernmentName = "陆家镇",
                            HighLevelAreaNumber = "320583000000",
                            TownNumber = 0,
                            VillageGroupNumber = 231,
                            VillageNumber = 13
                        },
                        new
                        {
                            Id = new Guid("8ea618d7-f42d-4da6-aa43-43732c358ee0"),
                            AreaNumber = "320583101000",
                            CountyNumber = 0,
                            GovernmentLevel = 4,
                            GovernmentName = "巴城镇",
                            HighLevelAreaNumber = "320583000000",
                            TownNumber = 0,
                            VillageGroupNumber = 216,
                            VillageNumber = 13
                        },
                        new
                        {
                            Id = new Guid("05b80961-d221-47aa-aa6c-e28f0279929a"),
                            AreaNumber = "320583108000",
                            CountyNumber = 0,
                            GovernmentLevel = 4,
                            GovernmentName = "千灯镇",
                            HighLevelAreaNumber = "320583000000",
                            TownNumber = 0,
                            VillageGroupNumber = 213,
                            VillageNumber = 41
                        },
                        new
                        {
                            Id = new Guid("dd2e879d-a765-4560-ad01-756499b2c49d"),
                            AreaNumber = "320583105000",
                            CountyNumber = 0,
                            GovernmentLevel = 4,
                            GovernmentName = "淀山湖镇",
                            HighLevelAreaNumber = "320583000000",
                            TownNumber = 0,
                            VillageGroupNumber = 173,
                            VillageNumber = 11
                        },
                        new
                        {
                            Id = new Guid("348dedb3-17c8-4fd5-a1cc-d529ceacec58"),
                            AreaNumber = "320583107000",
                            CountyNumber = 0,
                            GovernmentLevel = 4,
                            GovernmentName = "周庄镇",
                            HighLevelAreaNumber = "320583000000",
                            TownNumber = 0,
                            VillageGroupNumber = 123,
                            VillageNumber = 31
                        },
                        new
                        {
                            Id = new Guid("20b39340-18c4-4341-8956-52a83524d65e"),
                            AreaNumber = "320583109000",
                            CountyNumber = 0,
                            GovernmentLevel = 4,
                            GovernmentName = "锦溪镇",
                            HighLevelAreaNumber = "320583000000",
                            TownNumber = 0,
                            VillageGroupNumber = 256,
                            VillageNumber = 22
                        },
                        new
                        {
                            Id = new Guid("a63e7b86-a663-4cee-a51b-d3bf593357b0"),
                            AreaNumber = "320583106001",
                            CountyNumber = 0,
                            GovernmentLevel = 5,
                            GovernmentName = "张浦社区",
                            HighLevelAreaNumber = "320583106000",
                            TownNumber = 0,
                            VillageGroupNumber = 12,
                            VillageNumber = 0
                        },
                        new
                        {
                            Id = new Guid("eb9ab1e9-6037-4067-94c1-eaf9b605e8b9"),
                            AreaNumber = "320583106002",
                            CountyNumber = 0,
                            GovernmentLevel = 5,
                            GovernmentName = "花园社区",
                            HighLevelAreaNumber = "320583106000",
                            TownNumber = 0,
                            VillageGroupNumber = 12,
                            VillageNumber = 0
                        },
                        new
                        {
                            Id = new Guid("11e04272-3550-4b39-90ec-aea11d4754b9"),
                            AreaNumber = "320583106003",
                            CountyNumber = 0,
                            GovernmentLevel = 5,
                            GovernmentName = "振苏社区",
                            HighLevelAreaNumber = "320583106000",
                            TownNumber = 0,
                            VillageGroupNumber = 12,
                            VillageNumber = 0
                        },
                        new
                        {
                            Id = new Guid("4a0ab535-6a59-4e39-a8ee-97e08a5e0904"),
                            AreaNumber = "320583106004",
                            CountyNumber = 0,
                            GovernmentLevel = 5,
                            GovernmentName = "南港社区",
                            HighLevelAreaNumber = "320583106000",
                            TownNumber = 0,
                            VillageGroupNumber = 12,
                            VillageNumber = 0
                        });
                });

            modelBuilder.Entity("AspNetCore.Entity.Core.Villager", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AnnualIncome");

                    b.Property<DateTime>("Birthday");

                    b.Property<string>("Education")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(3);

                    b.Property<bool>("HavingCriminalRecord");

                    b.Property<bool>("HavingIllegalRecord");

                    b.Property<string>("HomeAddress")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("MaritalStatus")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Villagers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2b52bc8c-be63-4c46-ac1c-f374f17217a8"),
                            AnnualIncome = 20000,
                            Birthday = new DateTime(1984, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Education = "高中",
                            Gender = "男",
                            HavingCriminalRecord = false,
                            HavingIllegalRecord = false,
                            HomeAddress = "向阳村3组14号",
                            MaritalStatus = "已婚",
                            Name = "张东"
                        },
                        new
                        {
                            Id = new Guid("02796c14-670a-4b09-bf4d-ceb73271e8e9"),
                            AnnualIncome = 17000,
                            Birthday = new DateTime(1972, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Education = "初中",
                            Gender = "男",
                            HavingCriminalRecord = false,
                            HavingIllegalRecord = false,
                            HomeAddress = "向阳村5组17号",
                            MaritalStatus = "已婚",
                            Name = "刘项"
                        },
                        new
                        {
                            Id = new Guid("61a62ca1-8ef8-46e1-b24f-54026f60d030"),
                            AnnualIncome = 50000,
                            Birthday = new DateTime(1990, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Education = "本科",
                            Gender = "男",
                            HavingCriminalRecord = false,
                            HavingIllegalRecord = false,
                            HomeAddress = "向阳村1组2号",
                            MaritalStatus = "未婚",
                            Name = "马伦"
                        });
                });

            modelBuilder.Entity("AspNetCore.Entity.DataCategroy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CategroyCode")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("CategroyName")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("DataCategroys");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bd3b91e9-28dd-4ddd-af42-ecfe97f4b659"),
                            CategroyCode = "001",
                            CategroyName = "城乡分类"
                        },
                        new
                        {
                            Id = new Guid("e37fe8c6-4a68-4c8c-8c6d-ca5562a3210b"),
                            CategroyCode = "002",
                            CategroyName = "行政级别"
                        },
                        new
                        {
                            Id = new Guid("f0bac4f3-7d06-4e4c-83d3-027e9767464c"),
                            CategroyCode = "003",
                            CategroyName = "政治面貌"
                        });
                });

            modelBuilder.Entity("AspNetCore.Entity.DataItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CategroyCode")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Content")
                        .IsRequired();

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("DataItems");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b2de2f77-0836-4371-a061-abe04b4463c1"),
                            CategroyCode = "001",
                            Content = "主城区",
                            ItemCode = "001"
                        },
                        new
                        {
                            Id = new Guid("ed9a4ba4-2542-4ab5-bbe8-119d2a5ef11b"),
                            CategroyCode = "001",
                            Content = "城乡结合区",
                            ItemCode = "002"
                        },
                        new
                        {
                            Id = new Guid("f6392b80-98af-4099-90e0-f4c01e4bdb98"),
                            CategroyCode = "001",
                            Content = "镇中心区",
                            ItemCode = "003"
                        },
                        new
                        {
                            Id = new Guid("d59b119c-9ac6-4aa5-b45e-5379dda7e90a"),
                            CategroyCode = "001",
                            Content = "特殊区域",
                            ItemCode = "004"
                        },
                        new
                        {
                            Id = new Guid("e43d7200-9b72-4145-af54-a68e185940a4"),
                            CategroyCode = "001",
                            Content = "乡中心区",
                            ItemCode = "005"
                        },
                        new
                        {
                            Id = new Guid("233fab47-1fc1-4e49-a012-f1b6f94a64cb"),
                            CategroyCode = "001",
                            Content = "村庄",
                            ItemCode = "006"
                        },
                        new
                        {
                            Id = new Guid("bf9cd914-56a7-4c83-9b96-e66e13a05635"),
                            CategroyCode = "002",
                            Content = "省级行政区",
                            ItemCode = "001"
                        },
                        new
                        {
                            Id = new Guid("4b776f25-906d-4dc2-ab77-4d452314e56a"),
                            CategroyCode = "002",
                            Content = "地级行政区",
                            ItemCode = "001"
                        },
                        new
                        {
                            Id = new Guid("9ef052d9-9a24-468c-acb8-b985d3e24ccc"),
                            CategroyCode = "002",
                            Content = "县级行政区",
                            ItemCode = "003"
                        },
                        new
                        {
                            Id = new Guid("fd734113-0987-45b6-bbaa-20c59f917ba7"),
                            CategroyCode = "002",
                            Content = "乡级行政区",
                            ItemCode = "004"
                        },
                        new
                        {
                            Id = new Guid("8cab79f9-3990-455a-9992-b0620f81bd9a"),
                            CategroyCode = "002",
                            Content = "村级行政区",
                            ItemCode = "005"
                        },
                        new
                        {
                            Id = new Guid("dead6e87-50d8-4d0f-a9c3-d2001982f977"),
                            CategroyCode = "003",
                            Content = "中共党员",
                            ItemCode = "001"
                        },
                        new
                        {
                            Id = new Guid("9a2f4fa7-d92b-463f-b316-cb2a791f2943"),
                            CategroyCode = "003",
                            Content = "中共预备党员",
                            ItemCode = "002"
                        },
                        new
                        {
                            Id = new Guid("444f92f6-97c2-446f-92fc-28351928ed21"),
                            CategroyCode = "003",
                            Content = "共青团员",
                            ItemCode = "003"
                        },
                        new
                        {
                            Id = new Guid("4c6af827-1d5c-4859-893b-9121db223750"),
                            CategroyCode = "003",
                            Content = "民革党员",
                            ItemCode = "004"
                        },
                        new
                        {
                            Id = new Guid("6541dac4-b68a-4f7f-bc1e-226d31d4a6ae"),
                            CategroyCode = "003",
                            Content = "民盟盟员",
                            ItemCode = "005"
                        },
                        new
                        {
                            Id = new Guid("bbb470ba-8ad2-4ca2-ba43-ef07399cf448"),
                            CategroyCode = "003",
                            Content = "民建会员",
                            ItemCode = "006"
                        },
                        new
                        {
                            Id = new Guid("f3138dff-cd98-44e6-8d23-1582190a84d9"),
                            CategroyCode = "003",
                            Content = "民进会员",
                            ItemCode = "007"
                        },
                        new
                        {
                            Id = new Guid("824e73b4-6442-4a42-b768-3c96e4161ec6"),
                            CategroyCode = "003",
                            Content = "农工党党员",
                            ItemCode = "008"
                        },
                        new
                        {
                            Id = new Guid("7f5ef092-2331-4cfe-95fe-5b130ec595db"),
                            CategroyCode = "003",
                            Content = "致公党党员",
                            ItemCode = "009"
                        },
                        new
                        {
                            Id = new Guid("798efa6e-b328-4718-a7c3-555a40c4fc34"),
                            CategroyCode = "003",
                            Content = "九三学社社员",
                            ItemCode = "010"
                        },
                        new
                        {
                            Id = new Guid("af9d994c-391e-4626-866b-0868ebfa2652"),
                            CategroyCode = "003",
                            Content = "台盟盟员",
                            ItemCode = "011"
                        },
                        new
                        {
                            Id = new Guid("dc82b1a0-cb7d-4257-936c-a79c20c94187"),
                            CategroyCode = "003",
                            Content = "无党派人士",
                            ItemCode = "012"
                        },
                        new
                        {
                            Id = new Guid("5c9fa5e4-20b5-4a6d-b93c-0739b157f2f8"),
                            CategroyCode = "003",
                            Content = "群众",
                            ItemCode = "013"
                        });
                });

            modelBuilder.Entity("AspNetCore.Entity.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("ContactPhone")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("DepartmentCode")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("DepartmentName")
                        .IsRequired();

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("Fax")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Notes");

                    b.Property<string>("PrincipalName")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aa77cf6a-ebe9-4c26-949d-a2445c598b2b"),
                            Address = "京东路469号",
                            ContactPhone = "0512-57623451",
                            DepartmentCode = "001",
                            DepartmentName = "张浦社区党支部委员会",
                            Email = "zhenxinguo@kszpzp.gov.cn",
                            Fax = "0512-54123412",
                            Notes = "",
                            PrincipalName = "郑兴国"
                        },
                        new
                        {
                            Id = new Guid("681778cc-ff76-49ba-a677-118d794dfce7"),
                            Address = "京东路469号",
                            ContactPhone = "0512-58289432",
                            DepartmentCode = "002",
                            DepartmentName = "张浦社区居民委员会",
                            Email = "chenlecheng@kszpzp.gov.cn",
                            Fax = "0512-59283414",
                            Notes = "临时兼任",
                            PrincipalName = "陈乐成"
                        },
                        new
                        {
                            Id = new Guid("cd1271c0-fdbb-4f74-be0e-a02ce1e4c287"),
                            Address = "花苑路与京东路交叉口西侧",
                            ContactPhone = "0512-54128123",
                            DepartmentCode = "003",
                            DepartmentName = "花园社区党支部委员会",
                            Email = "xugaoyi@kszpzp.gov.cn",
                            Fax = "0512-564178314",
                            PrincipalName = "许高义"
                        });
                });

            modelBuilder.Entity("AspNetCore.Entity.Family", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AccountCharacter")
                        .IsRequired()
                        .HasMaxLength(3);

                    b.Property<int>("AverageAnnualIncome");

                    b.Property<float>("AverageHousingArea");

                    b.Property<string>("FamilyCode")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Householder")
                        .IsRequired();

                    b.Property<float>("HousingArea");

                    b.Property<bool>("IsLowIncome");

                    b.Property<bool>("IsPoor");

                    b.Property<int>("PeopleNumber");

                    b.Property<string>("VillageGroupCode")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("VillageName")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Families");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f89b2e71-16c4-4adf-8af5-b394f705cf7a"),
                            AccountCharacter = "非农业",
                            AverageAnnualIncome = 5000,
                            AverageHousingArea = 20.84f,
                            FamilyCode = "001000",
                            Householder = "秦博厚",
                            HousingArea = 104.2f,
                            IsLowIncome = false,
                            IsPoor = false,
                            PeopleNumber = 5,
                            VillageGroupCode = "001",
                            VillageName = "张浦社区"
                        });
                });

            modelBuilder.Entity("AspNetCore.Entity.Member", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Birthday");

                    b.Property<string>("DepartmentCode")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Education")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<DateTime>("EntryTime");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(3);

                    b.Property<string>("HomeAddress")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("IdCardNumber")
                        .IsRequired()
                        .HasMaxLength(18);

                    b.Property<DateTime>("LeaveTime");

                    b.Property<string>("LengthOfService")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("MaritalStatus")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<string>("MemberCode")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("MemberName")
                        .IsRequired();

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<string>("PersonnelNature")
                        .HasMaxLength(10);

                    b.Property<string>("PoliticalStatus")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.HasKey("Id");

                    b.ToTable("Members");

                    b.HasData(
                        new
                        {
                            Id = new Guid("476f9256-6e01-4616-b96c-392a4787bd27"),
                            Birthday = new DateTime(1974, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentCode = "002",
                            Education = "本科",
                            EntryTime = new DateTime(2007, 2, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = "男",
                            HomeAddress = "张浦镇江北新村14号",
                            IdCardNumber = "320583197407056857",
                            LeaveTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LengthOfService = "12年",
                            MaritalStatus = "已婚",
                            MemberCode = "002000",
                            MemberName = "陈乐成",
                            Nationality = "汉族",
                            PoliticalStatus = "中共党员",
                            Position = "主任",
                            Status = "在职"
                        },
                        new
                        {
                            Id = new Guid("f573de7b-e913-4bf6-bf4a-797b1d791e2e"),
                            Birthday = new DateTime(1977, 7, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentCode = "002",
                            Education = "本科",
                            EntryTime = new DateTime(2002, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = "男",
                            HomeAddress = "张浦镇浦江北新村112号",
                            IdCardNumber = "320583197707087692",
                            LeaveTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LengthOfService = "17年",
                            MaritalStatus = "已婚",
                            MemberCode = "002001",
                            MemberName = "姜兴安",
                            Nationality = "汉族",
                            PoliticalStatus = "中共党员",
                            Position = "副主任",
                            Status = "在职"
                        },
                        new
                        {
                            Id = new Guid("051502d1-e38b-4121-bc93-d07a1a8c7e33"),
                            Birthday = new DateTime(1985, 4, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentCode = "002",
                            Education = "高中",
                            EntryTime = new DateTime(2010, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = "男",
                            HomeAddress = "张浦镇江北新村56号",
                            IdCardNumber = "320583198504178937",
                            LeaveTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LengthOfService = "9年",
                            MaritalStatus = "丧偶",
                            MemberCode = "002002",
                            MemberName = "于君昊",
                            Nationality = "汉族",
                            PoliticalStatus = "中共党员",
                            Position = "治调委员",
                            Status = "在职"
                        },
                        new
                        {
                            Id = new Guid("62793355-8133-4616-b24e-8cb23decd7b9"),
                            Birthday = new DateTime(1979, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentCode = "002",
                            Education = "硕士研究生",
                            EntryTime = new DateTime(2005, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = "男",
                            HomeAddress = "张浦镇江北新村12号",
                            IdCardNumber = "320583197910154878",
                            LeaveTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LengthOfService = "14年",
                            MaritalStatus = "离异",
                            MemberCode = "002003",
                            MemberName = "康志国",
                            Nationality = "汉族",
                            PoliticalStatus = "群众",
                            Position = "财经委员",
                            Status = "在职"
                        },
                        new
                        {
                            Id = new Guid("1400125e-cb30-4a2e-bf86-d2877078613f"),
                            Birthday = new DateTime(1987, 4, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentCode = "002",
                            Education = "本科",
                            EntryTime = new DateTime(2007, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = "女",
                            HomeAddress = "张浦镇江北新村17号",
                            IdCardNumber = "320583198704187965",
                            LeaveTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LengthOfService = "12年",
                            MaritalStatus = "已婚",
                            MemberCode = "002004",
                            MemberName = "赵陈红",
                            Nationality = "汉族",
                            PoliticalStatus = "群众",
                            Position = "妇女计生委员",
                            Status = "在职"
                        });
                });

            modelBuilder.Entity("AspNetCore.Entity.NonOperatingAssets", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("LibaryCollectionsNumber");

                    b.Property<int>("LibraryNumber");

                    b.Property<float>("OfficeBuildingArea");

                    b.Property<int>("OfficeBuildingNumber");

                    b.Property<float>("SeniorCitizenCenterArea");

                    b.Property<int>("SeniorCitizenCenterNumber");

                    b.Property<int>("ServiceStationNumber");

                    b.Property<float>("SportActivityRoomArea");

                    b.Property<int>("SportsActivityRoomNumber");

                    b.Property<float>("StaffQuarterArea");

                    b.Property<int>("StaffQuartersNumber");

                    b.Property<string>("VillageName")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("NonOperatingAssets");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a58112ea-23aa-4004-b659-9be52a19c82f"),
                            LibaryCollectionsNumber = 3000,
                            LibraryNumber = 1,
                            OfficeBuildingArea = 105f,
                            OfficeBuildingNumber = 1,
                            SeniorCitizenCenterArea = 450f,
                            SeniorCitizenCenterNumber = 1,
                            ServiceStationNumber = 4,
                            SportActivityRoomArea = 1000f,
                            SportsActivityRoomNumber = 2,
                            StaffQuarterArea = 1000f,
                            StaffQuartersNumber = 1,
                            VillageName = "张浦社区"
                        },
                        new
                        {
                            Id = new Guid("308bd861-9e2d-46af-9abd-0ad591dbb81a"),
                            LibaryCollectionsNumber = 2500,
                            LibraryNumber = 1,
                            OfficeBuildingArea = 172f,
                            OfficeBuildingNumber = 1,
                            SeniorCitizenCenterArea = 380f,
                            SeniorCitizenCenterNumber = 1,
                            ServiceStationNumber = 2,
                            SportActivityRoomArea = 800f,
                            SportsActivityRoomNumber = 1,
                            StaffQuarterArea = 1200f,
                            StaffQuartersNumber = 1,
                            VillageName = "花园社区"
                        },
                        new
                        {
                            Id = new Guid("5e08e8fb-8f39-4cd8-baf9-ccf29b27b086"),
                            LibaryCollectionsNumber = 5000,
                            LibraryNumber = 1,
                            OfficeBuildingArea = 250f,
                            OfficeBuildingNumber = 2,
                            SeniorCitizenCenterArea = 700f,
                            SeniorCitizenCenterNumber = 2,
                            ServiceStationNumber = 1,
                            SportActivityRoomArea = 1500f,
                            SportsActivityRoomNumber = 3,
                            StaffQuarterArea = 2000f,
                            StaffQuartersNumber = 2,
                            VillageName = "振苏社区"
                        });
                });

            modelBuilder.Entity("AspNetCore.Entity.PartyMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Birthday");

                    b.Property<string>("ContactPhone")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("DepartmentCode")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Education")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(3);

                    b.Property<bool>("IsFullMember");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<string>("PartyMemberCode")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("PartyMemberName")
                        .IsRequired();

                    b.Property<string>("PartyOrganizationName")
                        .IsRequired();

                    b.Property<string>("PartyPosition")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<string>("VillageName")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("PartyMembers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4470663d-1caa-4926-9f79-ae25c70ae3a9"),
                            Birthday = new DateTime(1974, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ContactPhone = "13057134712",
                            DepartmentCode = "001",
                            Education = "本科",
                            Gender = "男",
                            IsFullMember = true,
                            Nationality = "汉族",
                            PartyMemberCode = "001000",
                            PartyMemberName = "陈乐成",
                            PartyOrganizationName = "张浦社区党支部委员会",
                            PartyPosition = "无",
                            VillageName = "张浦社区"
                        });
                });

            modelBuilder.Entity("AspNetCore.Entity.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("RoleName")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("77a429ab-c3a5-49d9-b61d-96a8bd87a604"),
                            RoleName = "Admin"
                        },
                        new
                        {
                            Id = new Guid("a346c3ba-c25b-47e4-8d2d-8a26d9e3e181"),
                            RoleName = "Client"
                        },
                        new
                        {
                            Id = new Guid("b01c1b9d-daac-4419-ab67-281efca0f187"),
                            RoleName = "System"
                        });
                });

            modelBuilder.Entity("AspNetCore.Entity.Town", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("AreaNumber")
                        .IsRequired()
                        .HasMaxLength(15);

                    b.Property<string>("ChairmanName")
                        .IsRequired();

                    b.Property<string>("ContactPhone")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("GovernmentLevel");

                    b.Property<string>("MayorName")
                        .IsRequired();

                    b.Property<string>("SecretaryName")
                        .IsRequired();

                    b.Property<string>("TownName")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Towns");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c11259d1-605c-4e1a-8509-7cd5ac8172c3"),
                            Address = "前进西路168号",
                            AreaNumber = "320583102000",
                            ChairmanName = "祖冲之",
                            ContactPhone = "0512-57621053",
                            GovernmentLevel = 4,
                            MayorName = "陆机",
                            SecretaryName = "陆云",
                            TownName = "周市镇"
                        },
                        new
                        {
                            Id = new Guid("5d6848ad-84ae-4544-a90a-4648d27ce7b2"),
                            Address = "前进东路",
                            AreaNumber = "320583400000",
                            ChairmanName = "邢栋祥",
                            ContactPhone = "0512-57329416",
                            GovernmentLevel = 4,
                            MayorName = "逢建德",
                            SecretaryName = "匡俊智",
                            TownName = "开发区"
                        },
                        new
                        {
                            Id = new Guid("1e80f388-a343-4280-87f6-d3af20b13e20"),
                            Address = "花溪路358号",
                            AreaNumber = "320583104000",
                            ChairmanName = "武财章",
                            ContactPhone = "0512-57698733",
                            GovernmentLevel = 4,
                            MayorName = "王班",
                            SecretaryName = "吴启河",
                            TownName = "花桥镇"
                        },
                        new
                        {
                            Id = new Guid("c6c7a81f-7888-4b0a-bd3a-d84014e8f88c"),
                            Address = "华杨路188号",
                            AreaNumber = "320583106000",
                            ChairmanName = "成梦昆",
                            ContactPhone = "0512-57452503",
                            GovernmentLevel = 4,
                            MayorName = "刘赫伯",
                            SecretaryName = "蒋信迟",
                            TownName = "张浦镇"
                        },
                        new
                        {
                            Id = new Guid("77da3fd3-5cf9-414b-be4a-a37ca38cdf2a"),
                            Address = "菉溪路22号",
                            AreaNumber = "	320583103000",
                            ChairmanName = "李迪尉",
                            ContactPhone = "0512-57671003",
                            GovernmentLevel = 4,
                            MayorName = "梁灶慈",
                            SecretaryName = "刘群胜",
                            TownName = "陆家镇"
                        },
                        new
                        {
                            Id = new Guid("cc82abf1-087e-4b1d-b2cf-ede31b29d390"),
                            Address = "新澄路918号",
                            AreaNumber = "320583101000",
                            ChairmanName = "周伟",
                            ContactPhone = "0521-57656330",
                            GovernmentLevel = 4,
                            MayorName = "李迪尉",
                            SecretaryName = "钟开桦",
                            TownName = "巴城镇"
                        },
                        new
                        {
                            Id = new Guid("1c3351ce-94f0-458f-acf6-90f3d590829f"),
                            Address = "炎东路",
                            AreaNumber = "320583108000",
                            ChairmanName = "林修胜",
                            ContactPhone = "0512-36620396",
                            GovernmentLevel = 4,
                            MayorName = "张弥成",
                            SecretaryName = "时可北",
                            TownName = "千灯镇"
                        },
                        new
                        {
                            Id = new Guid("ecdc3c87-8648-4be7-aeb6-69694b8ff04f"),
                            Address = "府前路78号",
                            AreaNumber = "320583105000",
                            ChairmanName = "常般业",
                            ContactPhone = "0512-57488358",
                            GovernmentLevel = 4,
                            MayorName = "冯便磊",
                            SecretaryName = "颜尚冲",
                            TownName = "淀山湖镇"
                        },
                        new
                        {
                            Id = new Guid("e4e72280-68ec-4876-86ab-4f560ad5e4f5"),
                            Address = "淀南路100号",
                            AreaNumber = "320583107000",
                            ChairmanName = "陆先",
                            ContactPhone = "0521-57211236",
                            GovernmentLevel = 4,
                            MayorName = "王翱桦",
                            SecretaryName = "江衷力",
                            TownName = "周庄镇"
                        },
                        new
                        {
                            Id = new Guid("4ac58097-17b9-49ae-ad32-ff990e28f008"),
                            Address = "普庆路1号",
                            AreaNumber = "320583109000",
                            ChairmanName = "邹鉴夕",
                            ContactPhone = "0521-57231290",
                            GovernmentLevel = 4,
                            MayorName = "倪御奋",
                            SecretaryName = "姬道生",
                            TownName = "锦溪镇"
                        });
                });

            modelBuilder.Entity("AspNetCore.Entity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(150);

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1b3289ea-62b5-4da3-902f-7a9dd7dc4976"),
                            Password = "fu1Enyt+Hrdo9BNpDnSy5qb0tM7noN4WtRZwYUtkfpc=",
                            UserName = "admin"
                        },
                        new
                        {
                            Id = new Guid("d3c2340a-5564-4579-b931-84652733ce82"),
                            Password = "/uQH4FsnsFGBmvRluYOYHKDjUWimJiwnOV9WCRuEHQE=",
                            UserName = "user1"
                        },
                        new
                        {
                            Id = new Guid("699eec59-91cb-4bfa-a0f3-2fd0dcc87ede"),
                            Password = "vuQZWjwJouGCACBNyNwxQoSZc+8sK51nsCv34XSgelE=",
                            UserName = "user2"
                        },
                        new
                        {
                            Id = new Guid("eb03f11e-f117-4923-b03e-42b6df3e6635"),
                            Password = "h3fPS6qc1oAs9EImA3iGSZ9fH6Zl1yZJtFa6T3tiQko=",
                            UserName = "user3"
                        });
                });

            modelBuilder.Entity("AspNetCore.Entity.UserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("RoleId");

                    b.Property<Guid>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b667e8fa-727b-4bfa-a9ff-99d8b77a8ed0"),
                            RoleId = new Guid("77a429ab-c3a5-49d9-b61d-96a8bd87a604"),
                            UserId = new Guid("1b3289ea-62b5-4da3-902f-7a9dd7dc4976")
                        },
                        new
                        {
                            Id = new Guid("9a369a01-c2ce-4a7f-9b7d-1ab7eccf94a6"),
                            RoleId = new Guid("a346c3ba-c25b-47e4-8d2d-8a26d9e3e181"),
                            UserId = new Guid("d3c2340a-5564-4579-b931-84652733ce82")
                        },
                        new
                        {
                            Id = new Guid("c785dab3-6005-4ad7-af6c-ebb0875cdc73"),
                            RoleId = new Guid("a346c3ba-c25b-47e4-8d2d-8a26d9e3e181"),
                            UserId = new Guid("699eec59-91cb-4bfa-a0f3-2fd0dcc87ede")
                        },
                        new
                        {
                            Id = new Guid("bda299a7-c995-4018-9777-cfcd65a6c80b"),
                            RoleId = new Guid("77a429ab-c3a5-49d9-b61d-96a8bd87a604"),
                            UserId = new Guid("eb03f11e-f117-4923-b03e-42b6df3e6635")
                        },
                        new
                        {
                            Id = new Guid("f9cba504-88e4-4121-8471-d55a22b32813"),
                            RoleId = new Guid("b01c1b9d-daac-4419-ab67-281efca0f187"),
                            UserId = new Guid("1b3289ea-62b5-4da3-902f-7a9dd7dc4976")
                        });
                });

            modelBuilder.Entity("AspNetCore.Entity.Village", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("AreaNumber")
                        .IsRequired()
                        .HasMaxLength(15);

                    b.Property<string>("ContactPhone")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("GovernmentLevel");

                    b.Property<int?>("GroupCount");

                    b.Property<string>("HighLevelAreaNumber")
                        .IsRequired()
                        .HasMaxLength(15);

                    b.Property<string>("SecretaryName")
                        .IsRequired();

                    b.Property<int>("UrbanRuralClassification");

                    b.Property<string>("VillageHeadName")
                        .IsRequired();

                    b.Property<string>("VillageName")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Villages");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3d0678bc-bd4e-463c-a298-7e1e35b27a78"),
                            Address = "京东路469号",
                            AreaNumber = "320583106001",
                            ContactPhone = "0512-57441175",
                            GovernmentLevel = 5,
                            GroupCount = 12,
                            HighLevelAreaNumber = "320583106000",
                            SecretaryName = "尹乐和",
                            UrbanRuralClassification = 111,
                            VillageHeadName = "赵乐欣",
                            VillageName = "张浦社区"
                        },
                        new
                        {
                            Id = new Guid("e8e1bdba-05ab-4c74-b510-9102edcab268"),
                            Address = "花苑路与京东路交叉口西侧",
                            AreaNumber = "320583106002",
                            ContactPhone = "0512-36863123",
                            GovernmentLevel = 5,
                            GroupCount = 26,
                            HighLevelAreaNumber = "320583106000",
                            SecretaryName = "汤振海",
                            UrbanRuralClassification = 111,
                            VillageHeadName = "杜向阳",
                            VillageName = "花园社区"
                        },
                        new
                        {
                            Id = new Guid("701d2341-654c-4287-b537-82f23908ccc6"),
                            Address = "振苏六村",
                            AreaNumber = "320583106003",
                            ContactPhone = "0512-55270465",
                            GovernmentLevel = 5,
                            HighLevelAreaNumber = "320583106000",
                            SecretaryName = "廖景天",
                            UrbanRuralClassification = 111,
                            VillageHeadName = "崔泰宁",
                            VillageName = "振苏社区"
                        },
                        new
                        {
                            Id = new Guid("71cc1b6a-4d9d-4c93-bfb1-0e308395c7e0"),
                            Address = "震阳路126号",
                            AreaNumber = "320583106004",
                            ContactPhone = "0512-57428835",
                            GovernmentLevel = 5,
                            HighLevelAreaNumber = "320583106000",
                            SecretaryName = "阎乐池",
                            UrbanRuralClassification = 121,
                            VillageHeadName = "尹和蔼",
                            VillageName = "南港社区"
                        },
                        new
                        {
                            Id = new Guid("bcbaaab0-145d-462b-81f1-278e74333661"),
                            Address = "淞沪西路36号",
                            AreaNumber = "320583106005",
                            ContactPhone = "0512-57256550",
                            GovernmentLevel = 5,
                            HighLevelAreaNumber = "320583106000",
                            SecretaryName = "许宏畅",
                            UrbanRuralClassification = 220,
                            VillageHeadName = "薛兴为",
                            VillageName = "大市社区"
                        },
                        new
                        {
                            Id = new Guid("9782916c-4d34-4523-9cae-e3bafdc2363f"),
                            Address = "俱巷路894号",
                            AreaNumber = "320583106006",
                            ContactPhone = "0512-36691258",
                            GovernmentLevel = 5,
                            HighLevelAreaNumber = "320583106000",
                            SecretaryName = "孔浩思",
                            UrbanRuralClassification = 111,
                            VillageHeadName = "王康胜",
                            VillageName = "新巷社区"
                        },
                        new
                        {
                            Id = new Guid("291e0f83-78ad-4c22-9b54-80364d7047c3"),
                            Address = "商秧路178号",
                            AreaNumber = "320583106007",
                            ContactPhone = "0512-55272500",
                            GovernmentLevel = 5,
                            GroupCount = 26,
                            HighLevelAreaNumber = "320583106000",
                            SecretaryName = "吴俊晤",
                            UrbanRuralClassification = 111,
                            VillageHeadName = "石欣德",
                            VillageName = "新吴社区"
                        },
                        new
                        {
                            Id = new Guid("dae39b1b-8b25-4bcc-9b4d-5e8967b9e915"),
                            Address = "大直路504号",
                            AreaNumber = "320583106008",
                            ContactPhone = "0512-55272500",
                            GovernmentLevel = 5,
                            GroupCount = 23,
                            HighLevelAreaNumber = "320583106000",
                            SecretaryName = "梁奇希",
                            UrbanRuralClassification = 112,
                            VillageHeadName = "吕勇男",
                            VillageName = "大直社区"
                        },
                        new
                        {
                            Id = new Guid("59963257-8c81-4354-8fed-572df9a8437d"),
                            Address = "周巷路",
                            AreaNumber = "320583106009",
                            ContactPhone = "0512-57294577",
                            GovernmentLevel = 5,
                            GroupCount = 40,
                            HighLevelAreaNumber = "320583106000",
                            SecretaryName = "姜永昌",
                            UrbanRuralClassification = 111,
                            VillageHeadName = "吴凯凯",
                            VillageName = "周巷社区"
                        },
                        new
                        {
                            Id = new Guid("ba84bbd4-03fe-4fea-aed5-b4087f18e584"),
                            Address = "京东路588号",
                            AreaNumber = "320583106012",
                            ContactPhone = "0512-57883298",
                            GovernmentLevel = 5,
                            HighLevelAreaNumber = "320583106000",
                            SecretaryName = "龙澔",
                            UrbanRuralClassification = 111,
                            VillageHeadName = "汤烨磊",
                            VillageName = "亲和社区"
                        },
                        new
                        {
                            Id = new Guid("dd5656c1-bf8e-4c61-832a-570bb6d4b0f5"),
                            Address = "京东路731号",
                            AreaNumber = "320583106013",
                            ContactPhone = "0512-57278938",
                            GovernmentLevel = 5,
                            HighLevelAreaNumber = "320583106000",
                            SecretaryName = "李段",
                            UrbanRuralClassification = 111,
                            VillageHeadName = "吕尊",
                            VillageName = "锦和社区"
                        },
                        new
                        {
                            Id = new Guid("b9f1afc1-b142-48d0-be13-c36ffca0354a"),
                            Address = "金华路1号",
                            AreaNumber = "320583106200",
                            ContactPhone = "0512-57293702",
                            GovernmentLevel = 5,
                            GroupCount = 26,
                            HighLevelAreaNumber = "320583106000",
                            SecretaryName = "宋翰学",
                            UrbanRuralClassification = 112,
                            VillageHeadName = "龙昊焱",
                            VillageName = "金华村"
                        },
                        new
                        {
                            Id = new Guid("7d6c9f2a-dae5-46e5-985b-7fd6a1ac2f7c"),
                            Address = "商鞅路1号",
                            AreaNumber = "320583106204",
                            ContactPhone = "0512-50310612",
                            GovernmentLevel = 5,
                            GroupCount = 20,
                            HighLevelAreaNumber = "320583106000",
                            SecretaryName = "汤明亮",
                            UrbanRuralClassification = 112,
                            VillageHeadName = "吴咏德",
                            VillageName = "七桥村"
                        },
                        new
                        {
                            Id = new Guid("792c3b91-5b00-4085-a950-8298c2849f5c"),
                            Address = "机场路与兴陵路交叉口往南200米",
                            AreaNumber = "320583106205",
                            ContactPhone = "0512-57441476",
                            GovernmentLevel = 5,
                            GroupCount = 27,
                            HighLevelAreaNumber = "320583106000",
                            SecretaryName = "邹俊雄",
                            UrbanRuralClassification = 220,
                            VillageHeadName = "程飞虎",
                            VillageName = "赵陵村"
                        },
                        new
                        {
                            Id = new Guid("ab09246d-9555-4336-a79e-0066f373c4b0"),
                            Address = "川浩路22号",
                            AreaNumber = "320583106206",
                            ContactPhone = "0512-57441101",
                            GovernmentLevel = 5,
                            HighLevelAreaNumber = "320583106000",
                            SecretaryName = "丁弘亮",
                            UrbanRuralClassification = 220,
                            VillageHeadName = "龚炎彬",
                            VillageName = "吴加村"
                        },
                        new
                        {
                            Id = new Guid("8e64b820-69e9-4eac-8335-01580c74fb97"),
                            Address = "港浦东路8号",
                            AreaNumber = "320583106207",
                            ContactPhone = "0512-5736863220",
                            GovernmentLevel = 5,
                            GroupCount = 33,
                            HighLevelAreaNumber = "320583106000",
                            SecretaryName = "史光临",
                            UrbanRuralClassification = 111,
                            VillageHeadName = "陈浦和",
                            VillageName = "三家村"
                        },
                        new
                        {
                            Id = new Guid("0119b8c9-59e3-4f98-9f54-bfeccf682c17"),
                            Address = "盛巷花园门卫北侧",
                            AreaNumber = "320583106209",
                            ContactPhone = "0512-57441616",
                            GovernmentLevel = 5,
                            GroupCount = 20,
                            HighLevelAreaNumber = "320583106000",
                            SecretaryName = "韩华藏",
                            UrbanRuralClassification = 111,
                            VillageHeadName = "萧泰河",
                            VillageName = "新塘村"
                        },
                        new
                        {
                            Id = new Guid("a2bdaecb-5461-4fee-bad5-b938c401d187"),
                            Address = "震阳路与双娄路交叉口",
                            AreaNumber = "320583106210",
                            ContactPhone = "0512-57421150",
                            GovernmentLevel = 5,
                            GroupCount = 35,
                            HighLevelAreaNumber = "320583106000",
                            SecretaryName = "贺博艺",
                            UrbanRuralClassification = 122,
                            VillageHeadName = "冯鹏赋",
                            VillageName = "星金村"
                        },
                        new
                        {
                            Id = new Guid("6b2b98bc-3e07-4a96-a291-7587911f61eb"),
                            Address = "陈邱家浜58号",
                            AreaNumber = "320583106211",
                            ContactPhone = "0512-50331469",
                            GovernmentLevel = 5,
                            GroupCount = 44,
                            HighLevelAreaNumber = "320583106000",
                            SecretaryName = "孙明杰",
                            UrbanRuralClassification = 220,
                            VillageHeadName = "谭睿诚",
                            VillageName = "新龙村"
                        },
                        new
                        {
                            Id = new Guid("66092946-eb4a-4e3b-aef7-fa4b80f0d125"),
                            Address = "建林路往北到底向西100米",
                            AreaNumber = "320583106212",
                            ContactPhone = "0512-57120550",
                            GovernmentLevel = 5,
                            HighLevelAreaNumber = "320583106000",
                            SecretaryName = "万安怡",
                            UrbanRuralClassification = 220,
                            VillageHeadName = "萧波峻",
                            VillageName = "白米村"
                        },
                        new
                        {
                            Id = new Guid("fea32f8c-b12d-4c61-8840-7e905f1fd1b3"),
                            Address = "南港文体站",
                            AreaNumber = "320583106214",
                            ContactPhone = "0512-57428327",
                            GovernmentLevel = 5,
                            GroupCount = 28,
                            HighLevelAreaNumber = "320583106000",
                            SecretaryName = "蒋英卓",
                            UrbanRuralClassification = 220,
                            VillageHeadName = "冯兴庆",
                            VillageName = "林庄村"
                        },
                        new
                        {
                            Id = new Guid("c6b86833-8023-4391-b4c4-efd415ee4d44"),
                            Address = "安头村公交站台往南60米处",
                            AreaNumber = "320583106215",
                            ContactPhone = "0512-57428927",
                            GovernmentLevel = 5,
                            GroupCount = 25,
                            HighLevelAreaNumber = "320583106000",
                            SecretaryName = "郝嘉慕",
                            UrbanRuralClassification = 220,
                            VillageHeadName = "史意蕴",
                            VillageName = "安头村"
                        },
                        new
                        {
                            Id = new Guid("b67a1741-d0f3-4d00-b0f8-b5571a1a5079"),
                            Address = "江浦南路与C325交叉处",
                            AreaNumber = "320583106219",
                            ContactPhone = "0512-57272133",
                            GovernmentLevel = 5,
                            GroupCount = 23,
                            HighLevelAreaNumber = "320583106000",
                            SecretaryName = "漕文彦",
                            UrbanRuralClassification = 220,
                            VillageHeadName = "许高岑",
                            VillageName = "姜杭村"
                        },
                        new
                        {
                            Id = new Guid("a1861491-e283-4fb0-9c1b-416a6491965c"),
                            Address = "长江南路东侧与锦溪北交界",
                            AreaNumber = "320583106220",
                            ContactPhone = "0512-57256590",
                            GovernmentLevel = 5,
                            GroupCount = 21,
                            HighLevelAreaNumber = "320583106000",
                            SecretaryName = "汤英耀",
                            UrbanRuralClassification = 220,
                            VillageHeadName = "蒋嘉许",
                            VillageName = "尚明甸村"
                        },
                        new
                        {
                            Id = new Guid("61f96991-2a6c-406d-9ea2-c30fe09dcb83"),
                            Address = "姚家港北首",
                            AreaNumber = "320583106221",
                            ContactPhone = "0512-57117756",
                            GovernmentLevel = 5,
                            GroupCount = 22,
                            HighLevelAreaNumber = "320583106000",
                            SecretaryName = "杨成仁",
                            UrbanRuralClassification = 220,
                            VillageHeadName = "谢高义",
                            VillageName = "南姚村"
                        },
                        new
                        {
                            Id = new Guid("792e4d6e-53c1-4e59-b58b-d1a5e0a1d22e"),
                            Address = "淞沪西路与江浦南路交叉口",
                            AreaNumber = "320583106226",
                            ContactPhone = "0512-57255236",
                            GovernmentLevel = 5,
                            GroupCount = 49,
                            HighLevelAreaNumber = "320583106000",
                            SecretaryName = "顾绍祺",
                            UrbanRuralClassification = 220,
                            VillageHeadName = "金和怡",
                            VillageName = "大市村"
                        },
                        new
                        {
                            Id = new Guid("0872de0b-30b3-4482-97a0-e10187caeda6"),
                            Address = "淞沪东路12号",
                            AreaNumber = "320583106227",
                            ContactPhone = "0512-57251131",
                            GovernmentLevel = 5,
                            HighLevelAreaNumber = "320583106000",
                            SecretaryName = "朱嘉石",
                            UrbanRuralClassification = 220,
                            VillageHeadName = "顾飞羽",
                            VillageName = "南吉山村"
                        });
                });

            modelBuilder.Entity("AspNetCore.Entity.VillagerGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("MemberNumber");

                    b.Property<string>("PrincipalAddress")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("PrincipalEmail")
                        .IsRequired();

                    b.Property<string>("PrincipalName")
                        .IsRequired();

                    b.Property<string>("PrincipalPhone")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("VillageGroupCode")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("VillageName")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("VillagerGroups");

                    b.HasData(
                        new
                        {
                            Id = new Guid("cf5afe06-ae72-40ee-888c-1ebb397ac94e"),
                            MemberNumber = 356,
                            PrincipalAddress = "张浦镇望江新村6幢206室",
                            PrincipalEmail = "wuxuefei@kszpwz.gov.cn",
                            PrincipalName = "吴雪峰",
                            PrincipalPhone = "0512-57841234",
                            VillageGroupCode = "001",
                            VillageName = "南港社区"
                        },
                        new
                        {
                            Id = new Guid("92be18ea-f109-4f3f-b416-acab927240ca"),
                            MemberNumber = 412,
                            PrincipalAddress = "张浦镇富都新村3幢204室",
                            PrincipalEmail = "fangjitong@kszpfd.gov.cn",
                            PrincipalName = "方季同",
                            PrincipalPhone = "0512-42345124",
                            VillageGroupCode = "002",
                            VillageName = "南港社区"
                        },
                        new
                        {
                            Id = new Guid("671172d2-b44c-4a93-8f55-e3362dd99e88"),
                            MemberNumber = 532,
                            PrincipalAddress = "张浦镇茶风新村1幢206室",
                            PrincipalEmail = "caogao@kszpcf.gov.cn",
                            PrincipalName = "蔡高",
                            PrincipalPhone = "0512-42345244",
                            VillageGroupCode = "003",
                            VillageName = "花园社区"
                        },
                        new
                        {
                            Id = new Guid("80a562b2-e674-479b-8880-43365f3559b6"),
                            MemberNumber = 253,
                            PrincipalAddress = "张浦镇富仁小区5幢102室",
                            PrincipalEmail = "changgaohan@kszpfr.gov.cn",
                            PrincipalName = "常高翰",
                            PrincipalPhone = "0512-421235124",
                            VillageGroupCode = "004",
                            VillageName = "大市社区"
                        },
                        new
                        {
                            Id = new Guid("ef3f48b8-7882-4708-8322-785bd74ada9e"),
                            MemberNumber = 512,
                            PrincipalAddress = "张浦镇风和日丽5幢1102室",
                            PrincipalEmail = "qianyancheng@kszpfhrl.gov.cn",
                            PrincipalName = "钱阳成",
                            PrincipalPhone = "0512-52341124",
                            VillageGroupCode = "005",
                            VillageName = "南港社区"
                        },
                        new
                        {
                            Id = new Guid("2dc183c9-6946-4cd0-bbd1-7785d1f1e860"),
                            MemberNumber = 567,
                            PrincipalAddress = "张浦镇枫情佳苑3幢306室",
                            PrincipalEmail = "kongzhiwen@kszpfqjy.gov.cn",
                            PrincipalName = "孔志文",
                            PrincipalPhone = "0512-42323124",
                            VillageGroupCode = "006",
                            VillageName = "新吴社区"
                        },
                        new
                        {
                            Id = new Guid("55f4534d-af9d-4b56-b6c5-1690e1c07e7f"),
                            MemberNumber = 476,
                            PrincipalAddress = "张浦镇张浦村14号",
                            PrincipalEmail = "huhaorang@kszpzp.gov.cn",
                            PrincipalName = "胡浩壤",
                            PrincipalPhone = "0512-42341124",
                            VillageGroupCode = "007",
                            VillageName = "张浦社区"
                        },
                        new
                        {
                            Id = new Guid("e191ece3-858f-4750-85dc-5fadf71447e4"),
                            MemberNumber = 345,
                            PrincipalAddress = "张浦镇张浦村142号",
                            PrincipalEmail = "xuexiuxian@kszpzp.gov.cn",
                            PrincipalName = "薛修贤",
                            PrincipalPhone = "0512-423125124",
                            VillageGroupCode = "008",
                            VillageName = "张浦社区"
                        },
                        new
                        {
                            Id = new Guid("58666900-9ce5-4cf5-b8d2-20f9609fa7c9"),
                            MemberNumber = 452,
                            PrincipalAddress = "张浦镇银鹿新城3幢802室",
                            PrincipalEmail = "heliren@kszpylxc.gov.cn",
                            PrincipalName = "何立人",
                            PrincipalPhone = "0512-523125124",
                            VillageGroupCode = "009",
                            VillageName = "张浦社区"
                        },
                        new
                        {
                            Id = new Guid("ecd16be6-cdec-4086-bb42-bd83db47490f"),
                            MemberNumber = 662,
                            PrincipalAddress = "张浦镇牡丹苑7幢502",
                            PrincipalEmail = "zhongjunde@kszpmdy.gov.cn",
                            PrincipalName = "钟俊德",
                            PrincipalPhone = "0512-12345124",
                            VillageGroupCode = "010",
                            VillageName = "周巷社区"
                        },
                        new
                        {
                            Id = new Guid("bc6dfbb0-0244-478b-bd94-c065ae59a15b"),
                            MemberNumber = 341,
                            PrincipalAddress = "张浦镇江南春堤14号",
                            PrincipalEmail = "jiatianzong@kszpjnkd.gov.cn",
                            PrincipalName = "贾天纵",
                            PrincipalPhone = "0512-43423124",
                            VillageGroupCode = "011",
                            VillageName = "新巷社区"
                        },
                        new
                        {
                            Id = new Guid("a70b3f77-ef1d-41db-a97e-277dc087521e"),
                            MemberNumber = 543,
                            PrincipalAddress = "张浦镇安居小区24号",
                            PrincipalEmail = "duanxuehai@kszpanxq.gov.cn",
                            PrincipalName = "段学海",
                            PrincipalPhone = "0512-12455124",
                            VillageGroupCode = "012",
                            VillageName = "大市社区"
                        });
                });

            modelBuilder.Entity("AspNetCore.Entity.UserRole", b =>
                {
                    b.HasOne("AspNetCore.Entity.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AspNetCore.Entity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
