// <auto-generated />
using System;
using AspNetCore.Entity.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace AspNetCore.Entity.Migrations
{
    [DbContext(typeof(MsContext))]
    [Migration("20190319050818_Migration00")]
    partial class Migration00
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:PostgresExtension:uuid-ossp", ",,")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("AspNetCore.Entity.Core.Villager", b =>
                {
                    b.Property<Guid>("VillagerId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AnnualIncome");

                    b.Property<DateTime>("Birthday");

                    b.Property<string>("Education");

                    b.Property<string>("Gender")
                        .IsRequired();

                    b.Property<bool>("HavingCriminalRecord");

                    b.Property<bool>("HavingIllegalRecord");

                    b.Property<string>("HomeAddress")
                        .IsRequired();

                    b.Property<string>("MaritalStatus");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("VillagerId");

                    b.ToTable("Villagers");
                });

            modelBuilder.Entity("AspNetCore.Entity.Role", b =>
                {
                    b.Property<Guid>("RoleId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("RoleName")
                        .IsRequired();

                    b.HasKey("RoleId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = new Guid("36f4a336-5239-4519-8f53-0783d5fa7f27"),
                            RoleName = "Admin"
                        },
                        new
                        {
                            RoleId = new Guid("aed0a076-7111-4a5e-bfff-6055850a11cd"),
                            RoleName = "Client"
                        },
                        new
                        {
                            RoleId = new Guid("382417ca-b56d-47bc-8db2-e9c1930592c3"),
                            RoleName = "System"
                        });
                });

            modelBuilder.Entity("AspNetCore.Entity.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Password")
                        .IsRequired();

                    b.Property<string>("UserName")
                        .IsRequired();

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("4ba9e9b7-36ef-40da-8e3c-849c2673cf0f"),
                            Password = "admin",
                            UserName = "admin"
                        },
                        new
                        {
                            UserId = new Guid("8e423e51-56e6-4ef5-85fa-6373c96269c5"),
                            Password = "user1",
                            UserName = "user1"
                        },
                        new
                        {
                            UserId = new Guid("859c27dd-48b3-4512-80ad-c3c7a46118e4"),
                            Password = "user2",
                            UserName = "user2"
                        },
                        new
                        {
                            UserId = new Guid("78e16794-f853-445c-9879-f150f8f817be"),
                            Password = "user3",
                            UserName = "user3"
                        });
                });

            modelBuilder.Entity("AspNetCore.Entity.UserRole", b =>
                {
                    b.Property<Guid>("UserRoleId")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("RoleId");

                    b.Property<Guid>("UserId");

                    b.HasKey("UserRoleId");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            UserRoleId = new Guid("82f2fdb8-4f10-41f7-abb1-c06f88cae53e"),
                            RoleId = new Guid("36f4a336-5239-4519-8f53-0783d5fa7f27"),
                            UserId = new Guid("4ba9e9b7-36ef-40da-8e3c-849c2673cf0f")
                        },
                        new
                        {
                            UserRoleId = new Guid("530a4517-764d-437f-9144-3bf9163bcf3a"),
                            RoleId = new Guid("aed0a076-7111-4a5e-bfff-6055850a11cd"),
                            UserId = new Guid("8e423e51-56e6-4ef5-85fa-6373c96269c5")
                        },
                        new
                        {
                            UserRoleId = new Guid("b59896fc-c433-4267-8a13-edacfa4233a4"),
                            RoleId = new Guid("aed0a076-7111-4a5e-bfff-6055850a11cd"),
                            UserId = new Guid("859c27dd-48b3-4512-80ad-c3c7a46118e4")
                        },
                        new
                        {
                            UserRoleId = new Guid("2251f609-dbbd-4055-841d-a2a89e934529"),
                            RoleId = new Guid("36f4a336-5239-4519-8f53-0783d5fa7f27"),
                            UserId = new Guid("78e16794-f853-445c-9879-f150f8f817be")
                        });
                });

            modelBuilder.Entity("AspNetCore.Entity.UserRole", b =>
                {
                    b.HasOne("AspNetCore.Entity.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AspNetCore.Entity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
