// <auto-generated />
using System;
using AspNetCore.Entity.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace AspNetCore.Entity.Migrations
{
    [DbContext(typeof(MsContext))]
    [Migration("20190418021144_Migration18")]
    partial class Migration18
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:PostgresExtension:uuid-ossp", ",,")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("AspNetCore.Entity.AdminDivision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AreaNumber")
                        .IsRequired()
                        .HasMaxLength(15);

                    b.Property<int>("CountyNumber");

                    b.Property<int>("GovernmentLevel");

                    b.Property<string>("GovernmentName")
                        .IsRequired();

                    b.Property<string>("HighLevelAreaNumber");

                    b.Property<int>("TownNumber");

                    b.Property<int>("VillageGroupNumber");

                    b.Property<int>("VillageNumber");

                    b.HasKey("Id");

                    b.ToTable("AdminDivisions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3050b17c-ef0e-4097-84e8-c0e560d687fb"),
                            AreaNumber = "320583000000",
                            CountyNumber = 0,
                            GovernmentLevel = 3,
                            GovernmentName = "昆山市",
                            HighLevelAreaNumber = "",
                            TownNumber = 0,
                            VillageGroupNumber = 2205,
                            VillageNumber = 10
                        },
                        new
                        {
                            Id = new Guid("7a2f5586-7ad3-4ee5-a348-ec60f1b68c3e"),
                            AreaNumber = "320583102000",
                            CountyNumber = 0,
                            GovernmentLevel = 4,
                            GovernmentName = "周市镇",
                            HighLevelAreaNumber = "320583000000",
                            TownNumber = 0,
                            VillageGroupNumber = 240,
                            VillageNumber = 29
                        },
                        new
                        {
                            Id = new Guid("8f387385-d902-4dc4-b305-4cc1e8edde2f"),
                            AreaNumber = "320583400000",
                            CountyNumber = 0,
                            GovernmentLevel = 4,
                            GovernmentName = "开发区",
                            HighLevelAreaNumber = "320583000000",
                            TownNumber = 12,
                            VillageGroupNumber = 312,
                            VillageNumber = 7
                        },
                        new
                        {
                            Id = new Guid("961d8532-d2f2-425c-93ac-00ce5513435e"),
                            AreaNumber = "320583104000",
                            CountyNumber = 0,
                            GovernmentLevel = 4,
                            GovernmentName = "花桥镇",
                            HighLevelAreaNumber = "320583000000",
                            TownNumber = 0,
                            VillageGroupNumber = 123,
                            VillageNumber = 13
                        },
                        new
                        {
                            Id = new Guid("70ef30b4-3a6c-4b9b-ac61-77ead2766278"),
                            AreaNumber = "320583106000",
                            CountyNumber = 0,
                            GovernmentLevel = 4,
                            GovernmentName = "张浦镇",
                            HighLevelAreaNumber = "320583000000",
                            TownNumber = 0,
                            VillageGroupNumber = 221,
                            VillageNumber = 12
                        },
                        new
                        {
                            Id = new Guid("720cd26a-f13c-4846-8853-0d12ae5618cd"),
                            AreaNumber = "320583103000",
                            CountyNumber = 0,
                            GovernmentLevel = 4,
                            GovernmentName = "陆家镇",
                            HighLevelAreaNumber = "320583000000",
                            TownNumber = 0,
                            VillageGroupNumber = 231,
                            VillageNumber = 13
                        },
                        new
                        {
                            Id = new Guid("7ee5647d-2201-424e-bfa3-8f7524ef670c"),
                            AreaNumber = "320583101000",
                            CountyNumber = 0,
                            GovernmentLevel = 4,
                            GovernmentName = "巴城镇",
                            HighLevelAreaNumber = "320583000000",
                            TownNumber = 0,
                            VillageGroupNumber = 216,
                            VillageNumber = 13
                        },
                        new
                        {
                            Id = new Guid("ca32aedb-c53f-431b-93a1-222ddea18ef2"),
                            AreaNumber = "320583108000",
                            CountyNumber = 0,
                            GovernmentLevel = 4,
                            GovernmentName = "千灯镇",
                            HighLevelAreaNumber = "320583000000",
                            TownNumber = 0,
                            VillageGroupNumber = 213,
                            VillageNumber = 41
                        },
                        new
                        {
                            Id = new Guid("52ae5052-2029-495c-b328-26bd9a6f7b84"),
                            AreaNumber = "320583105000",
                            CountyNumber = 0,
                            GovernmentLevel = 4,
                            GovernmentName = "淀山湖镇",
                            HighLevelAreaNumber = "320583000000",
                            TownNumber = 0,
                            VillageGroupNumber = 173,
                            VillageNumber = 11
                        },
                        new
                        {
                            Id = new Guid("c7b7e316-2d68-40d8-bcd3-63cd44deb391"),
                            AreaNumber = "320583107000",
                            CountyNumber = 0,
                            GovernmentLevel = 4,
                            GovernmentName = "周庄镇",
                            HighLevelAreaNumber = "320583000000",
                            TownNumber = 0,
                            VillageGroupNumber = 123,
                            VillageNumber = 31
                        },
                        new
                        {
                            Id = new Guid("4786b76d-dcbb-4e48-9564-94ea61d556c9"),
                            AreaNumber = "320583109000",
                            CountyNumber = 0,
                            GovernmentLevel = 4,
                            GovernmentName = "锦溪镇",
                            HighLevelAreaNumber = "320583000000",
                            TownNumber = 0,
                            VillageGroupNumber = 256,
                            VillageNumber = 22
                        },
                        new
                        {
                            Id = new Guid("dacb0d56-1722-4680-8c78-94c929fc6484"),
                            AreaNumber = "320583106001",
                            CountyNumber = 0,
                            GovernmentLevel = 5,
                            GovernmentName = "张浦社区",
                            HighLevelAreaNumber = "320583106000",
                            TownNumber = 0,
                            VillageGroupNumber = 12,
                            VillageNumber = 0
                        },
                        new
                        {
                            Id = new Guid("28caee20-031a-40f0-8d9c-fb6e4e8efc4e"),
                            AreaNumber = "320583106002",
                            CountyNumber = 0,
                            GovernmentLevel = 5,
                            GovernmentName = "花园社区",
                            HighLevelAreaNumber = "320583106000",
                            TownNumber = 0,
                            VillageGroupNumber = 12,
                            VillageNumber = 0
                        },
                        new
                        {
                            Id = new Guid("a40d0f95-31f4-4596-9e1a-b19a1b185550"),
                            AreaNumber = "320583106003",
                            CountyNumber = 0,
                            GovernmentLevel = 5,
                            GovernmentName = "振苏社区",
                            HighLevelAreaNumber = "320583106000",
                            TownNumber = 0,
                            VillageGroupNumber = 12,
                            VillageNumber = 0
                        },
                        new
                        {
                            Id = new Guid("33eafd15-20b7-4f06-b5c7-00cdc468c78a"),
                            AreaNumber = "320583106004",
                            CountyNumber = 0,
                            GovernmentLevel = 5,
                            GovernmentName = "南港社区",
                            HighLevelAreaNumber = "320583106000",
                            TownNumber = 0,
                            VillageGroupNumber = 12,
                            VillageNumber = 0
                        });
                });

            modelBuilder.Entity("AspNetCore.Entity.Core.Villager", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AnnualIncome");

                    b.Property<DateTime>("Birthday");

                    b.Property<string>("Education")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(3);

                    b.Property<bool>("HavingCriminalRecord");

                    b.Property<bool>("HavingIllegalRecord");

                    b.Property<string>("HomeAddress")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("MaritalStatus")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Villagers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3c1429a2-782e-4eb1-ada3-7f50d9f2ca68"),
                            AnnualIncome = 20000,
                            Birthday = new DateTime(1984, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Education = "高中",
                            Gender = "男",
                            HavingCriminalRecord = false,
                            HavingIllegalRecord = false,
                            HomeAddress = "向阳村3组14号",
                            MaritalStatus = "已婚",
                            Name = "张东"
                        },
                        new
                        {
                            Id = new Guid("e028691a-0712-4134-a775-089ae3e1c3e5"),
                            AnnualIncome = 17000,
                            Birthday = new DateTime(1972, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Education = "初中",
                            Gender = "男",
                            HavingCriminalRecord = false,
                            HavingIllegalRecord = false,
                            HomeAddress = "向阳村5组17号",
                            MaritalStatus = "已婚",
                            Name = "刘项"
                        },
                        new
                        {
                            Id = new Guid("cb5174b1-499a-4d36-85fb-de2d5f2966d1"),
                            AnnualIncome = 50000,
                            Birthday = new DateTime(1990, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Education = "本科",
                            Gender = "男",
                            HavingCriminalRecord = false,
                            HavingIllegalRecord = false,
                            HomeAddress = "向阳村1组2号",
                            MaritalStatus = "未婚",
                            Name = "马伦"
                        });
                });

            modelBuilder.Entity("AspNetCore.Entity.DataCategroy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CategroyCode")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("CategroyName")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("DataCategroys");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bfe5fb4f-7ac2-41da-bac6-0461574f095e"),
                            CategroyCode = "001",
                            CategroyName = "城乡分类"
                        },
                        new
                        {
                            Id = new Guid("172827e1-3898-428d-973f-5a234a52c45e"),
                            CategroyCode = "002",
                            CategroyName = "行政级别"
                        },
                        new
                        {
                            Id = new Guid("a8d2c088-0a13-46ed-9450-ba35dd579f61"),
                            CategroyCode = "003",
                            CategroyName = "政治面貌"
                        });
                });

            modelBuilder.Entity("AspNetCore.Entity.DataItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CategroyCode")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Content")
                        .IsRequired();

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("DataItems");

                    b.HasData(
                        new
                        {
                            Id = new Guid("412d8622-6e3e-4a58-a2f5-7733305cba26"),
                            CategroyCode = "001",
                            Content = "主城区",
                            ItemCode = "001"
                        },
                        new
                        {
                            Id = new Guid("a4b3eb1e-0a7d-44e3-a48e-d1374eb7461f"),
                            CategroyCode = "001",
                            Content = "城乡结合区",
                            ItemCode = "002"
                        },
                        new
                        {
                            Id = new Guid("43b5040c-b5a8-4949-ba84-cbcec74e2528"),
                            CategroyCode = "001",
                            Content = "镇中心区",
                            ItemCode = "003"
                        },
                        new
                        {
                            Id = new Guid("d1bbc4ea-3f68-43ff-a81c-e47b7ff745cd"),
                            CategroyCode = "001",
                            Content = "特殊区域",
                            ItemCode = "004"
                        },
                        new
                        {
                            Id = new Guid("5115bd0b-568b-487b-8405-c986cf40ac83"),
                            CategroyCode = "001",
                            Content = "乡中心区",
                            ItemCode = "005"
                        },
                        new
                        {
                            Id = new Guid("6c17954d-ad8a-45a8-b0f5-a104e7d50452"),
                            CategroyCode = "001",
                            Content = "村庄",
                            ItemCode = "006"
                        },
                        new
                        {
                            Id = new Guid("300c2da1-9cc5-4d02-a96f-4b97a6e27504"),
                            CategroyCode = "002",
                            Content = "省级行政区",
                            ItemCode = "001"
                        },
                        new
                        {
                            Id = new Guid("36045de4-c52d-4cb3-8abc-8657c86f9ddf"),
                            CategroyCode = "002",
                            Content = "地级行政区",
                            ItemCode = "001"
                        },
                        new
                        {
                            Id = new Guid("6e1ac252-0015-4466-bd90-f217814d7bb3"),
                            CategroyCode = "002",
                            Content = "县级行政区",
                            ItemCode = "003"
                        },
                        new
                        {
                            Id = new Guid("d73cf3f0-a47b-4226-96bf-dc020834a0cd"),
                            CategroyCode = "002",
                            Content = "乡级行政区",
                            ItemCode = "004"
                        },
                        new
                        {
                            Id = new Guid("faa9b505-ec19-484b-8f43-806207d197ca"),
                            CategroyCode = "002",
                            Content = "村级行政区",
                            ItemCode = "005"
                        },
                        new
                        {
                            Id = new Guid("06a5bca4-c977-4ea0-96bb-5306779c161a"),
                            CategroyCode = "003",
                            Content = "中共党员",
                            ItemCode = "001"
                        },
                        new
                        {
                            Id = new Guid("3ebe8eca-021f-4bee-96b2-f7c9738f0ae2"),
                            CategroyCode = "003",
                            Content = "中共预备党员",
                            ItemCode = "002"
                        },
                        new
                        {
                            Id = new Guid("0d770610-a8bb-47a8-9a52-d80c107d5bca"),
                            CategroyCode = "003",
                            Content = "共青团员",
                            ItemCode = "003"
                        },
                        new
                        {
                            Id = new Guid("dc11aed5-5d02-4486-a755-487203a7a7fa"),
                            CategroyCode = "003",
                            Content = "民革党员",
                            ItemCode = "004"
                        },
                        new
                        {
                            Id = new Guid("810b0778-7dae-4934-b8e3-885ecc68b8c8"),
                            CategroyCode = "003",
                            Content = "民盟盟员",
                            ItemCode = "005"
                        },
                        new
                        {
                            Id = new Guid("1dbaa2a9-2efe-4b00-86b5-47a03faf1d12"),
                            CategroyCode = "003",
                            Content = "民建会员",
                            ItemCode = "006"
                        },
                        new
                        {
                            Id = new Guid("1dae85bd-a832-4e12-b05e-69452bb25e44"),
                            CategroyCode = "003",
                            Content = "民进会员",
                            ItemCode = "007"
                        },
                        new
                        {
                            Id = new Guid("c70c2fad-8cc8-4d18-9528-b07fe49426c0"),
                            CategroyCode = "003",
                            Content = "农工党党员",
                            ItemCode = "008"
                        },
                        new
                        {
                            Id = new Guid("ae4a6c12-8205-43d4-ae9f-af9acd6ffdad"),
                            CategroyCode = "003",
                            Content = "致公党党员",
                            ItemCode = "009"
                        },
                        new
                        {
                            Id = new Guid("b141aec5-0627-457a-8666-981f5362e04e"),
                            CategroyCode = "003",
                            Content = "九三学社社员",
                            ItemCode = "010"
                        },
                        new
                        {
                            Id = new Guid("48ed0a33-8056-40cf-b26b-ea415cb1d288"),
                            CategroyCode = "003",
                            Content = "台盟盟员",
                            ItemCode = "011"
                        },
                        new
                        {
                            Id = new Guid("a301919c-c60e-4bda-8f6c-249c7f7b8162"),
                            CategroyCode = "003",
                            Content = "无党派人士",
                            ItemCode = "012"
                        },
                        new
                        {
                            Id = new Guid("2fd8a9cd-2160-42aa-9cc4-14719d769867"),
                            CategroyCode = "003",
                            Content = "群众",
                            ItemCode = "013"
                        });
                });

            modelBuilder.Entity("AspNetCore.Entity.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("ContactPhone")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("DepartmentCode")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("DepartmentName")
                        .IsRequired();

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("Fax")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Notes");

                    b.Property<string>("PrincipalName")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("79c6850a-3e57-4148-83f6-8d61118ebf84"),
                            Address = "京东路469号",
                            ContactPhone = "0512-57623451",
                            DepartmentCode = "001",
                            DepartmentName = "张浦社区党支部委员会",
                            Email = "zhenxinguo@kszpzp.gov.cn",
                            Fax = "0512-54123412",
                            Notes = "",
                            PrincipalName = "郑兴国"
                        },
                        new
                        {
                            Id = new Guid("16f17ff7-07b3-4934-b8f2-fc4120f50fa5"),
                            Address = "京东路469号",
                            ContactPhone = "0512-58289432",
                            DepartmentCode = "002",
                            DepartmentName = "张浦社区居民委员会",
                            Email = "chenlecheng@kszpzp.gov.cn",
                            Fax = "0512-59283414",
                            Notes = "临时兼任",
                            PrincipalName = "陈乐成"
                        },
                        new
                        {
                            Id = new Guid("4778b943-036d-4e28-9a48-a71895c4ba26"),
                            Address = "花苑路与京东路交叉口西侧",
                            ContactPhone = "0512-54128123",
                            DepartmentCode = "003",
                            DepartmentName = "花园社区党支部委员会",
                            Email = "xugaoyi@kszpzp.gov.cn",
                            Fax = "0512-564178314",
                            PrincipalName = "许高义"
                        });
                });

            modelBuilder.Entity("AspNetCore.Entity.Family", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AccountCharacter")
                        .IsRequired()
                        .HasMaxLength(3);

                    b.Property<int>("AverageAnnualIncome");

                    b.Property<float>("AverageHousingArea");

                    b.Property<string>("FamilyCode")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Householder")
                        .IsRequired();

                    b.Property<float>("HousingArea");

                    b.Property<bool>("IsLowIncome");

                    b.Property<bool>("IsPoor");

                    b.Property<int>("PeopleNumber");

                    b.Property<string>("VillageGroupCode")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("VillageName")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Families");

                    b.HasData(
                        new
                        {
                            Id = new Guid("126d7d3a-f68f-4759-a73d-1ee556910da9"),
                            AccountCharacter = "非农业",
                            AverageAnnualIncome = 5000,
                            AverageHousingArea = 20.84f,
                            FamilyCode = "001000",
                            Householder = "秦博厚",
                            HousingArea = 104.2f,
                            IsLowIncome = false,
                            IsPoor = false,
                            PeopleNumber = 5,
                            VillageGroupCode = "001",
                            VillageName = "张浦社区"
                        });
                });

            modelBuilder.Entity("AspNetCore.Entity.Member", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Birthday");

                    b.Property<string>("DepartmentCode")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Education")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<DateTime>("EntryTime");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(3);

                    b.Property<string>("HomeAddress")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("IdCardNumber")
                        .IsRequired()
                        .HasMaxLength(18);

                    b.Property<DateTime>("LeaveTime");

                    b.Property<string>("LengthOfService")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("MaritalStatus")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<string>("MemberCode")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("MemberName")
                        .IsRequired();

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<string>("PersonnelNature")
                        .HasMaxLength(10);

                    b.Property<string>("PoliticalStatus")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.HasKey("Id");

                    b.ToTable("Members");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d3e89186-e15b-4002-ad50-9e9a9415b059"),
                            Birthday = new DateTime(1974, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentCode = "002",
                            Education = "本科",
                            EntryTime = new DateTime(2007, 2, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = "男",
                            HomeAddress = "张浦镇江北新村14号",
                            IdCardNumber = "320583197407056857",
                            LeaveTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LengthOfService = "12年",
                            MaritalStatus = "已婚",
                            MemberCode = "002000",
                            MemberName = "陈乐成",
                            Nationality = "汉族",
                            PoliticalStatus = "中共党员",
                            Position = "主任",
                            Status = "在职"
                        },
                        new
                        {
                            Id = new Guid("c2501bae-955e-486f-8664-ecce26ef02f1"),
                            Birthday = new DateTime(1977, 7, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentCode = "002",
                            Education = "本科",
                            EntryTime = new DateTime(2002, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = "男",
                            HomeAddress = "张浦镇浦江北新村112号",
                            IdCardNumber = "320583197707087692",
                            LeaveTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LengthOfService = "17年",
                            MaritalStatus = "已婚",
                            MemberCode = "002001",
                            MemberName = "姜兴安",
                            Nationality = "汉族",
                            PoliticalStatus = "中共党员",
                            Position = "副主任",
                            Status = "在职"
                        },
                        new
                        {
                            Id = new Guid("e8daaa80-ce41-4b47-bc2b-1ec03ed0a61d"),
                            Birthday = new DateTime(1985, 4, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentCode = "002",
                            Education = "高中",
                            EntryTime = new DateTime(2010, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = "男",
                            HomeAddress = "张浦镇江北新村56号",
                            IdCardNumber = "320583198504178937",
                            LeaveTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LengthOfService = "9年",
                            MaritalStatus = "丧偶",
                            MemberCode = "002002",
                            MemberName = "于君昊",
                            Nationality = "汉族",
                            PoliticalStatus = "中共党员",
                            Position = "治调委员",
                            Status = "在职"
                        },
                        new
                        {
                            Id = new Guid("3f95601e-136f-44c3-9501-3a3615fd53bc"),
                            Birthday = new DateTime(1979, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentCode = "002",
                            Education = "硕士研究生",
                            EntryTime = new DateTime(2005, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = "男",
                            HomeAddress = "张浦镇江北新村12号",
                            IdCardNumber = "320583197910154878",
                            LeaveTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LengthOfService = "14年",
                            MaritalStatus = "离异",
                            MemberCode = "002003",
                            MemberName = "康志国",
                            Nationality = "汉族",
                            PoliticalStatus = "群众",
                            Position = "财经委员",
                            Status = "在职"
                        },
                        new
                        {
                            Id = new Guid("3709e6d1-5197-4bab-93b1-8fe46943ea7f"),
                            Birthday = new DateTime(1987, 4, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentCode = "002",
                            Education = "本科",
                            EntryTime = new DateTime(2007, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = "女",
                            HomeAddress = "张浦镇江北新村17号",
                            IdCardNumber = "320583198704187965",
                            LeaveTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LengthOfService = "12年",
                            MaritalStatus = "已婚",
                            MemberCode = "002004",
                            MemberName = "赵陈红",
                            Nationality = "汉族",
                            PoliticalStatus = "群众",
                            Position = "妇女计生委员",
                            Status = "在职"
                        });
                });

            modelBuilder.Entity("AspNetCore.Entity.Menu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("RoleName")
                        .IsRequired();

                    b.Property<string>("Url")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Menus");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b19e7135-0159-48b5-b819-2778d79b26d7"),
                            RoleName = "System",
                            Url = "/api/AdminDivisions"
                        },
                        new
                        {
                            Id = new Guid("bcb12e66-e11d-4286-8b80-7a9277bfaa8a"),
                            RoleName = "System",
                            Url = "api/DataCategroys"
                        },
                        new
                        {
                            Id = new Guid("ee792b44-e946-4932-87ac-139f8d9c9247"),
                            RoleName = "System",
                            Url = "api/DataItems"
                        },
                        new
                        {
                            Id = new Guid("096f8835-d97b-4b29-969c-7a9c8c7bc195"),
                            RoleName = "Admmin",
                            Url = "api/Villagers"
                        },
                        new
                        {
                            Id = new Guid("4d047b66-5b14-4601-b380-73fca385038e"),
                            RoleName = "Admin",
                            Url = "api/Villages"
                        },
                        new
                        {
                            Id = new Guid("60000ad2-9965-4b27-9ba6-021e5203b1a2"),
                            RoleName = "Admin",
                            Url = "api/VillagerGroups"
                        },
                        new
                        {
                            Id = new Guid("9f416dac-7f9d-49e4-9202-6244e15ccd08"),
                            RoleName = "Admin",
                            Url = "api/Towns"
                        },
                        new
                        {
                            Id = new Guid("fc3b43f3-e406-4884-a285-148d40afa600"),
                            RoleName = "Admin",
                            Url = "api/PartyMembers"
                        },
                        new
                        {
                            Id = new Guid("2821244a-79f1-4aa4-b6ba-0c3f98fa6f9d"),
                            RoleName = "Admin",
                            Url = "api/Departments"
                        },
                        new
                        {
                            Id = new Guid("96fd4faf-b5c7-4a6b-94a3-0de6b818624b"),
                            RoleName = "Admin",
                            Url = "api/Members"
                        },
                        new
                        {
                            Id = new Guid("562a8644-c9b4-4bc8-b021-d333f338ac0d"),
                            RoleName = "Admin",
                            Url = "api/Familys"
                        },
                        new
                        {
                            Id = new Guid("e1a8d588-2148-4061-8c5e-d72032025490"),
                            RoleName = "Admin",
                            Url = "api/NonOperatingAssetss"
                        },
                        new
                        {
                            Id = new Guid("f66e9920-fa6e-48f8-891e-5c9da596b5f5"),
                            RoleName = "System",
                            Url = "api/Users"
                        },
                        new
                        {
                            Id = new Guid("9e69438f-92e1-43a0-af0f-876e42369b74"),
                            RoleName = "System",
                            Url = "api/Roles"
                        },
                        new
                        {
                            Id = new Guid("ed892271-b030-4948-a1c9-7779c674c25f"),
                            RoleName = "System",
                            Url = "api/UserRoles"
                        },
                        new
                        {
                            Id = new Guid("fd1817d6-fd6a-46d7-9934-f9adbfebbc56"),
                            RoleName = "Admin",
                            Url = "api/Secret/deactivate"
                        },
                        new
                        {
                            Id = new Guid("29169d55-c429-4c2d-b1b3-bde01ec45044"),
                            RoleName = "Admin",
                            Url = "api/Secret/refresh"
                        });
                });

            modelBuilder.Entity("AspNetCore.Entity.NonOperatingAssets", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("LibaryCollectionsNumber");

                    b.Property<int>("LibraryNumber");

                    b.Property<float>("OfficeBuildingArea");

                    b.Property<int>("OfficeBuildingNumber");

                    b.Property<float>("SeniorCitizenCenterArea");

                    b.Property<int>("SeniorCitizenCenterNumber");

                    b.Property<int>("ServiceStationNumber");

                    b.Property<float>("SportActivityRoomArea");

                    b.Property<int>("SportsActivityRoomNumber");

                    b.Property<float>("StaffQuarterArea");

                    b.Property<int>("StaffQuartersNumber");

                    b.Property<string>("VillageName")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("NonOperatingAssets");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0da022c0-5d82-4eba-9a82-c06315afbc23"),
                            LibaryCollectionsNumber = 3000,
                            LibraryNumber = 1,
                            OfficeBuildingArea = 105f,
                            OfficeBuildingNumber = 1,
                            SeniorCitizenCenterArea = 450f,
                            SeniorCitizenCenterNumber = 1,
                            ServiceStationNumber = 4,
                            SportActivityRoomArea = 1000f,
                            SportsActivityRoomNumber = 2,
                            StaffQuarterArea = 1000f,
                            StaffQuartersNumber = 1,
                            VillageName = "张浦社区"
                        },
                        new
                        {
                            Id = new Guid("27f23db6-42e7-4f73-8db7-9d4a0c51175b"),
                            LibaryCollectionsNumber = 2500,
                            LibraryNumber = 1,
                            OfficeBuildingArea = 172f,
                            OfficeBuildingNumber = 1,
                            SeniorCitizenCenterArea = 380f,
                            SeniorCitizenCenterNumber = 1,
                            ServiceStationNumber = 2,
                            SportActivityRoomArea = 800f,
                            SportsActivityRoomNumber = 1,
                            StaffQuarterArea = 1200f,
                            StaffQuartersNumber = 1,
                            VillageName = "花园社区"
                        },
                        new
                        {
                            Id = new Guid("020014e9-c673-400b-8e2c-65a58899744e"),
                            LibaryCollectionsNumber = 5000,
                            LibraryNumber = 1,
                            OfficeBuildingArea = 250f,
                            OfficeBuildingNumber = 2,
                            SeniorCitizenCenterArea = 700f,
                            SeniorCitizenCenterNumber = 2,
                            ServiceStationNumber = 1,
                            SportActivityRoomArea = 1500f,
                            SportsActivityRoomNumber = 3,
                            StaffQuarterArea = 2000f,
                            StaffQuartersNumber = 2,
                            VillageName = "振苏社区"
                        });
                });

            modelBuilder.Entity("AspNetCore.Entity.PartyMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Birthday");

                    b.Property<string>("ContactPhone")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("DepartmentCode")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Education")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(3);

                    b.Property<bool>("IsFullMember");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<string>("PartyMemberCode")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("PartyMemberName")
                        .IsRequired();

                    b.Property<string>("PartyOrganizationName")
                        .IsRequired();

                    b.Property<string>("PartyPosition")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<string>("VillageName")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("PartyMembers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7331ec1c-1a09-4351-9887-4754eb2cf723"),
                            Birthday = new DateTime(1974, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ContactPhone = "13057134712",
                            DepartmentCode = "001",
                            Education = "本科",
                            Gender = "男",
                            IsFullMember = true,
                            Nationality = "汉族",
                            PartyMemberCode = "001000",
                            PartyMemberName = "陈乐成",
                            PartyOrganizationName = "张浦社区党支部委员会",
                            PartyPosition = "无",
                            VillageName = "张浦社区"
                        });
                });

            modelBuilder.Entity("AspNetCore.Entity.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("RoleName")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c3e5c776-a07a-460d-b8d9-4b8ce07ca1e0"),
                            RoleName = "Admin"
                        },
                        new
                        {
                            Id = new Guid("cacf2dd3-13c0-46e5-b83e-09b4c8755448"),
                            RoleName = "Client"
                        },
                        new
                        {
                            Id = new Guid("8145438f-2450-46b1-b267-4a90d6749b17"),
                            RoleName = "System"
                        });
                });

            modelBuilder.Entity("AspNetCore.Entity.Town", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("AreaNumber")
                        .IsRequired()
                        .HasMaxLength(15);

                    b.Property<string>("ChairmanName")
                        .IsRequired();

                    b.Property<string>("ContactPhone")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("GovernmentLevel");

                    b.Property<string>("MayorName")
                        .IsRequired();

                    b.Property<string>("SecretaryName")
                        .IsRequired();

                    b.Property<string>("TownName")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Towns");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e18db9cc-3a24-47c2-a7d4-db92bf007641"),
                            Address = "前进西路168号",
                            AreaNumber = "320583102000",
                            ChairmanName = "祖冲之",
                            ContactPhone = "0512-57621053",
                            GovernmentLevel = 4,
                            MayorName = "陆机",
                            SecretaryName = "陆云",
                            TownName = "周市镇"
                        },
                        new
                        {
                            Id = new Guid("9430b52b-a1d8-470b-bdfb-daeaa2da6f92"),
                            Address = "前进东路",
                            AreaNumber = "320583400000",
                            ChairmanName = "邢栋祥",
                            ContactPhone = "0512-57329416",
                            GovernmentLevel = 4,
                            MayorName = "逢建德",
                            SecretaryName = "匡俊智",
                            TownName = "开发区"
                        },
                        new
                        {
                            Id = new Guid("025a4a65-94b0-44ea-a815-db44f44a661d"),
                            Address = "花溪路358号",
                            AreaNumber = "320583104000",
                            ChairmanName = "武财章",
                            ContactPhone = "0512-57698733",
                            GovernmentLevel = 4,
                            MayorName = "王班",
                            SecretaryName = "吴启河",
                            TownName = "花桥镇"
                        },
                        new
                        {
                            Id = new Guid("b4b270ef-abd4-4aa1-9c36-ce50d84e97b7"),
                            Address = "华杨路188号",
                            AreaNumber = "320583106000",
                            ChairmanName = "成梦昆",
                            ContactPhone = "0512-57452503",
                            GovernmentLevel = 4,
                            MayorName = "刘赫伯",
                            SecretaryName = "蒋信迟",
                            TownName = "张浦镇"
                        },
                        new
                        {
                            Id = new Guid("6fcbb54c-9ace-42e8-ba21-40497dbbb5e0"),
                            Address = "菉溪路22号",
                            AreaNumber = "	320583103000",
                            ChairmanName = "李迪尉",
                            ContactPhone = "0512-57671003",
                            GovernmentLevel = 4,
                            MayorName = "梁灶慈",
                            SecretaryName = "刘群胜",
                            TownName = "陆家镇"
                        },
                        new
                        {
                            Id = new Guid("7e732436-1008-4837-b1e3-8dc9de392ae8"),
                            Address = "新澄路918号",
                            AreaNumber = "320583101000",
                            ChairmanName = "周伟",
                            ContactPhone = "0521-57656330",
                            GovernmentLevel = 4,
                            MayorName = "李迪尉",
                            SecretaryName = "钟开桦",
                            TownName = "巴城镇"
                        },
                        new
                        {
                            Id = new Guid("58c6e502-5faa-4812-84ec-8be05a06bde4"),
                            Address = "炎东路",
                            AreaNumber = "320583108000",
                            ChairmanName = "林修胜",
                            ContactPhone = "0512-36620396",
                            GovernmentLevel = 4,
                            MayorName = "张弥成",
                            SecretaryName = "时可北",
                            TownName = "千灯镇"
                        },
                        new
                        {
                            Id = new Guid("9f268ba1-77cd-4f68-83bb-903050abc0f5"),
                            Address = "府前路78号",
                            AreaNumber = "320583105000",
                            ChairmanName = "常般业",
                            ContactPhone = "0512-57488358",
                            GovernmentLevel = 4,
                            MayorName = "冯便磊",
                            SecretaryName = "颜尚冲",
                            TownName = "淀山湖镇"
                        },
                        new
                        {
                            Id = new Guid("d93b6e2f-fd8c-4a0b-808c-c2710109ffbb"),
                            Address = "淀南路100号",
                            AreaNumber = "320583107000",
                            ChairmanName = "陆先",
                            ContactPhone = "0521-57211236",
                            GovernmentLevel = 4,
                            MayorName = "王翱桦",
                            SecretaryName = "江衷力",
                            TownName = "周庄镇"
                        },
                        new
                        {
                            Id = new Guid("18846306-d1e8-4339-8e46-9f60ca9b437c"),
                            Address = "普庆路1号",
                            AreaNumber = "320583109000",
                            ChairmanName = "邹鉴夕",
                            ContactPhone = "0521-57231290",
                            GovernmentLevel = 4,
                            MayorName = "倪御奋",
                            SecretaryName = "姬道生",
                            TownName = "锦溪镇"
                        });
                });

            modelBuilder.Entity("AspNetCore.Entity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(150);

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0c68b05a-721e-41b5-b3ad-a2a368b0a096"),
                            Password = "fu1Enyt+Hrdo9BNpDnSy5qb0tM7noN4WtRZwYUtkfpc=",
                            UserName = "admin"
                        },
                        new
                        {
                            Id = new Guid("4845b35c-4352-474b-8b68-4e83edcb3178"),
                            Password = "/uQH4FsnsFGBmvRluYOYHKDjUWimJiwnOV9WCRuEHQE=",
                            UserName = "user1"
                        },
                        new
                        {
                            Id = new Guid("4001c6a6-5fef-43c2-8197-d87be07d3532"),
                            Password = "vuQZWjwJouGCACBNyNwxQoSZc+8sK51nsCv34XSgelE=",
                            UserName = "user2"
                        },
                        new
                        {
                            Id = new Guid("e149f75a-9f70-4382-acf6-f702c80ce372"),
                            Password = "h3fPS6qc1oAs9EImA3iGSZ9fH6Zl1yZJtFa6T3tiQko=",
                            UserName = "user3"
                        });
                });

            modelBuilder.Entity("AspNetCore.Entity.UserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("RoleId");

                    b.Property<Guid>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("80f16ad9-8693-43e0-987e-9437a4651f9b"),
                            RoleId = new Guid("c3e5c776-a07a-460d-b8d9-4b8ce07ca1e0"),
                            UserId = new Guid("0c68b05a-721e-41b5-b3ad-a2a368b0a096")
                        },
                        new
                        {
                            Id = new Guid("40098dd1-c5d8-4c7d-8646-23cf0a66ef85"),
                            RoleId = new Guid("cacf2dd3-13c0-46e5-b83e-09b4c8755448"),
                            UserId = new Guid("4845b35c-4352-474b-8b68-4e83edcb3178")
                        },
                        new
                        {
                            Id = new Guid("91f1a59d-0201-4f7f-a505-b63af8d02b8b"),
                            RoleId = new Guid("cacf2dd3-13c0-46e5-b83e-09b4c8755448"),
                            UserId = new Guid("4001c6a6-5fef-43c2-8197-d87be07d3532")
                        },
                        new
                        {
                            Id = new Guid("ed14ae9b-2a6d-4ece-b4b6-4244f096e05a"),
                            RoleId = new Guid("c3e5c776-a07a-460d-b8d9-4b8ce07ca1e0"),
                            UserId = new Guid("e149f75a-9f70-4382-acf6-f702c80ce372")
                        },
                        new
                        {
                            Id = new Guid("862ccfb9-1fdb-4df0-8fd1-a5205bcf5f8c"),
                            RoleId = new Guid("8145438f-2450-46b1-b267-4a90d6749b17"),
                            UserId = new Guid("0c68b05a-721e-41b5-b3ad-a2a368b0a096")
                        });
                });

            modelBuilder.Entity("AspNetCore.Entity.Village", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("AreaNumber")
                        .IsRequired()
                        .HasMaxLength(15);

                    b.Property<string>("ContactPhone")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("GovernmentLevel");

                    b.Property<int?>("GroupCount");

                    b.Property<string>("HighLevelAreaNumber")
                        .IsRequired()
                        .HasMaxLength(15);

                    b.Property<string>("SecretaryName")
                        .IsRequired();

                    b.Property<int>("UrbanRuralClassification");

                    b.Property<string>("VillageHeadName")
                        .IsRequired();

                    b.Property<string>("VillageName")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Villages");

                    b.HasData(
                        new
                        {
                            Id = new Guid("636ceec6-d4f7-4c07-a449-1874811bfcec"),
                            Address = "京东路469号",
                            AreaNumber = "320583106001",
                            ContactPhone = "0512-57441175",
                            GovernmentLevel = 5,
                            GroupCount = 12,
                            HighLevelAreaNumber = "320583106000",
                            SecretaryName = "尹乐和",
                            UrbanRuralClassification = 111,
                            VillageHeadName = "赵乐欣",
                            VillageName = "张浦社区"
                        },
                        new
                        {
                            Id = new Guid("276384dc-8d4a-41c9-b739-e7d5bfe963bd"),
                            Address = "花苑路与京东路交叉口西侧",
                            AreaNumber = "320583106002",
                            ContactPhone = "0512-36863123",
                            GovernmentLevel = 5,
                            GroupCount = 26,
                            HighLevelAreaNumber = "320583106000",
                            SecretaryName = "汤振海",
                            UrbanRuralClassification = 111,
                            VillageHeadName = "杜向阳",
                            VillageName = "花园社区"
                        },
                        new
                        {
                            Id = new Guid("730ec507-004c-4301-b008-cbf3e03555f5"),
                            Address = "振苏六村",
                            AreaNumber = "320583106003",
                            ContactPhone = "0512-55270465",
                            GovernmentLevel = 5,
                            HighLevelAreaNumber = "320583106000",
                            SecretaryName = "廖景天",
                            UrbanRuralClassification = 111,
                            VillageHeadName = "崔泰宁",
                            VillageName = "振苏社区"
                        },
                        new
                        {
                            Id = new Guid("8d8bdec4-49fd-47ad-b051-44e586254eec"),
                            Address = "震阳路126号",
                            AreaNumber = "320583106004",
                            ContactPhone = "0512-57428835",
                            GovernmentLevel = 5,
                            HighLevelAreaNumber = "320583106000",
                            SecretaryName = "阎乐池",
                            UrbanRuralClassification = 121,
                            VillageHeadName = "尹和蔼",
                            VillageName = "南港社区"
                        },
                        new
                        {
                            Id = new Guid("7d68304f-36ec-4fab-9235-3f3cdccac2f8"),
                            Address = "淞沪西路36号",
                            AreaNumber = "320583106005",
                            ContactPhone = "0512-57256550",
                            GovernmentLevel = 5,
                            HighLevelAreaNumber = "320583106000",
                            SecretaryName = "许宏畅",
                            UrbanRuralClassification = 220,
                            VillageHeadName = "薛兴为",
                            VillageName = "大市社区"
                        },
                        new
                        {
                            Id = new Guid("8e88d4c2-8b91-41fe-8493-3352a60eb8d5"),
                            Address = "俱巷路894号",
                            AreaNumber = "320583106006",
                            ContactPhone = "0512-36691258",
                            GovernmentLevel = 5,
                            HighLevelAreaNumber = "320583106000",
                            SecretaryName = "孔浩思",
                            UrbanRuralClassification = 111,
                            VillageHeadName = "王康胜",
                            VillageName = "新巷社区"
                        },
                        new
                        {
                            Id = new Guid("279ce130-8730-4ca3-ae99-c0ef0e11b6ae"),
                            Address = "商秧路178号",
                            AreaNumber = "320583106007",
                            ContactPhone = "0512-55272500",
                            GovernmentLevel = 5,
                            GroupCount = 26,
                            HighLevelAreaNumber = "320583106000",
                            SecretaryName = "吴俊晤",
                            UrbanRuralClassification = 111,
                            VillageHeadName = "石欣德",
                            VillageName = "新吴社区"
                        },
                        new
                        {
                            Id = new Guid("774a35f9-82dc-496d-90bd-16bbfb7f8adf"),
                            Address = "大直路504号",
                            AreaNumber = "320583106008",
                            ContactPhone = "0512-55272500",
                            GovernmentLevel = 5,
                            GroupCount = 23,
                            HighLevelAreaNumber = "320583106000",
                            SecretaryName = "梁奇希",
                            UrbanRuralClassification = 112,
                            VillageHeadName = "吕勇男",
                            VillageName = "大直社区"
                        },
                        new
                        {
                            Id = new Guid("56a0e4d3-e09e-48d5-8515-b53d8456c47e"),
                            Address = "周巷路",
                            AreaNumber = "320583106009",
                            ContactPhone = "0512-57294577",
                            GovernmentLevel = 5,
                            GroupCount = 40,
                            HighLevelAreaNumber = "320583106000",
                            SecretaryName = "姜永昌",
                            UrbanRuralClassification = 111,
                            VillageHeadName = "吴凯凯",
                            VillageName = "周巷社区"
                        },
                        new
                        {
                            Id = new Guid("2b234b89-1bdc-4a07-98c2-e2199d59565d"),
                            Address = "京东路588号",
                            AreaNumber = "320583106012",
                            ContactPhone = "0512-57883298",
                            GovernmentLevel = 5,
                            HighLevelAreaNumber = "320583106000",
                            SecretaryName = "龙澔",
                            UrbanRuralClassification = 111,
                            VillageHeadName = "汤烨磊",
                            VillageName = "亲和社区"
                        },
                        new
                        {
                            Id = new Guid("5df9b778-ffbd-479a-94b8-305554058ebb"),
                            Address = "京东路731号",
                            AreaNumber = "320583106013",
                            ContactPhone = "0512-57278938",
                            GovernmentLevel = 5,
                            HighLevelAreaNumber = "320583106000",
                            SecretaryName = "李段",
                            UrbanRuralClassification = 111,
                            VillageHeadName = "吕尊",
                            VillageName = "锦和社区"
                        },
                        new
                        {
                            Id = new Guid("732e4dd8-9844-4457-8d88-a93575ea4e8f"),
                            Address = "金华路1号",
                            AreaNumber = "320583106200",
                            ContactPhone = "0512-57293702",
                            GovernmentLevel = 5,
                            GroupCount = 26,
                            HighLevelAreaNumber = "320583106000",
                            SecretaryName = "宋翰学",
                            UrbanRuralClassification = 112,
                            VillageHeadName = "龙昊焱",
                            VillageName = "金华村"
                        },
                        new
                        {
                            Id = new Guid("da39b83a-d315-41db-ab19-013971d38e40"),
                            Address = "商鞅路1号",
                            AreaNumber = "320583106204",
                            ContactPhone = "0512-50310612",
                            GovernmentLevel = 5,
                            GroupCount = 20,
                            HighLevelAreaNumber = "320583106000",
                            SecretaryName = "汤明亮",
                            UrbanRuralClassification = 112,
                            VillageHeadName = "吴咏德",
                            VillageName = "七桥村"
                        },
                        new
                        {
                            Id = new Guid("a42c151e-e918-40b4-ab7b-8bc8fa1741ec"),
                            Address = "机场路与兴陵路交叉口往南200米",
                            AreaNumber = "320583106205",
                            ContactPhone = "0512-57441476",
                            GovernmentLevel = 5,
                            GroupCount = 27,
                            HighLevelAreaNumber = "320583106000",
                            SecretaryName = "邹俊雄",
                            UrbanRuralClassification = 220,
                            VillageHeadName = "程飞虎",
                            VillageName = "赵陵村"
                        },
                        new
                        {
                            Id = new Guid("aa0b39ad-51bc-4fd4-b69a-8985f4e28956"),
                            Address = "川浩路22号",
                            AreaNumber = "320583106206",
                            ContactPhone = "0512-57441101",
                            GovernmentLevel = 5,
                            HighLevelAreaNumber = "320583106000",
                            SecretaryName = "丁弘亮",
                            UrbanRuralClassification = 220,
                            VillageHeadName = "龚炎彬",
                            VillageName = "吴加村"
                        },
                        new
                        {
                            Id = new Guid("b4e69f3e-51bc-488f-aeb9-4d66f61a7c64"),
                            Address = "港浦东路8号",
                            AreaNumber = "320583106207",
                            ContactPhone = "0512-5736863220",
                            GovernmentLevel = 5,
                            GroupCount = 33,
                            HighLevelAreaNumber = "320583106000",
                            SecretaryName = "史光临",
                            UrbanRuralClassification = 111,
                            VillageHeadName = "陈浦和",
                            VillageName = "三家村"
                        },
                        new
                        {
                            Id = new Guid("1089efa7-6bee-4df9-a097-6d563ee35237"),
                            Address = "盛巷花园门卫北侧",
                            AreaNumber = "320583106209",
                            ContactPhone = "0512-57441616",
                            GovernmentLevel = 5,
                            GroupCount = 20,
                            HighLevelAreaNumber = "320583106000",
                            SecretaryName = "韩华藏",
                            UrbanRuralClassification = 111,
                            VillageHeadName = "萧泰河",
                            VillageName = "新塘村"
                        },
                        new
                        {
                            Id = new Guid("378b69e4-6736-4493-9f92-5455f333e140"),
                            Address = "震阳路与双娄路交叉口",
                            AreaNumber = "320583106210",
                            ContactPhone = "0512-57421150",
                            GovernmentLevel = 5,
                            GroupCount = 35,
                            HighLevelAreaNumber = "320583106000",
                            SecretaryName = "贺博艺",
                            UrbanRuralClassification = 122,
                            VillageHeadName = "冯鹏赋",
                            VillageName = "星金村"
                        },
                        new
                        {
                            Id = new Guid("9da2a2a6-676a-463c-939e-a83038f3159a"),
                            Address = "陈邱家浜58号",
                            AreaNumber = "320583106211",
                            ContactPhone = "0512-50331469",
                            GovernmentLevel = 5,
                            GroupCount = 44,
                            HighLevelAreaNumber = "320583106000",
                            SecretaryName = "孙明杰",
                            UrbanRuralClassification = 220,
                            VillageHeadName = "谭睿诚",
                            VillageName = "新龙村"
                        },
                        new
                        {
                            Id = new Guid("c27b4bba-0ea8-4836-9bc0-18916806f5e4"),
                            Address = "建林路往北到底向西100米",
                            AreaNumber = "320583106212",
                            ContactPhone = "0512-57120550",
                            GovernmentLevel = 5,
                            HighLevelAreaNumber = "320583106000",
                            SecretaryName = "万安怡",
                            UrbanRuralClassification = 220,
                            VillageHeadName = "萧波峻",
                            VillageName = "白米村"
                        },
                        new
                        {
                            Id = new Guid("73fc1ab5-db9f-4528-bec9-d85e5e03517d"),
                            Address = "南港文体站",
                            AreaNumber = "320583106214",
                            ContactPhone = "0512-57428327",
                            GovernmentLevel = 5,
                            GroupCount = 28,
                            HighLevelAreaNumber = "320583106000",
                            SecretaryName = "蒋英卓",
                            UrbanRuralClassification = 220,
                            VillageHeadName = "冯兴庆",
                            VillageName = "林庄村"
                        },
                        new
                        {
                            Id = new Guid("999e37df-dcfd-4492-a357-eddc89512069"),
                            Address = "安头村公交站台往南60米处",
                            AreaNumber = "320583106215",
                            ContactPhone = "0512-57428927",
                            GovernmentLevel = 5,
                            GroupCount = 25,
                            HighLevelAreaNumber = "320583106000",
                            SecretaryName = "郝嘉慕",
                            UrbanRuralClassification = 220,
                            VillageHeadName = "史意蕴",
                            VillageName = "安头村"
                        },
                        new
                        {
                            Id = new Guid("9c730570-5173-4281-9709-4da5144b923c"),
                            Address = "江浦南路与C325交叉处",
                            AreaNumber = "320583106219",
                            ContactPhone = "0512-57272133",
                            GovernmentLevel = 5,
                            GroupCount = 23,
                            HighLevelAreaNumber = "320583106000",
                            SecretaryName = "漕文彦",
                            UrbanRuralClassification = 220,
                            VillageHeadName = "许高岑",
                            VillageName = "姜杭村"
                        },
                        new
                        {
                            Id = new Guid("d585f37e-1af2-4ad9-bc7b-df0598c9783e"),
                            Address = "长江南路东侧与锦溪北交界",
                            AreaNumber = "320583106220",
                            ContactPhone = "0512-57256590",
                            GovernmentLevel = 5,
                            GroupCount = 21,
                            HighLevelAreaNumber = "320583106000",
                            SecretaryName = "汤英耀",
                            UrbanRuralClassification = 220,
                            VillageHeadName = "蒋嘉许",
                            VillageName = "尚明甸村"
                        },
                        new
                        {
                            Id = new Guid("7adaff0e-a4cf-47fc-bb02-ba5e32e67bad"),
                            Address = "姚家港北首",
                            AreaNumber = "320583106221",
                            ContactPhone = "0512-57117756",
                            GovernmentLevel = 5,
                            GroupCount = 22,
                            HighLevelAreaNumber = "320583106000",
                            SecretaryName = "杨成仁",
                            UrbanRuralClassification = 220,
                            VillageHeadName = "谢高义",
                            VillageName = "南姚村"
                        },
                        new
                        {
                            Id = new Guid("dec0db8b-10c8-4996-b16d-a7dae381580a"),
                            Address = "淞沪西路与江浦南路交叉口",
                            AreaNumber = "320583106226",
                            ContactPhone = "0512-57255236",
                            GovernmentLevel = 5,
                            GroupCount = 49,
                            HighLevelAreaNumber = "320583106000",
                            SecretaryName = "顾绍祺",
                            UrbanRuralClassification = 220,
                            VillageHeadName = "金和怡",
                            VillageName = "大市村"
                        },
                        new
                        {
                            Id = new Guid("a287ad1f-b1ed-4f01-9dc1-ad7d64b32646"),
                            Address = "淞沪东路12号",
                            AreaNumber = "320583106227",
                            ContactPhone = "0512-57251131",
                            GovernmentLevel = 5,
                            HighLevelAreaNumber = "320583106000",
                            SecretaryName = "朱嘉石",
                            UrbanRuralClassification = 220,
                            VillageHeadName = "顾飞羽",
                            VillageName = "南吉山村"
                        });
                });

            modelBuilder.Entity("AspNetCore.Entity.VillagerGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("MemberNumber");

                    b.Property<string>("PrincipalAddress")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("PrincipalEmail")
                        .IsRequired();

                    b.Property<string>("PrincipalName")
                        .IsRequired();

                    b.Property<string>("PrincipalPhone")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("VillageGroupCode")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("VillageName")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("VillagerGroups");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7b2deac3-7f41-4777-b238-bd9dc5c6c262"),
                            MemberNumber = 356,
                            PrincipalAddress = "张浦镇望江新村6幢206室",
                            PrincipalEmail = "wuxuefei@kszpwz.gov.cn",
                            PrincipalName = "吴雪峰",
                            PrincipalPhone = "0512-57841234",
                            VillageGroupCode = "001",
                            VillageName = "南港社区"
                        },
                        new
                        {
                            Id = new Guid("6bc939cc-8581-48ef-be9a-81a4a7052dfd"),
                            MemberNumber = 412,
                            PrincipalAddress = "张浦镇富都新村3幢204室",
                            PrincipalEmail = "fangjitong@kszpfd.gov.cn",
                            PrincipalName = "方季同",
                            PrincipalPhone = "0512-42345124",
                            VillageGroupCode = "002",
                            VillageName = "南港社区"
                        },
                        new
                        {
                            Id = new Guid("f74ae82f-7313-4b32-891f-612bdff5973f"),
                            MemberNumber = 532,
                            PrincipalAddress = "张浦镇茶风新村1幢206室",
                            PrincipalEmail = "caogao@kszpcf.gov.cn",
                            PrincipalName = "蔡高",
                            PrincipalPhone = "0512-42345244",
                            VillageGroupCode = "003",
                            VillageName = "花园社区"
                        },
                        new
                        {
                            Id = new Guid("d65d6c37-69e7-4ae1-8fb3-5229ab81a9b4"),
                            MemberNumber = 253,
                            PrincipalAddress = "张浦镇富仁小区5幢102室",
                            PrincipalEmail = "changgaohan@kszpfr.gov.cn",
                            PrincipalName = "常高翰",
                            PrincipalPhone = "0512-421235124",
                            VillageGroupCode = "004",
                            VillageName = "大市社区"
                        },
                        new
                        {
                            Id = new Guid("aa16f912-382e-47ad-a679-01c1600570bb"),
                            MemberNumber = 512,
                            PrincipalAddress = "张浦镇风和日丽5幢1102室",
                            PrincipalEmail = "qianyancheng@kszpfhrl.gov.cn",
                            PrincipalName = "钱阳成",
                            PrincipalPhone = "0512-52341124",
                            VillageGroupCode = "005",
                            VillageName = "南港社区"
                        },
                        new
                        {
                            Id = new Guid("2133276e-3563-4417-a49b-1f1f6011f620"),
                            MemberNumber = 567,
                            PrincipalAddress = "张浦镇枫情佳苑3幢306室",
                            PrincipalEmail = "kongzhiwen@kszpfqjy.gov.cn",
                            PrincipalName = "孔志文",
                            PrincipalPhone = "0512-42323124",
                            VillageGroupCode = "006",
                            VillageName = "新吴社区"
                        },
                        new
                        {
                            Id = new Guid("3231ddb4-8bec-4634-b97f-98adc57ed0b1"),
                            MemberNumber = 476,
                            PrincipalAddress = "张浦镇张浦村14号",
                            PrincipalEmail = "huhaorang@kszpzp.gov.cn",
                            PrincipalName = "胡浩壤",
                            PrincipalPhone = "0512-42341124",
                            VillageGroupCode = "007",
                            VillageName = "张浦社区"
                        },
                        new
                        {
                            Id = new Guid("7a178472-9d81-4fd9-be9f-01771b219348"),
                            MemberNumber = 345,
                            PrincipalAddress = "张浦镇张浦村142号",
                            PrincipalEmail = "xuexiuxian@kszpzp.gov.cn",
                            PrincipalName = "薛修贤",
                            PrincipalPhone = "0512-423125124",
                            VillageGroupCode = "008",
                            VillageName = "张浦社区"
                        },
                        new
                        {
                            Id = new Guid("407d4ff0-1626-4985-9b43-5bbc9a14190d"),
                            MemberNumber = 452,
                            PrincipalAddress = "张浦镇银鹿新城3幢802室",
                            PrincipalEmail = "heliren@kszpylxc.gov.cn",
                            PrincipalName = "何立人",
                            PrincipalPhone = "0512-523125124",
                            VillageGroupCode = "009",
                            VillageName = "张浦社区"
                        },
                        new
                        {
                            Id = new Guid("418bc78c-dda4-4a4c-9239-f40a70dd3493"),
                            MemberNumber = 662,
                            PrincipalAddress = "张浦镇牡丹苑7幢502",
                            PrincipalEmail = "zhongjunde@kszpmdy.gov.cn",
                            PrincipalName = "钟俊德",
                            PrincipalPhone = "0512-12345124",
                            VillageGroupCode = "010",
                            VillageName = "周巷社区"
                        },
                        new
                        {
                            Id = new Guid("08de69db-9eef-42c9-accd-495302100e9e"),
                            MemberNumber = 341,
                            PrincipalAddress = "张浦镇江南春堤14号",
                            PrincipalEmail = "jiatianzong@kszpjnkd.gov.cn",
                            PrincipalName = "贾天纵",
                            PrincipalPhone = "0512-43423124",
                            VillageGroupCode = "011",
                            VillageName = "新巷社区"
                        },
                        new
                        {
                            Id = new Guid("cec69a02-bf29-4a85-9000-9a7de9907990"),
                            MemberNumber = 543,
                            PrincipalAddress = "张浦镇安居小区24号",
                            PrincipalEmail = "duanxuehai@kszpanxq.gov.cn",
                            PrincipalName = "段学海",
                            PrincipalPhone = "0512-12455124",
                            VillageGroupCode = "012",
                            VillageName = "大市社区"
                        });
                });

            modelBuilder.Entity("AspNetCore.Entity.UserRole", b =>
                {
                    b.HasOne("AspNetCore.Entity.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AspNetCore.Entity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
