// <auto-generated />
using System;
using AspNetCore.Entity.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace AspNetCore.Entity.Migrations
{
    [DbContext(typeof(MsContext))]
    [Migration("20190413060217_Migration07")]
    partial class Migration07
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:PostgresExtension:uuid-ossp", ",,")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("AspNetCore.Entity.Core.Villager", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AnnualIncome");

                    b.Property<DateTime>("Birthday");

                    b.Property<string>("Education");

                    b.Property<string>("Gender")
                        .IsRequired();

                    b.Property<bool>("HavingCriminalRecord");

                    b.Property<bool>("HavingIllegalRecord");

                    b.Property<string>("HomeAddress")
                        .IsRequired();

                    b.Property<string>("MaritalStatus");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Villagers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7373f677-89db-44cf-8339-893412f86e0f"),
                            AnnualIncome = 20000,
                            Birthday = new DateTime(1984, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Education = "高中",
                            Gender = "男",
                            HavingCriminalRecord = false,
                            HavingIllegalRecord = false,
                            HomeAddress = "向阳村3组14号",
                            MaritalStatus = "已婚",
                            Name = "张东"
                        },
                        new
                        {
                            Id = new Guid("be4bf72f-bbcf-445a-9f5e-3076195f98cc"),
                            AnnualIncome = 17000,
                            Birthday = new DateTime(1972, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Education = "初中",
                            Gender = "男",
                            HavingCriminalRecord = false,
                            HavingIllegalRecord = false,
                            HomeAddress = "向阳村5组17号",
                            MaritalStatus = "已婚",
                            Name = "刘项"
                        },
                        new
                        {
                            Id = new Guid("6f95e111-da15-49b5-906d-8431705a9dd8"),
                            AnnualIncome = 50000,
                            Birthday = new DateTime(1990, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Education = "本科",
                            Gender = "男",
                            HavingCriminalRecord = false,
                            HavingIllegalRecord = false,
                            HomeAddress = "向阳村1组2号",
                            MaritalStatus = "未婚",
                            Name = "马伦"
                        });
                });

            modelBuilder.Entity("AspNetCore.Entity.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<string>("ContactPhone");

                    b.Property<string>("DepartmentCode");

                    b.Property<string>("DepartmentName");

                    b.Property<string>("Email");

                    b.Property<string>("Fax");

                    b.Property<string>("Notes");

                    b.Property<string>("PrincipalName");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("916d1e13-a624-4c69-b1b5-f4c69bef7dd9"),
                            Address = "京东路469号",
                            ContactPhone = "0512-57623451",
                            DepartmentCode = "001",
                            DepartmentName = "张浦社区党支部委员会",
                            Email = "zhenxinguo@kszpzp.gov.cn",
                            Fax = "0512-54123412",
                            Notes = "",
                            PrincipalName = "郑兴国"
                        },
                        new
                        {
                            Id = new Guid("a28852f3-990b-4002-a3e2-3c976973fa2b"),
                            Address = "京东路469号",
                            ContactPhone = "0512-58289432",
                            DepartmentCode = "002",
                            DepartmentName = "张浦社区居民委员会",
                            Email = "chenlecheng@kszpzp.gov.cn",
                            Fax = "0512-59283414",
                            Notes = "临时兼任",
                            PrincipalName = "陈乐成"
                        },
                        new
                        {
                            Id = new Guid("00a97e6f-d988-4551-88a7-15288df6b8ea"),
                            Address = "花苑路与京东路交叉口西侧",
                            ContactPhone = "0512-54128123",
                            DepartmentCode = "003",
                            DepartmentName = "花园社区党支部委员会",
                            Email = "xugaoyi@kszpzp.gov.cn",
                            Fax = "0512-564178314",
                            PrincipalName = "许高义"
                        });
                });

            modelBuilder.Entity("AspNetCore.Entity.Family", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AccountCharacter");

                    b.Property<int>("AverageAnnualIncome");

                    b.Property<float>("AverageHousingArea");

                    b.Property<string>("FamilyCode");

                    b.Property<string>("Householder");

                    b.Property<float>("HousingArea");

                    b.Property<bool>("IsLowIncome");

                    b.Property<bool>("IsPoor");

                    b.Property<int>("PeopleNumber");

                    b.Property<string>("VillageGroupCode");

                    b.Property<string>("VillageName");

                    b.HasKey("Id");

                    b.ToTable("Families");

                    b.HasData(
                        new
                        {
                            Id = new Guid("799a6d80-9506-4ffa-b5df-4347b1d2d599"),
                            AccountCharacter = "非农业",
                            AverageAnnualIncome = 5000,
                            AverageHousingArea = 20.84f,
                            FamilyCode = "001000",
                            Householder = "秦博厚",
                            HousingArea = 104.2f,
                            IsLowIncome = false,
                            IsPoor = false,
                            PeopleNumber = 5,
                            VillageGroupCode = "001"
                        });
                });

            modelBuilder.Entity("AspNetCore.Entity.Member", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Birthday");

                    b.Property<string>("DepartmentCode");

                    b.Property<string>("Education");

                    b.Property<DateTime>("EntryTime");

                    b.Property<string>("Gender");

                    b.Property<string>("HomeAddress");

                    b.Property<string>("IdCardNumber");

                    b.Property<DateTime>("LeaveTime");

                    b.Property<string>("LengthOfService");

                    b.Property<string>("MaritalStatus");

                    b.Property<string>("MemberCode");

                    b.Property<string>("MemberName");

                    b.Property<string>("Nationality");

                    b.Property<string>("PersonnelNature");

                    b.Property<string>("PoliticalStatus");

                    b.Property<string>("Position");

                    b.Property<string>("Status");

                    b.HasKey("Id");

                    b.ToTable("Members");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7ccf6962-8734-4c39-bd7e-05c650752d32"),
                            Birthday = new DateTime(1974, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentCode = "002",
                            Education = "本科",
                            EntryTime = new DateTime(2007, 2, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = "男",
                            HomeAddress = "张浦镇江北新村14号",
                            IdCardNumber = "320583197407056857",
                            LeaveTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LengthOfService = "12年",
                            MaritalStatus = "已婚",
                            MemberCode = "002000",
                            MemberName = "陈乐成",
                            Nationality = "汉族",
                            PoliticalStatus = "中共党员",
                            Position = "主任",
                            Status = "在职"
                        },
                        new
                        {
                            Id = new Guid("51861814-a3e9-4fef-a10e-85085b3e1a2d"),
                            Birthday = new DateTime(1977, 7, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentCode = "002",
                            Education = "本科",
                            EntryTime = new DateTime(2002, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = "男",
                            HomeAddress = "张浦镇浦江北新村112号",
                            IdCardNumber = "320583197707087692",
                            LeaveTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LengthOfService = "17年",
                            MaritalStatus = "已婚",
                            MemberCode = "002001",
                            MemberName = "姜兴安",
                            Nationality = "汉族",
                            PoliticalStatus = "中共党员",
                            Position = "副主任",
                            Status = "在职"
                        },
                        new
                        {
                            Id = new Guid("8d7a0084-9ee9-4de6-bcf8-22ecef68ef84"),
                            Birthday = new DateTime(1985, 4, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentCode = "002",
                            Education = "高中",
                            EntryTime = new DateTime(2010, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = "男",
                            HomeAddress = "张浦镇江北新村56号",
                            IdCardNumber = "320583198504178937",
                            LeaveTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LengthOfService = "9年",
                            MaritalStatus = "丧偶",
                            MemberCode = "002002",
                            MemberName = "于君昊",
                            Nationality = "汉族",
                            PoliticalStatus = "中共党员",
                            Position = "治调委员",
                            Status = "在职"
                        },
                        new
                        {
                            Id = new Guid("03a5b722-7e14-41a0-9cac-7b22fb5f4f09"),
                            Birthday = new DateTime(1979, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentCode = "002",
                            Education = "硕士研究生",
                            EntryTime = new DateTime(2005, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = "男",
                            HomeAddress = "张浦镇江北新村12号",
                            IdCardNumber = "320583197910154878",
                            LeaveTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LengthOfService = "14年",
                            MaritalStatus = "离异",
                            MemberCode = "002003",
                            MemberName = "康志国",
                            Nationality = "汉族",
                            PoliticalStatus = "群众",
                            Position = "财经委员",
                            Status = "在职"
                        },
                        new
                        {
                            Id = new Guid("daf4d636-c213-495f-8035-72255bd3fcac"),
                            Birthday = new DateTime(1987, 4, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentCode = "002",
                            Education = "本科",
                            EntryTime = new DateTime(2007, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = "女",
                            HomeAddress = "张浦镇江北新村17号",
                            IdCardNumber = "320583198704187965",
                            LeaveTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LengthOfService = "12年",
                            MaritalStatus = "已婚",
                            MemberCode = "002004",
                            MemberName = "赵陈红",
                            Nationality = "汉族",
                            PoliticalStatus = "群众",
                            Position = "妇女计生委员",
                            Status = "在职"
                        });
                });

            modelBuilder.Entity("AspNetCore.Entity.NonOperatingAssets", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("LibaryCollectionsNumber");

                    b.Property<int>("LibraryNumber");

                    b.Property<float>("OfficeBuildingArea");

                    b.Property<int>("OfficeBuildingNumber");

                    b.Property<float>("SeniorCitizenCenterArea");

                    b.Property<int>("SeniorCitizenCenterNumber");

                    b.Property<int>("ServiceStationNumber");

                    b.Property<float>("SportActivityRoomArea");

                    b.Property<int>("SportsActivityRoomNumber");

                    b.Property<float>("StaffQuarterArea");

                    b.Property<int>("StaffQuartersNumber");

                    b.Property<string>("VillageName");

                    b.HasKey("Id");

                    b.ToTable("NonOperatingAssets");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8ea96382-47eb-463f-990c-420526ff0c24"),
                            LibaryCollectionsNumber = 3000,
                            LibraryNumber = 1,
                            OfficeBuildingArea = 105f,
                            OfficeBuildingNumber = 1,
                            SeniorCitizenCenterArea = 450f,
                            SeniorCitizenCenterNumber = 1,
                            ServiceStationNumber = 4,
                            SportActivityRoomArea = 1000f,
                            SportsActivityRoomNumber = 2,
                            StaffQuarterArea = 1000f,
                            StaffQuartersNumber = 1,
                            VillageName = "张浦社区"
                        },
                        new
                        {
                            Id = new Guid("f4bf71f4-c696-4a90-927d-1afc03765738"),
                            LibaryCollectionsNumber = 2500,
                            LibraryNumber = 1,
                            OfficeBuildingArea = 172f,
                            OfficeBuildingNumber = 1,
                            SeniorCitizenCenterArea = 380f,
                            SeniorCitizenCenterNumber = 1,
                            ServiceStationNumber = 2,
                            SportActivityRoomArea = 800f,
                            SportsActivityRoomNumber = 1,
                            StaffQuarterArea = 1200f,
                            StaffQuartersNumber = 1,
                            VillageName = "花园社区"
                        },
                        new
                        {
                            Id = new Guid("1d26ae2d-6974-4a16-b323-1ca5ad24b038"),
                            LibaryCollectionsNumber = 5000,
                            LibraryNumber = 1,
                            OfficeBuildingArea = 250f,
                            OfficeBuildingNumber = 2,
                            SeniorCitizenCenterArea = 700f,
                            SeniorCitizenCenterNumber = 2,
                            ServiceStationNumber = 1,
                            SportActivityRoomArea = 1500f,
                            SportsActivityRoomNumber = 3,
                            StaffQuarterArea = 2000f,
                            StaffQuartersNumber = 2,
                            VillageName = "振苏社区"
                        });
                });

            modelBuilder.Entity("AspNetCore.Entity.PartyMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Birthday");

                    b.Property<string>("ContactPhone");

                    b.Property<string>("DepartmentCode");

                    b.Property<string>("Education");

                    b.Property<string>("Gender");

                    b.Property<bool?>("IsFullMember");

                    b.Property<string>("MemberCode");

                    b.Property<string>("Nationality");

                    b.Property<string>("PartyMemberName");

                    b.Property<string>("PartyOrganizationName");

                    b.Property<string>("PartyPosition");

                    b.Property<string>("VillageName");

                    b.HasKey("Id");

                    b.ToTable("PartyMembers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("24074bf0-430e-44f4-9678-6085811d95a6"),
                            Birthday = new DateTime(1974, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ContactPhone = "13057134712",
                            DepartmentCode = "001",
                            Education = "本科",
                            Gender = "男",
                            IsFullMember = true,
                            MemberCode = "001000",
                            Nationality = "汉族",
                            PartyMemberName = "陈乐成",
                            PartyOrganizationName = "张浦社区党支部委员会",
                            PartyPosition = "无",
                            VillageName = "张浦社区"
                        });
                });

            modelBuilder.Entity("AspNetCore.Entity.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("RoleName")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("783d3395-1764-418a-9772-f3fa207bc8f6"),
                            RoleName = "Admin"
                        },
                        new
                        {
                            Id = new Guid("e01a243f-c285-42eb-aec1-ae5d99e6c020"),
                            RoleName = "Client"
                        },
                        new
                        {
                            Id = new Guid("b1edf7db-ee81-4f2b-be54-20b637caa3b4"),
                            RoleName = "System"
                        });
                });

            modelBuilder.Entity("AspNetCore.Entity.Town", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<string>("AreaNumber");

                    b.Property<string>("ChairmanName");

                    b.Property<string>("ContactPhone");

                    b.Property<int>("GovernmentLevel");

                    b.Property<string>("MayorName");

                    b.Property<string>("SecretaryName");

                    b.Property<string>("TownName");

                    b.HasKey("Id");

                    b.ToTable("Towns");

                    b.HasData(
                        new
                        {
                            Id = new Guid("cf1a317a-e2c2-46ab-8412-619f3f3ed66e"),
                            Address = "前进西路168号",
                            AreaNumber = "320583102000",
                            ChairmanName = "祖冲之",
                            ContactPhone = "0512-57621053",
                            GovernmentLevel = 4,
                            MayorName = "陆机",
                            SecretaryName = "陆云",
                            TownName = "周市镇"
                        },
                        new
                        {
                            Id = new Guid("a3da34d8-5fb9-4b50-b427-38f3e1ddb4aa"),
                            Address = "前进东路",
                            AreaNumber = "320583400000",
                            ChairmanName = "邢栋祥",
                            ContactPhone = "0512-57329416",
                            GovernmentLevel = 4,
                            MayorName = "逢建德",
                            SecretaryName = "匡俊智",
                            TownName = "开发区"
                        },
                        new
                        {
                            Id = new Guid("e6081eda-a460-4f83-b349-3a7130c835e5"),
                            Address = "花溪路358号",
                            AreaNumber = "320583104000",
                            ChairmanName = "武财章",
                            ContactPhone = "0512-57698733",
                            GovernmentLevel = 4,
                            MayorName = "王班",
                            SecretaryName = "吴启河",
                            TownName = "花桥镇"
                        },
                        new
                        {
                            Id = new Guid("f3042800-7c4e-42a7-9f33-fb54d695b0dc"),
                            Address = "华杨路188号",
                            AreaNumber = "320583106000",
                            ChairmanName = "成梦昆",
                            ContactPhone = "0512-57452503",
                            GovernmentLevel = 4,
                            MayorName = "刘赫伯",
                            SecretaryName = "蒋信迟",
                            TownName = "张浦镇"
                        },
                        new
                        {
                            Id = new Guid("a64b7d5e-a89c-4796-9af9-7aaf1e15ee90"),
                            Address = "菉溪路22号",
                            AreaNumber = "	320583103000",
                            ChairmanName = "李迪尉",
                            ContactPhone = "0512-57671003",
                            GovernmentLevel = 4,
                            MayorName = "梁灶慈",
                            SecretaryName = "刘群胜",
                            TownName = "陆家镇"
                        },
                        new
                        {
                            Id = new Guid("1236c799-6ba8-4247-8575-490181b097f7"),
                            Address = "新澄路918号",
                            AreaNumber = "320583101000",
                            ChairmanName = "周伟",
                            ContactPhone = "0521-57656330",
                            GovernmentLevel = 4,
                            MayorName = "李迪尉",
                            SecretaryName = "钟开桦",
                            TownName = "巴城镇"
                        },
                        new
                        {
                            Id = new Guid("96dc9fb4-ccc9-492a-a68d-9618d3c5abf3"),
                            Address = "炎东路",
                            AreaNumber = "320583108000",
                            ChairmanName = "林修胜",
                            ContactPhone = "0512-36620396",
                            GovernmentLevel = 4,
                            MayorName = "张弥成",
                            SecretaryName = "时可北",
                            TownName = "千灯镇"
                        },
                        new
                        {
                            Id = new Guid("4632e465-df78-466e-91a1-d05478ea856e"),
                            Address = "府前路78号",
                            AreaNumber = "320583105000",
                            ChairmanName = "常般业",
                            ContactPhone = "0512-57488358",
                            GovernmentLevel = 4,
                            MayorName = "冯便磊",
                            SecretaryName = "颜尚冲",
                            TownName = "淀山湖镇"
                        },
                        new
                        {
                            Id = new Guid("ed072c74-cbc9-4cf4-b393-98821cfb8b3d"),
                            Address = "淀南路100号",
                            AreaNumber = "320583107000",
                            ChairmanName = "陆先",
                            ContactPhone = "0521-57211236",
                            GovernmentLevel = 4,
                            MayorName = "王翱桦",
                            SecretaryName = "江衷力",
                            TownName = "周庄镇"
                        },
                        new
                        {
                            Id = new Guid("6b21cf9f-16d3-4b8a-8d56-545335ad96c3"),
                            Address = "普庆路1号",
                            AreaNumber = "320583109000",
                            ChairmanName = "邹鉴夕",
                            ContactPhone = "0521-57231290",
                            GovernmentLevel = 4,
                            MayorName = "倪御奋",
                            SecretaryName = "姬道生",
                            TownName = "锦溪镇"
                        });
                });

            modelBuilder.Entity("AspNetCore.Entity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(40);

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2b657f37-604f-4096-b756-ff49b644247b"),
                            Password = "admin",
                            UserName = "admin"
                        },
                        new
                        {
                            Id = new Guid("c03c25a1-dfc4-4d46-b1b5-9d10123655c7"),
                            Password = "user1",
                            UserName = "user1"
                        },
                        new
                        {
                            Id = new Guid("28ea152c-79d7-450e-b6ae-1e108834fa40"),
                            Password = "user2",
                            UserName = "user2"
                        },
                        new
                        {
                            Id = new Guid("3384518d-4d76-4b7a-83bc-8d779cffa458"),
                            Password = "user3",
                            UserName = "user3"
                        });
                });

            modelBuilder.Entity("AspNetCore.Entity.UserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("RoleId");

                    b.Property<Guid>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6b027a24-3c05-4383-bd9e-67217e52b62f"),
                            RoleId = new Guid("783d3395-1764-418a-9772-f3fa207bc8f6"),
                            UserId = new Guid("2b657f37-604f-4096-b756-ff49b644247b")
                        },
                        new
                        {
                            Id = new Guid("5cc834bc-8237-481c-bd21-f1960c90f052"),
                            RoleId = new Guid("e01a243f-c285-42eb-aec1-ae5d99e6c020"),
                            UserId = new Guid("c03c25a1-dfc4-4d46-b1b5-9d10123655c7")
                        },
                        new
                        {
                            Id = new Guid("72e9682e-6b22-400d-9715-66324ee58c8c"),
                            RoleId = new Guid("e01a243f-c285-42eb-aec1-ae5d99e6c020"),
                            UserId = new Guid("28ea152c-79d7-450e-b6ae-1e108834fa40")
                        },
                        new
                        {
                            Id = new Guid("6ff030b3-aa06-44be-bb6c-cc15782075a3"),
                            RoleId = new Guid("783d3395-1764-418a-9772-f3fa207bc8f6"),
                            UserId = new Guid("3384518d-4d76-4b7a-83bc-8d779cffa458")
                        },
                        new
                        {
                            Id = new Guid("af0a8560-9acc-44df-87f7-91538fbd4f26"),
                            RoleId = new Guid("b1edf7db-ee81-4f2b-be54-20b637caa3b4"),
                            UserId = new Guid("2b657f37-604f-4096-b756-ff49b644247b")
                        });
                });

            modelBuilder.Entity("AspNetCore.Entity.Village", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<string>("AreaNumber");

                    b.Property<string>("ContactPhone");

                    b.Property<int>("GovernmentLevel");

                    b.Property<int?>("GroupCount");

                    b.Property<string>("SecretaryName");

                    b.Property<int>("UrbanRuralClassification");

                    b.Property<string>("VillageHeadName");

                    b.Property<string>("VillageName");

                    b.HasKey("Id");

                    b.ToTable("Villages");

                    b.HasData(
                        new
                        {
                            Id = new Guid("cfa29fec-d824-4099-abc6-c3b432963b88"),
                            Address = "京东路469号",
                            AreaNumber = "320583106001",
                            ContactPhone = "0512-57441175",
                            GovernmentLevel = 5,
                            GroupCount = 12,
                            SecretaryName = "尹乐和",
                            UrbanRuralClassification = 111,
                            VillageHeadName = "赵乐欣",
                            VillageName = "张浦社区"
                        },
                        new
                        {
                            Id = new Guid("99172a1a-5733-4371-9cdf-3dd4c105f964"),
                            Address = "花苑路与京东路交叉口西侧",
                            AreaNumber = "320583106002",
                            ContactPhone = "0512-36863123",
                            GovernmentLevel = 5,
                            GroupCount = 26,
                            SecretaryName = "汤振海",
                            UrbanRuralClassification = 111,
                            VillageHeadName = "杜向阳",
                            VillageName = "花园社区"
                        },
                        new
                        {
                            Id = new Guid("06b40a0b-f476-4913-b02b-135ab2be8892"),
                            Address = "振苏六村",
                            AreaNumber = "320583106003",
                            ContactPhone = "0512-55270465",
                            GovernmentLevel = 5,
                            SecretaryName = "廖景天",
                            UrbanRuralClassification = 111,
                            VillageHeadName = "崔泰宁",
                            VillageName = "振苏社区"
                        },
                        new
                        {
                            Id = new Guid("5a1d5282-cda7-43bb-8498-8c72814d71ac"),
                            Address = "震阳路126号",
                            AreaNumber = "320583106004",
                            ContactPhone = "0512-57428835",
                            GovernmentLevel = 5,
                            SecretaryName = "阎乐池",
                            UrbanRuralClassification = 121,
                            VillageHeadName = "尹和蔼",
                            VillageName = "南港社区"
                        },
                        new
                        {
                            Id = new Guid("c7d55d8a-561c-4ac9-bcf8-1894a29d9884"),
                            Address = "淞沪西路36号",
                            AreaNumber = "320583106005",
                            ContactPhone = "0512-57256550",
                            GovernmentLevel = 5,
                            SecretaryName = "许宏畅",
                            UrbanRuralClassification = 220,
                            VillageHeadName = "薛兴为",
                            VillageName = "大市社区"
                        },
                        new
                        {
                            Id = new Guid("da5fcc37-1c12-4564-ac1e-f5ccdd0749a2"),
                            Address = "俱巷路894号",
                            AreaNumber = "320583106006",
                            ContactPhone = "0512-36691258",
                            GovernmentLevel = 5,
                            SecretaryName = "孔浩思",
                            UrbanRuralClassification = 111,
                            VillageHeadName = "王康胜",
                            VillageName = "新巷社区"
                        },
                        new
                        {
                            Id = new Guid("cccebd52-6016-4205-b6a2-a1848fc6ed80"),
                            Address = "商秧路178号",
                            AreaNumber = "320583106007",
                            ContactPhone = "0512-55272500",
                            GovernmentLevel = 5,
                            GroupCount = 26,
                            SecretaryName = "吴俊晤",
                            UrbanRuralClassification = 111,
                            VillageHeadName = "石欣德",
                            VillageName = "新吴社区"
                        },
                        new
                        {
                            Id = new Guid("f55d94b3-372e-4c4b-a82e-3c4922239dda"),
                            Address = "大直路504号",
                            AreaNumber = "320583106008",
                            ContactPhone = "0512-55272500",
                            GovernmentLevel = 5,
                            GroupCount = 23,
                            SecretaryName = "梁奇希",
                            UrbanRuralClassification = 112,
                            VillageHeadName = "吕勇男",
                            VillageName = "大直社区"
                        },
                        new
                        {
                            Id = new Guid("5ddf5806-4a1c-454d-bf79-a84bd650efb2"),
                            Address = "周巷路",
                            AreaNumber = "320583106009",
                            ContactPhone = "0512-57294577",
                            GovernmentLevel = 5,
                            GroupCount = 40,
                            SecretaryName = "姜永昌",
                            UrbanRuralClassification = 111,
                            VillageHeadName = "吴凯凯",
                            VillageName = "周巷社区"
                        },
                        new
                        {
                            Id = new Guid("c71241be-0e4b-4c35-a64f-b44dd37e0b0b"),
                            Address = "京东路588号",
                            AreaNumber = "320583106012",
                            ContactPhone = "0512-57883298",
                            GovernmentLevel = 5,
                            SecretaryName = "龙澔",
                            UrbanRuralClassification = 111,
                            VillageHeadName = "汤烨磊",
                            VillageName = "亲和社区"
                        },
                        new
                        {
                            Id = new Guid("0a1adf95-ff42-43d8-84bd-51e24e49b889"),
                            Address = "京东路731号",
                            AreaNumber = "320583106013",
                            ContactPhone = "0512-57278938",
                            GovernmentLevel = 5,
                            SecretaryName = "李段",
                            UrbanRuralClassification = 111,
                            VillageHeadName = "吕尊",
                            VillageName = "锦和社区"
                        },
                        new
                        {
                            Id = new Guid("185c86e6-54fd-4fb7-8700-02cce1e144b0"),
                            Address = "金华路1号",
                            AreaNumber = "320583106200",
                            ContactPhone = "0512-57293702",
                            GovernmentLevel = 5,
                            GroupCount = 26,
                            SecretaryName = "宋翰学",
                            UrbanRuralClassification = 112,
                            VillageHeadName = "龙昊焱",
                            VillageName = "金华村"
                        },
                        new
                        {
                            Id = new Guid("ec305b9a-9415-41e9-92c0-2cdcc54b5ae8"),
                            Address = "商鞅路1号",
                            AreaNumber = "320583106204",
                            ContactPhone = "0512-50310612",
                            GovernmentLevel = 5,
                            GroupCount = 20,
                            SecretaryName = "汤明亮",
                            UrbanRuralClassification = 112,
                            VillageHeadName = "吴咏德",
                            VillageName = "七桥村"
                        },
                        new
                        {
                            Id = new Guid("d479b7ff-3842-4164-b400-b73ae1fcfef7"),
                            Address = "机场路与兴陵路交叉口往南200米",
                            AreaNumber = "320583106205",
                            ContactPhone = "0512-57441476",
                            GovernmentLevel = 5,
                            GroupCount = 27,
                            SecretaryName = "邹俊雄",
                            UrbanRuralClassification = 220,
                            VillageHeadName = "程飞虎",
                            VillageName = "赵陵村"
                        },
                        new
                        {
                            Id = new Guid("198f26ac-f56f-49fe-ba86-e0f7b31e9725"),
                            Address = "川浩路22号",
                            AreaNumber = "320583106206",
                            ContactPhone = "0512-57441101",
                            GovernmentLevel = 5,
                            SecretaryName = "丁弘亮",
                            UrbanRuralClassification = 220,
                            VillageHeadName = "龚炎彬",
                            VillageName = "吴加村"
                        },
                        new
                        {
                            Id = new Guid("c8f50c7b-6459-419a-85c1-fbe8e577e3da"),
                            Address = "港浦东路8号",
                            AreaNumber = "320583106207",
                            ContactPhone = "0512-5736863220",
                            GovernmentLevel = 5,
                            GroupCount = 33,
                            SecretaryName = "史光临",
                            UrbanRuralClassification = 111,
                            VillageHeadName = "陈浦和",
                            VillageName = "三家村"
                        },
                        new
                        {
                            Id = new Guid("1b243d46-9503-4b28-a5d7-6d3c3248abec"),
                            Address = "盛巷花园门卫北侧",
                            AreaNumber = "320583106209",
                            ContactPhone = "0512-57441616",
                            GovernmentLevel = 5,
                            GroupCount = 20,
                            SecretaryName = "韩华藏",
                            UrbanRuralClassification = 111,
                            VillageHeadName = "萧泰河",
                            VillageName = "新塘村"
                        },
                        new
                        {
                            Id = new Guid("f0443a35-d67b-4ba6-8137-50c6c2f3f934"),
                            Address = "震阳路与双娄路交叉口",
                            AreaNumber = "320583106210",
                            ContactPhone = "0512-57421150",
                            GovernmentLevel = 5,
                            GroupCount = 35,
                            SecretaryName = "贺博艺",
                            UrbanRuralClassification = 122,
                            VillageHeadName = "冯鹏赋",
                            VillageName = "星金村"
                        },
                        new
                        {
                            Id = new Guid("b2522ddf-f62f-4b62-aa17-9e19d0d3de2b"),
                            Address = "陈邱家浜58号",
                            AreaNumber = "320583106211",
                            ContactPhone = "0512-50331469",
                            GovernmentLevel = 5,
                            GroupCount = 44,
                            SecretaryName = "孙明杰",
                            UrbanRuralClassification = 220,
                            VillageHeadName = "谭睿诚",
                            VillageName = "新龙村"
                        },
                        new
                        {
                            Id = new Guid("784885d6-3736-4708-893f-825058ae2539"),
                            Address = "建林路往北到底向西100米",
                            AreaNumber = "320583106212",
                            ContactPhone = "0512-57120550",
                            GovernmentLevel = 5,
                            SecretaryName = "万安怡",
                            UrbanRuralClassification = 220,
                            VillageHeadName = "萧波峻",
                            VillageName = "白米村"
                        },
                        new
                        {
                            Id = new Guid("1df02b11-599c-478b-a7a4-759ff0faf9e9"),
                            Address = "南港文体站",
                            AreaNumber = "320583106214",
                            ContactPhone = "0512-57428327",
                            GovernmentLevel = 5,
                            GroupCount = 28,
                            SecretaryName = "蒋英卓",
                            UrbanRuralClassification = 220,
                            VillageHeadName = "冯兴庆",
                            VillageName = "林庄村"
                        },
                        new
                        {
                            Id = new Guid("2c25a9c0-3fd1-4e52-b96b-fd96d46600ac"),
                            Address = "安头村公交站台往南60米处",
                            AreaNumber = "320583106215",
                            ContactPhone = "0512-57428927",
                            GovernmentLevel = 5,
                            GroupCount = 25,
                            SecretaryName = "郝嘉慕",
                            UrbanRuralClassification = 220,
                            VillageHeadName = "史意蕴",
                            VillageName = "安头村"
                        },
                        new
                        {
                            Id = new Guid("43d3421a-96ca-456f-b79e-94beb8d5258b"),
                            Address = "江浦南路与C325交叉处",
                            AreaNumber = "320583106219",
                            ContactPhone = "0512-57272133",
                            GovernmentLevel = 5,
                            GroupCount = 23,
                            SecretaryName = "漕文彦",
                            UrbanRuralClassification = 220,
                            VillageHeadName = "许高岑",
                            VillageName = "姜杭村"
                        },
                        new
                        {
                            Id = new Guid("62fdf56c-b79b-466b-9a25-bf6ad868e6ed"),
                            Address = "长江南路东侧与锦溪北交界",
                            AreaNumber = "320583106220",
                            ContactPhone = "0512-57256590",
                            GovernmentLevel = 5,
                            GroupCount = 21,
                            SecretaryName = "汤英耀",
                            UrbanRuralClassification = 220,
                            VillageHeadName = "蒋嘉许",
                            VillageName = "尚明甸村"
                        },
                        new
                        {
                            Id = new Guid("9339a3a6-ae1f-453c-a204-7a8d1e027da5"),
                            Address = "姚家港北首",
                            AreaNumber = "320583106221",
                            ContactPhone = "0512-57117756",
                            GovernmentLevel = 5,
                            GroupCount = 22,
                            SecretaryName = "杨成仁",
                            UrbanRuralClassification = 220,
                            VillageHeadName = "谢高义",
                            VillageName = "南姚村"
                        },
                        new
                        {
                            Id = new Guid("05b92add-e539-4b6b-849d-913691dbb515"),
                            Address = "淞沪西路与江浦南路交叉口",
                            AreaNumber = "320583106226",
                            ContactPhone = "0512-57255236",
                            GovernmentLevel = 5,
                            GroupCount = 49,
                            SecretaryName = "顾绍祺",
                            UrbanRuralClassification = 220,
                            VillageHeadName = "金和怡",
                            VillageName = "大市村"
                        },
                        new
                        {
                            Id = new Guid("af26698b-d4d9-4111-b47c-106805e25562"),
                            Address = "淞沪东路12号",
                            AreaNumber = "320583106227",
                            ContactPhone = "0512-57251131",
                            GovernmentLevel = 5,
                            SecretaryName = "朱嘉石",
                            UrbanRuralClassification = 220,
                            VillageHeadName = "顾飞羽",
                            VillageName = "南吉山村"
                        });
                });

            modelBuilder.Entity("AspNetCore.Entity.VillagerGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("MemberNumber");

                    b.Property<string>("PrincipalAddress");

                    b.Property<string>("PrincipalEmail");

                    b.Property<string>("PrincipalName");

                    b.Property<string>("PrincipalPhone");

                    b.Property<string>("VillageGroupCode");

                    b.Property<string>("VillageName");

                    b.HasKey("Id");

                    b.ToTable("VillagerGroups");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8d02e443-ff83-4182-b91e-d5893d5c9b00"),
                            MemberNumber = 356,
                            PrincipalAddress = "张浦镇望江新村6幢206室",
                            PrincipalEmail = "wuxuefei@kszpwz.gov.cn",
                            PrincipalName = "吴雪峰",
                            PrincipalPhone = "0512-57841234",
                            VillageGroupCode = "001",
                            VillageName = "南港社区"
                        },
                        new
                        {
                            Id = new Guid("e601acd2-ac71-4ac1-a375-a08591cf3d2b"),
                            MemberNumber = 412,
                            PrincipalAddress = "张浦镇富都新村3幢204室",
                            PrincipalEmail = "fangjitong@kszpfd.gov.cn",
                            PrincipalName = "方季同",
                            VillageGroupCode = "002",
                            VillageName = "南港社区"
                        },
                        new
                        {
                            Id = new Guid("0aa95d1a-1289-471d-8d94-36e295f92977"),
                            MemberNumber = 532,
                            PrincipalAddress = "张浦镇茶风新村1幢206室",
                            PrincipalEmail = "caogao@kszpcf.gov.cn",
                            PrincipalName = "蔡高",
                            VillageGroupCode = "003",
                            VillageName = "花园社区"
                        },
                        new
                        {
                            Id = new Guid("4039ff64-9702-441d-9bd3-7db2c33abb7a"),
                            MemberNumber = 253,
                            PrincipalAddress = "张浦镇富仁小区5幢102室",
                            PrincipalEmail = "changgaohan@kszpfr.gov.cn",
                            PrincipalName = "常高翰",
                            VillageGroupCode = "004",
                            VillageName = "大市社区"
                        },
                        new
                        {
                            Id = new Guid("90aced48-9ed4-4e89-9916-586c225f6f02"),
                            MemberNumber = 512,
                            PrincipalAddress = "张浦镇风和日丽5幢1102室",
                            PrincipalEmail = "qianyancheng@kszpfhrl.gov.cn",
                            PrincipalName = "钱阳成",
                            VillageGroupCode = "005",
                            VillageName = "南港社区"
                        },
                        new
                        {
                            Id = new Guid("48fbdb51-d344-4a4f-bf71-ce3cc8afcda1"),
                            MemberNumber = 567,
                            PrincipalAddress = "张浦镇枫情佳苑3幢306室",
                            PrincipalEmail = "kongzhiwen@kszpfqjy.gov.cn",
                            PrincipalName = "孔志文",
                            VillageGroupCode = "006",
                            VillageName = "新吴社区"
                        },
                        new
                        {
                            Id = new Guid("892792a7-d98a-4fc7-b22f-d18b31047bfb"),
                            MemberNumber = 476,
                            PrincipalAddress = "张浦镇张浦村14号",
                            PrincipalEmail = "huhaorang@kszpzp.gov.cn",
                            PrincipalName = "胡浩壤",
                            VillageGroupCode = "007",
                            VillageName = "张浦社区"
                        },
                        new
                        {
                            Id = new Guid("3f40ba31-a05e-4ce2-836e-fe7cb2ace6ef"),
                            MemberNumber = 345,
                            PrincipalAddress = "张浦镇张浦村142号",
                            PrincipalEmail = "xuexiuxian@kszpzp.gov.cn",
                            PrincipalName = "薛修贤",
                            VillageGroupCode = "008",
                            VillageName = "张浦社区"
                        },
                        new
                        {
                            Id = new Guid("d07b4e7d-8052-487f-9242-e5dd95ab03c2"),
                            MemberNumber = 452,
                            PrincipalAddress = "张浦镇银鹿新城3幢802室",
                            PrincipalEmail = "heliren@kszpylxc.gov.cn",
                            PrincipalName = "何立人",
                            VillageGroupCode = "009",
                            VillageName = "张浦社区"
                        },
                        new
                        {
                            Id = new Guid("c83c284e-4308-468f-921b-0665af8860fa"),
                            MemberNumber = 662,
                            PrincipalAddress = "张浦镇牡丹苑7幢502",
                            PrincipalEmail = "zhongjunde@kszpmdy.gov.cn",
                            PrincipalName = "钟俊德",
                            VillageGroupCode = "010",
                            VillageName = "周巷社区"
                        },
                        new
                        {
                            Id = new Guid("4674bedd-3f42-4dfb-9ad8-d34fd80d16bc"),
                            MemberNumber = 341,
                            PrincipalAddress = "张浦镇江南春堤14号",
                            PrincipalEmail = "jiatianzong@kszpjnkd.gov.cn",
                            PrincipalName = "贾天纵",
                            VillageGroupCode = "011",
                            VillageName = "新巷社区"
                        },
                        new
                        {
                            Id = new Guid("f70c92ba-da8a-45cf-888d-5189d275e26a"),
                            MemberNumber = 543,
                            PrincipalAddress = "张浦镇安居小区24号",
                            PrincipalEmail = "duanxuehai@kszpanxq.gov.cn",
                            PrincipalName = "段学海",
                            VillageGroupCode = "012",
                            VillageName = "大市社区"
                        });
                });

            modelBuilder.Entity("AspNetCore.Entity.UserRole", b =>
                {
                    b.HasOne("AspNetCore.Entity.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AspNetCore.Entity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
