// <auto-generated />
using System;
using AspNetCore.Entity.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace AspNetCore.Entity.Migrations
{
    [DbContext(typeof(MsContext))]
    [Migration("20190414051124_Migration09")]
    partial class Migration09
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:PostgresExtension:uuid-ossp", ",,")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("AspNetCore.Entity.AdminDivision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AreaNumber");

                    b.Property<int>("CountyNumber");

                    b.Property<int>("GovernmentLevel");

                    b.Property<string>("GovernmentName");

                    b.Property<string>("HighLevelAreaNumber");

                    b.Property<int>("VillageGroupNumber");

                    b.Property<int>("VillageNumber");

                    b.HasKey("Id");

                    b.ToTable("AdminDivisions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0387baed-836d-49bc-be1a-d1691f59fddb"),
                            AreaNumber = "320583000000",
                            CountyNumber = 0,
                            GovernmentLevel = 3,
                            GovernmentName = "昆山市",
                            HighLevelAreaNumber = "",
                            VillageGroupNumber = 2205,
                            VillageNumber = 10
                        },
                        new
                        {
                            Id = new Guid("93d9ba17-d321-4f6a-bbe6-e65e8285115b"),
                            AreaNumber = "320583102000",
                            CountyNumber = 0,
                            GovernmentLevel = 4,
                            GovernmentName = "周市镇",
                            HighLevelAreaNumber = "320583000000",
                            VillageGroupNumber = 240,
                            VillageNumber = 29
                        },
                        new
                        {
                            Id = new Guid("4d399b64-e030-4762-a459-719a3a278e52"),
                            AreaNumber = "320583400000",
                            CountyNumber = 0,
                            GovernmentLevel = 4,
                            GovernmentName = "开发区",
                            HighLevelAreaNumber = "320583000000",
                            VillageGroupNumber = 312,
                            VillageNumber = 7
                        },
                        new
                        {
                            Id = new Guid("464e2a0c-de9a-4a29-9ae2-bdcf2ec4be63"),
                            AreaNumber = "320583104000",
                            CountyNumber = 0,
                            GovernmentLevel = 4,
                            GovernmentName = "花桥镇",
                            HighLevelAreaNumber = "320583000000",
                            VillageGroupNumber = 123,
                            VillageNumber = 13
                        },
                        new
                        {
                            Id = new Guid("0458c3ce-e80d-42d1-9d98-d2ff6c413b59"),
                            AreaNumber = "320583106000",
                            CountyNumber = 0,
                            GovernmentLevel = 4,
                            GovernmentName = "张浦镇",
                            HighLevelAreaNumber = "320583000000",
                            VillageGroupNumber = 221,
                            VillageNumber = 12
                        },
                        new
                        {
                            Id = new Guid("5c175f0a-cede-48a5-aebf-cd88f0f9c708"),
                            AreaNumber = "320583103000",
                            CountyNumber = 0,
                            GovernmentLevel = 4,
                            GovernmentName = "陆家镇",
                            HighLevelAreaNumber = "320583000000",
                            VillageGroupNumber = 231,
                            VillageNumber = 13
                        },
                        new
                        {
                            Id = new Guid("1b549175-d02e-487c-ade5-4ab8dd8eab7c"),
                            AreaNumber = "320583101000",
                            CountyNumber = 0,
                            GovernmentLevel = 4,
                            GovernmentName = "巴城镇",
                            HighLevelAreaNumber = "320583000000",
                            VillageGroupNumber = 216,
                            VillageNumber = 13
                        },
                        new
                        {
                            Id = new Guid("b2bcb90b-003d-45f6-86d9-a999280b5523"),
                            AreaNumber = "320583101000",
                            CountyNumber = 0,
                            GovernmentLevel = 4,
                            GovernmentName = "巴城镇",
                            HighLevelAreaNumber = "320583000000",
                            VillageGroupNumber = 216,
                            VillageNumber = 13
                        },
                        new
                        {
                            Id = new Guid("c6e3105b-6883-4c00-82ac-d92a9f7295a6"),
                            AreaNumber = "320583101000",
                            CountyNumber = 0,
                            GovernmentLevel = 4,
                            GovernmentName = "巴城镇",
                            HighLevelAreaNumber = "320583000000",
                            VillageGroupNumber = 216,
                            VillageNumber = 13
                        },
                        new
                        {
                            Id = new Guid("3775994b-0556-4883-b9d4-e42e4bf07615"),
                            AreaNumber = "320583108000",
                            CountyNumber = 0,
                            GovernmentLevel = 4,
                            GovernmentName = "千灯镇",
                            HighLevelAreaNumber = "320583000000",
                            VillageGroupNumber = 213,
                            VillageNumber = 41
                        },
                        new
                        {
                            Id = new Guid("e3794a01-748a-4cde-82c7-c21cffb25e21"),
                            AreaNumber = "320583105000",
                            CountyNumber = 0,
                            GovernmentLevel = 4,
                            GovernmentName = "淀山湖镇",
                            HighLevelAreaNumber = "320583000000",
                            VillageGroupNumber = 173,
                            VillageNumber = 11
                        },
                        new
                        {
                            Id = new Guid("db93b46d-6195-49f4-8191-ef4036110b82"),
                            AreaNumber = "320583107000",
                            CountyNumber = 0,
                            GovernmentLevel = 4,
                            GovernmentName = "周庄镇",
                            HighLevelAreaNumber = "320583000000",
                            VillageGroupNumber = 123,
                            VillageNumber = 31
                        },
                        new
                        {
                            Id = new Guid("bbc700a6-03e4-4a64-8d36-b380a97dbe03"),
                            AreaNumber = "320583109000",
                            CountyNumber = 0,
                            GovernmentLevel = 4,
                            GovernmentName = "锦溪镇",
                            HighLevelAreaNumber = "320583000000",
                            VillageGroupNumber = 256,
                            VillageNumber = 22
                        },
                        new
                        {
                            Id = new Guid("ae267179-9a10-4c80-8268-853786f5e966"),
                            AreaNumber = "320583106001",
                            CountyNumber = 0,
                            GovernmentLevel = 5,
                            GovernmentName = "张浦社区",
                            HighLevelAreaNumber = "320583106000",
                            VillageGroupNumber = 12,
                            VillageNumber = 0
                        },
                        new
                        {
                            Id = new Guid("07e38f1f-2577-49da-822d-ae75649ca594"),
                            AreaNumber = "320583106002",
                            CountyNumber = 0,
                            GovernmentLevel = 5,
                            GovernmentName = "花园社区",
                            HighLevelAreaNumber = "320583106000",
                            VillageGroupNumber = 12,
                            VillageNumber = 0
                        },
                        new
                        {
                            Id = new Guid("e4716e3c-4f19-464a-905c-0d37de504548"),
                            AreaNumber = "320583106003",
                            CountyNumber = 0,
                            GovernmentLevel = 5,
                            GovernmentName = "振苏社区",
                            HighLevelAreaNumber = "320583106000",
                            VillageGroupNumber = 12,
                            VillageNumber = 0
                        },
                        new
                        {
                            Id = new Guid("8dea4e0c-98f8-4caa-89c6-c15d5dde07d4"),
                            AreaNumber = "320583106004",
                            CountyNumber = 0,
                            GovernmentLevel = 5,
                            GovernmentName = "南港社区",
                            HighLevelAreaNumber = "320583106000",
                            VillageGroupNumber = 12,
                            VillageNumber = 0
                        });
                });

            modelBuilder.Entity("AspNetCore.Entity.Core.Villager", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AnnualIncome");

                    b.Property<DateTime>("Birthday");

                    b.Property<string>("Education");

                    b.Property<string>("Gender")
                        .IsRequired();

                    b.Property<bool>("HavingCriminalRecord");

                    b.Property<bool>("HavingIllegalRecord");

                    b.Property<string>("HomeAddress")
                        .IsRequired();

                    b.Property<string>("MaritalStatus");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Villagers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("270d3953-7b76-4e8c-97b7-67ba4a44065e"),
                            AnnualIncome = 20000,
                            Birthday = new DateTime(1984, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Education = "高中",
                            Gender = "男",
                            HavingCriminalRecord = false,
                            HavingIllegalRecord = false,
                            HomeAddress = "向阳村3组14号",
                            MaritalStatus = "已婚",
                            Name = "张东"
                        },
                        new
                        {
                            Id = new Guid("d6a55bef-ec66-4561-82dc-b51ed0eaf84a"),
                            AnnualIncome = 17000,
                            Birthday = new DateTime(1972, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Education = "初中",
                            Gender = "男",
                            HavingCriminalRecord = false,
                            HavingIllegalRecord = false,
                            HomeAddress = "向阳村5组17号",
                            MaritalStatus = "已婚",
                            Name = "刘项"
                        },
                        new
                        {
                            Id = new Guid("f8650d08-8232-4e7b-91ca-edeaa50eaa78"),
                            AnnualIncome = 50000,
                            Birthday = new DateTime(1990, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Education = "本科",
                            Gender = "男",
                            HavingCriminalRecord = false,
                            HavingIllegalRecord = false,
                            HomeAddress = "向阳村1组2号",
                            MaritalStatus = "未婚",
                            Name = "马伦"
                        });
                });

            modelBuilder.Entity("AspNetCore.Entity.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<string>("ContactPhone");

                    b.Property<string>("DepartmentCode");

                    b.Property<string>("DepartmentName");

                    b.Property<string>("Email");

                    b.Property<string>("Fax");

                    b.Property<string>("Notes");

                    b.Property<string>("PrincipalName");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f164074a-c46d-4e67-89bb-64933e305c87"),
                            Address = "京东路469号",
                            ContactPhone = "0512-57623451",
                            DepartmentCode = "001",
                            DepartmentName = "张浦社区党支部委员会",
                            Email = "zhenxinguo@kszpzp.gov.cn",
                            Fax = "0512-54123412",
                            Notes = "",
                            PrincipalName = "郑兴国"
                        },
                        new
                        {
                            Id = new Guid("356a0885-12d3-4baa-8488-8230a1913741"),
                            Address = "京东路469号",
                            ContactPhone = "0512-58289432",
                            DepartmentCode = "002",
                            DepartmentName = "张浦社区居民委员会",
                            Email = "chenlecheng@kszpzp.gov.cn",
                            Fax = "0512-59283414",
                            Notes = "临时兼任",
                            PrincipalName = "陈乐成"
                        },
                        new
                        {
                            Id = new Guid("2ccd9cfa-74c0-4e6e-91ad-f5ffea51e2d5"),
                            Address = "花苑路与京东路交叉口西侧",
                            ContactPhone = "0512-54128123",
                            DepartmentCode = "003",
                            DepartmentName = "花园社区党支部委员会",
                            Email = "xugaoyi@kszpzp.gov.cn",
                            Fax = "0512-564178314",
                            PrincipalName = "许高义"
                        });
                });

            modelBuilder.Entity("AspNetCore.Entity.Family", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AccountCharacter");

                    b.Property<int>("AverageAnnualIncome");

                    b.Property<float>("AverageHousingArea");

                    b.Property<string>("FamilyCode");

                    b.Property<string>("Householder");

                    b.Property<float>("HousingArea");

                    b.Property<bool>("IsLowIncome");

                    b.Property<bool>("IsPoor");

                    b.Property<int>("PeopleNumber");

                    b.Property<string>("VillageGroupCode");

                    b.Property<string>("VillageName");

                    b.HasKey("Id");

                    b.ToTable("Families");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f86d2484-6714-443d-8c8e-8a2d31e60bc4"),
                            AccountCharacter = "非农业",
                            AverageAnnualIncome = 5000,
                            AverageHousingArea = 20.84f,
                            FamilyCode = "001000",
                            Householder = "秦博厚",
                            HousingArea = 104.2f,
                            IsLowIncome = false,
                            IsPoor = false,
                            PeopleNumber = 5,
                            VillageGroupCode = "001"
                        });
                });

            modelBuilder.Entity("AspNetCore.Entity.Member", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Birthday");

                    b.Property<string>("DepartmentCode");

                    b.Property<string>("Education");

                    b.Property<DateTime>("EntryTime");

                    b.Property<string>("Gender");

                    b.Property<string>("HomeAddress");

                    b.Property<string>("IdCardNumber");

                    b.Property<DateTime>("LeaveTime");

                    b.Property<string>("LengthOfService");

                    b.Property<string>("MaritalStatus");

                    b.Property<string>("MemberCode");

                    b.Property<string>("MemberName");

                    b.Property<string>("Nationality");

                    b.Property<string>("PersonnelNature");

                    b.Property<string>("PoliticalStatus");

                    b.Property<string>("Position");

                    b.Property<string>("Status");

                    b.HasKey("Id");

                    b.ToTable("Members");

                    b.HasData(
                        new
                        {
                            Id = new Guid("407c17ce-597f-4663-bfbe-5ffc7f5ca8fa"),
                            Birthday = new DateTime(1974, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentCode = "002",
                            Education = "本科",
                            EntryTime = new DateTime(2007, 2, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = "男",
                            HomeAddress = "张浦镇江北新村14号",
                            IdCardNumber = "320583197407056857",
                            LeaveTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LengthOfService = "12年",
                            MaritalStatus = "已婚",
                            MemberCode = "002000",
                            MemberName = "陈乐成",
                            Nationality = "汉族",
                            PoliticalStatus = "中共党员",
                            Position = "主任",
                            Status = "在职"
                        },
                        new
                        {
                            Id = new Guid("2af3af03-02df-4c95-b8a9-6bef9d1868c3"),
                            Birthday = new DateTime(1977, 7, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentCode = "002",
                            Education = "本科",
                            EntryTime = new DateTime(2002, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = "男",
                            HomeAddress = "张浦镇浦江北新村112号",
                            IdCardNumber = "320583197707087692",
                            LeaveTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LengthOfService = "17年",
                            MaritalStatus = "已婚",
                            MemberCode = "002001",
                            MemberName = "姜兴安",
                            Nationality = "汉族",
                            PoliticalStatus = "中共党员",
                            Position = "副主任",
                            Status = "在职"
                        },
                        new
                        {
                            Id = new Guid("38591f2f-ad4a-4131-8003-fe76e041edfc"),
                            Birthday = new DateTime(1985, 4, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentCode = "002",
                            Education = "高中",
                            EntryTime = new DateTime(2010, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = "男",
                            HomeAddress = "张浦镇江北新村56号",
                            IdCardNumber = "320583198504178937",
                            LeaveTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LengthOfService = "9年",
                            MaritalStatus = "丧偶",
                            MemberCode = "002002",
                            MemberName = "于君昊",
                            Nationality = "汉族",
                            PoliticalStatus = "中共党员",
                            Position = "治调委员",
                            Status = "在职"
                        },
                        new
                        {
                            Id = new Guid("536f3911-1b81-434d-9ce0-b6befe473a6d"),
                            Birthday = new DateTime(1979, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentCode = "002",
                            Education = "硕士研究生",
                            EntryTime = new DateTime(2005, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = "男",
                            HomeAddress = "张浦镇江北新村12号",
                            IdCardNumber = "320583197910154878",
                            LeaveTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LengthOfService = "14年",
                            MaritalStatus = "离异",
                            MemberCode = "002003",
                            MemberName = "康志国",
                            Nationality = "汉族",
                            PoliticalStatus = "群众",
                            Position = "财经委员",
                            Status = "在职"
                        },
                        new
                        {
                            Id = new Guid("b13781d2-3fd4-46e4-acb9-79ce8a194ec6"),
                            Birthday = new DateTime(1987, 4, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentCode = "002",
                            Education = "本科",
                            EntryTime = new DateTime(2007, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = "女",
                            HomeAddress = "张浦镇江北新村17号",
                            IdCardNumber = "320583198704187965",
                            LeaveTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LengthOfService = "12年",
                            MaritalStatus = "已婚",
                            MemberCode = "002004",
                            MemberName = "赵陈红",
                            Nationality = "汉族",
                            PoliticalStatus = "群众",
                            Position = "妇女计生委员",
                            Status = "在职"
                        });
                });

            modelBuilder.Entity("AspNetCore.Entity.NonOperatingAssets", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("LibaryCollectionsNumber");

                    b.Property<int>("LibraryNumber");

                    b.Property<float>("OfficeBuildingArea");

                    b.Property<int>("OfficeBuildingNumber");

                    b.Property<float>("SeniorCitizenCenterArea");

                    b.Property<int>("SeniorCitizenCenterNumber");

                    b.Property<int>("ServiceStationNumber");

                    b.Property<float>("SportActivityRoomArea");

                    b.Property<int>("SportsActivityRoomNumber");

                    b.Property<float>("StaffQuarterArea");

                    b.Property<int>("StaffQuartersNumber");

                    b.Property<string>("VillageName");

                    b.HasKey("Id");

                    b.ToTable("NonOperatingAssets");

                    b.HasData(
                        new
                        {
                            Id = new Guid("88ca0853-912a-4df6-9c8f-0f416d1e0a35"),
                            LibaryCollectionsNumber = 3000,
                            LibraryNumber = 1,
                            OfficeBuildingArea = 105f,
                            OfficeBuildingNumber = 1,
                            SeniorCitizenCenterArea = 450f,
                            SeniorCitizenCenterNumber = 1,
                            ServiceStationNumber = 4,
                            SportActivityRoomArea = 1000f,
                            SportsActivityRoomNumber = 2,
                            StaffQuarterArea = 1000f,
                            StaffQuartersNumber = 1,
                            VillageName = "张浦社区"
                        },
                        new
                        {
                            Id = new Guid("28314b8a-fd71-4c97-8a33-cc148bbede7b"),
                            LibaryCollectionsNumber = 2500,
                            LibraryNumber = 1,
                            OfficeBuildingArea = 172f,
                            OfficeBuildingNumber = 1,
                            SeniorCitizenCenterArea = 380f,
                            SeniorCitizenCenterNumber = 1,
                            ServiceStationNumber = 2,
                            SportActivityRoomArea = 800f,
                            SportsActivityRoomNumber = 1,
                            StaffQuarterArea = 1200f,
                            StaffQuartersNumber = 1,
                            VillageName = "花园社区"
                        },
                        new
                        {
                            Id = new Guid("3f1b9bc1-1e14-4807-b057-35daddbfd921"),
                            LibaryCollectionsNumber = 5000,
                            LibraryNumber = 1,
                            OfficeBuildingArea = 250f,
                            OfficeBuildingNumber = 2,
                            SeniorCitizenCenterArea = 700f,
                            SeniorCitizenCenterNumber = 2,
                            ServiceStationNumber = 1,
                            SportActivityRoomArea = 1500f,
                            SportsActivityRoomNumber = 3,
                            StaffQuarterArea = 2000f,
                            StaffQuartersNumber = 2,
                            VillageName = "振苏社区"
                        });
                });

            modelBuilder.Entity("AspNetCore.Entity.PartyMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Birthday");

                    b.Property<string>("ContactPhone");

                    b.Property<string>("DepartmentCode");

                    b.Property<string>("Education");

                    b.Property<string>("Gender");

                    b.Property<bool?>("IsFullMember");

                    b.Property<string>("MemberCode");

                    b.Property<string>("Nationality");

                    b.Property<string>("PartyMemberName");

                    b.Property<string>("PartyOrganizationName");

                    b.Property<string>("PartyPosition");

                    b.Property<string>("VillageName");

                    b.HasKey("Id");

                    b.ToTable("PartyMembers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0055c71d-19ae-4653-a9be-c69a1f5d6a67"),
                            Birthday = new DateTime(1974, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ContactPhone = "13057134712",
                            DepartmentCode = "001",
                            Education = "本科",
                            Gender = "男",
                            IsFullMember = true,
                            MemberCode = "001000",
                            Nationality = "汉族",
                            PartyMemberName = "陈乐成",
                            PartyOrganizationName = "张浦社区党支部委员会",
                            PartyPosition = "无",
                            VillageName = "张浦社区"
                        });
                });

            modelBuilder.Entity("AspNetCore.Entity.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("RoleName")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bc9077b4-c5a8-46a8-8e77-f934e5d17d6a"),
                            RoleName = "Admin"
                        },
                        new
                        {
                            Id = new Guid("6819af08-0b4b-4537-9ad0-2ab11ba1340e"),
                            RoleName = "Client"
                        },
                        new
                        {
                            Id = new Guid("3cddd6dd-3d43-4c23-8f67-ba17916b4b1f"),
                            RoleName = "System"
                        });
                });

            modelBuilder.Entity("AspNetCore.Entity.Town", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<string>("AreaNumber");

                    b.Property<string>("ChairmanName");

                    b.Property<string>("ContactPhone");

                    b.Property<int>("GovernmentLevel");

                    b.Property<string>("MayorName");

                    b.Property<string>("SecretaryName");

                    b.Property<string>("TownName");

                    b.HasKey("Id");

                    b.ToTable("Towns");

                    b.HasData(
                        new
                        {
                            Id = new Guid("71bffd6d-957b-4fad-b82c-194bb49cd331"),
                            Address = "前进西路168号",
                            AreaNumber = "320583102000",
                            ChairmanName = "祖冲之",
                            ContactPhone = "0512-57621053",
                            GovernmentLevel = 4,
                            MayorName = "陆机",
                            SecretaryName = "陆云",
                            TownName = "周市镇"
                        },
                        new
                        {
                            Id = new Guid("429c5703-5333-4cd8-9604-7829927ddc86"),
                            Address = "前进东路",
                            AreaNumber = "320583400000",
                            ChairmanName = "邢栋祥",
                            ContactPhone = "0512-57329416",
                            GovernmentLevel = 4,
                            MayorName = "逢建德",
                            SecretaryName = "匡俊智",
                            TownName = "开发区"
                        },
                        new
                        {
                            Id = new Guid("ac1ec2aa-df9b-4105-babe-915a33db964d"),
                            Address = "花溪路358号",
                            AreaNumber = "320583104000",
                            ChairmanName = "武财章",
                            ContactPhone = "0512-57698733",
                            GovernmentLevel = 4,
                            MayorName = "王班",
                            SecretaryName = "吴启河",
                            TownName = "花桥镇"
                        },
                        new
                        {
                            Id = new Guid("eda79180-1263-4d10-ba3c-3d39a136f67d"),
                            Address = "华杨路188号",
                            AreaNumber = "320583106000",
                            ChairmanName = "成梦昆",
                            ContactPhone = "0512-57452503",
                            GovernmentLevel = 4,
                            MayorName = "刘赫伯",
                            SecretaryName = "蒋信迟",
                            TownName = "张浦镇"
                        },
                        new
                        {
                            Id = new Guid("5732ec3f-4213-4d4b-956f-7bba2d1b4a84"),
                            Address = "菉溪路22号",
                            AreaNumber = "	320583103000",
                            ChairmanName = "李迪尉",
                            ContactPhone = "0512-57671003",
                            GovernmentLevel = 4,
                            MayorName = "梁灶慈",
                            SecretaryName = "刘群胜",
                            TownName = "陆家镇"
                        },
                        new
                        {
                            Id = new Guid("c5893c85-3470-4679-8272-96387d306a5d"),
                            Address = "新澄路918号",
                            AreaNumber = "320583101000",
                            ChairmanName = "周伟",
                            ContactPhone = "0521-57656330",
                            GovernmentLevel = 4,
                            MayorName = "李迪尉",
                            SecretaryName = "钟开桦",
                            TownName = "巴城镇"
                        },
                        new
                        {
                            Id = new Guid("af2f0ed8-ac87-4101-97b8-c0608782006e"),
                            Address = "炎东路",
                            AreaNumber = "320583108000",
                            ChairmanName = "林修胜",
                            ContactPhone = "0512-36620396",
                            GovernmentLevel = 4,
                            MayorName = "张弥成",
                            SecretaryName = "时可北",
                            TownName = "千灯镇"
                        },
                        new
                        {
                            Id = new Guid("5d863c7e-8200-40e6-94c4-768ae1e6c9a9"),
                            Address = "府前路78号",
                            AreaNumber = "320583105000",
                            ChairmanName = "常般业",
                            ContactPhone = "0512-57488358",
                            GovernmentLevel = 4,
                            MayorName = "冯便磊",
                            SecretaryName = "颜尚冲",
                            TownName = "淀山湖镇"
                        },
                        new
                        {
                            Id = new Guid("435299e4-c9c5-4ebb-ae96-d293545549a2"),
                            Address = "淀南路100号",
                            AreaNumber = "320583107000",
                            ChairmanName = "陆先",
                            ContactPhone = "0521-57211236",
                            GovernmentLevel = 4,
                            MayorName = "王翱桦",
                            SecretaryName = "江衷力",
                            TownName = "周庄镇"
                        },
                        new
                        {
                            Id = new Guid("437313c6-e49e-4d67-810d-762536dd6c1d"),
                            Address = "普庆路1号",
                            AreaNumber = "320583109000",
                            ChairmanName = "邹鉴夕",
                            ContactPhone = "0521-57231290",
                            GovernmentLevel = 4,
                            MayorName = "倪御奋",
                            SecretaryName = "姬道生",
                            TownName = "锦溪镇"
                        });
                });

            modelBuilder.Entity("AspNetCore.Entity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(40);

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b1584dcd-c492-4e92-a128-40357c36596e"),
                            Password = "admin",
                            UserName = "admin"
                        },
                        new
                        {
                            Id = new Guid("2b1aaa70-00a4-4e64-9ee6-43cf22156b14"),
                            Password = "user1",
                            UserName = "user1"
                        },
                        new
                        {
                            Id = new Guid("d7f45dcb-74e6-4c58-bd9b-cd9fa4066920"),
                            Password = "user2",
                            UserName = "user2"
                        },
                        new
                        {
                            Id = new Guid("539cbbf2-2bec-498a-9a8a-f64c8f848a1d"),
                            Password = "user3",
                            UserName = "user3"
                        });
                });

            modelBuilder.Entity("AspNetCore.Entity.UserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("RoleId");

                    b.Property<Guid>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("572b55c0-da7f-4070-8cfc-23ec80a7e773"),
                            RoleId = new Guid("bc9077b4-c5a8-46a8-8e77-f934e5d17d6a"),
                            UserId = new Guid("b1584dcd-c492-4e92-a128-40357c36596e")
                        },
                        new
                        {
                            Id = new Guid("6eee6d65-b4fe-4d42-9b21-0a09cf8e0491"),
                            RoleId = new Guid("6819af08-0b4b-4537-9ad0-2ab11ba1340e"),
                            UserId = new Guid("2b1aaa70-00a4-4e64-9ee6-43cf22156b14")
                        },
                        new
                        {
                            Id = new Guid("1a511339-8501-4a11-85b7-a3915c4118db"),
                            RoleId = new Guid("6819af08-0b4b-4537-9ad0-2ab11ba1340e"),
                            UserId = new Guid("d7f45dcb-74e6-4c58-bd9b-cd9fa4066920")
                        },
                        new
                        {
                            Id = new Guid("2b842230-a9a1-45bf-ab32-2f6e0bb2a1f2"),
                            RoleId = new Guid("bc9077b4-c5a8-46a8-8e77-f934e5d17d6a"),
                            UserId = new Guid("539cbbf2-2bec-498a-9a8a-f64c8f848a1d")
                        },
                        new
                        {
                            Id = new Guid("72d95943-19d2-4e16-ad69-cf6cdca32f89"),
                            RoleId = new Guid("3cddd6dd-3d43-4c23-8f67-ba17916b4b1f"),
                            UserId = new Guid("b1584dcd-c492-4e92-a128-40357c36596e")
                        });
                });

            modelBuilder.Entity("AspNetCore.Entity.Village", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<string>("AreaNumber");

                    b.Property<string>("ContactPhone");

                    b.Property<int>("GovernmentLevel");

                    b.Property<int?>("GroupCount");

                    b.Property<string>("HighLevelAreaNumber");

                    b.Property<string>("SecretaryName");

                    b.Property<int>("UrbanRuralClassification");

                    b.Property<string>("VillageHeadName");

                    b.Property<string>("VillageName");

                    b.HasKey("Id");

                    b.ToTable("Villages");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f7610492-ea41-4a5d-a304-fe088a503455"),
                            Address = "京东路469号",
                            AreaNumber = "320583106001",
                            ContactPhone = "0512-57441175",
                            GovernmentLevel = 5,
                            GroupCount = 12,
                            HighLevelAreaNumber = "320583106000",
                            SecretaryName = "尹乐和",
                            UrbanRuralClassification = 111,
                            VillageHeadName = "赵乐欣",
                            VillageName = "张浦社区"
                        },
                        new
                        {
                            Id = new Guid("7bc02a90-9c0a-45d2-b291-39e8acbeb6c7"),
                            Address = "花苑路与京东路交叉口西侧",
                            AreaNumber = "320583106002",
                            ContactPhone = "0512-36863123",
                            GovernmentLevel = 5,
                            GroupCount = 26,
                            HighLevelAreaNumber = "320583106000",
                            SecretaryName = "汤振海",
                            UrbanRuralClassification = 111,
                            VillageHeadName = "杜向阳",
                            VillageName = "花园社区"
                        },
                        new
                        {
                            Id = new Guid("202a0240-1e8e-4ccc-8377-01faf79d2bfa"),
                            Address = "振苏六村",
                            AreaNumber = "320583106003",
                            ContactPhone = "0512-55270465",
                            GovernmentLevel = 5,
                            HighLevelAreaNumber = "320583106000",
                            SecretaryName = "廖景天",
                            UrbanRuralClassification = 111,
                            VillageHeadName = "崔泰宁",
                            VillageName = "振苏社区"
                        },
                        new
                        {
                            Id = new Guid("242c5877-2ebf-4354-a107-529ef69df130"),
                            Address = "震阳路126号",
                            AreaNumber = "320583106004",
                            ContactPhone = "0512-57428835",
                            GovernmentLevel = 5,
                            HighLevelAreaNumber = "320583106000",
                            SecretaryName = "阎乐池",
                            UrbanRuralClassification = 121,
                            VillageHeadName = "尹和蔼",
                            VillageName = "南港社区"
                        },
                        new
                        {
                            Id = new Guid("efba154a-a716-43c1-b268-56665854fade"),
                            Address = "淞沪西路36号",
                            AreaNumber = "320583106005",
                            ContactPhone = "0512-57256550",
                            GovernmentLevel = 5,
                            HighLevelAreaNumber = "320583106000",
                            SecretaryName = "许宏畅",
                            UrbanRuralClassification = 220,
                            VillageHeadName = "薛兴为",
                            VillageName = "大市社区"
                        },
                        new
                        {
                            Id = new Guid("eea279da-5e02-4364-8b6d-882629a90e86"),
                            Address = "俱巷路894号",
                            AreaNumber = "320583106006",
                            ContactPhone = "0512-36691258",
                            GovernmentLevel = 5,
                            HighLevelAreaNumber = "320583106000",
                            SecretaryName = "孔浩思",
                            UrbanRuralClassification = 111,
                            VillageHeadName = "王康胜",
                            VillageName = "新巷社区"
                        },
                        new
                        {
                            Id = new Guid("8d77535b-c012-419f-a7d8-9c366f82e947"),
                            Address = "商秧路178号",
                            AreaNumber = "320583106007",
                            ContactPhone = "0512-55272500",
                            GovernmentLevel = 5,
                            GroupCount = 26,
                            HighLevelAreaNumber = "320583106000",
                            SecretaryName = "吴俊晤",
                            UrbanRuralClassification = 111,
                            VillageHeadName = "石欣德",
                            VillageName = "新吴社区"
                        },
                        new
                        {
                            Id = new Guid("550683b9-4f4d-45d7-bf7e-7e33d768643b"),
                            Address = "大直路504号",
                            AreaNumber = "320583106008",
                            ContactPhone = "0512-55272500",
                            GovernmentLevel = 5,
                            GroupCount = 23,
                            HighLevelAreaNumber = "320583106000",
                            SecretaryName = "梁奇希",
                            UrbanRuralClassification = 112,
                            VillageHeadName = "吕勇男",
                            VillageName = "大直社区"
                        },
                        new
                        {
                            Id = new Guid("e1411b5a-aeaf-489a-aa4f-0eb8ec467816"),
                            Address = "周巷路",
                            AreaNumber = "320583106009",
                            ContactPhone = "0512-57294577",
                            GovernmentLevel = 5,
                            GroupCount = 40,
                            HighLevelAreaNumber = "320583106000",
                            SecretaryName = "姜永昌",
                            UrbanRuralClassification = 111,
                            VillageHeadName = "吴凯凯",
                            VillageName = "周巷社区"
                        },
                        new
                        {
                            Id = new Guid("41e0337e-09a5-4992-92e3-12e145983bdb"),
                            Address = "京东路588号",
                            AreaNumber = "320583106012",
                            ContactPhone = "0512-57883298",
                            GovernmentLevel = 5,
                            HighLevelAreaNumber = "320583106000",
                            SecretaryName = "龙澔",
                            UrbanRuralClassification = 111,
                            VillageHeadName = "汤烨磊",
                            VillageName = "亲和社区"
                        },
                        new
                        {
                            Id = new Guid("d20ba91f-3553-4f8e-a814-6f7e0b160a83"),
                            Address = "京东路731号",
                            AreaNumber = "320583106013",
                            ContactPhone = "0512-57278938",
                            GovernmentLevel = 5,
                            HighLevelAreaNumber = "320583106000",
                            SecretaryName = "李段",
                            UrbanRuralClassification = 111,
                            VillageHeadName = "吕尊",
                            VillageName = "锦和社区"
                        },
                        new
                        {
                            Id = new Guid("d11315b0-b1b7-4154-91fc-6cdac48870ce"),
                            Address = "金华路1号",
                            AreaNumber = "320583106200",
                            ContactPhone = "0512-57293702",
                            GovernmentLevel = 5,
                            GroupCount = 26,
                            HighLevelAreaNumber = "320583106000",
                            SecretaryName = "宋翰学",
                            UrbanRuralClassification = 112,
                            VillageHeadName = "龙昊焱",
                            VillageName = "金华村"
                        },
                        new
                        {
                            Id = new Guid("1f52a3f3-18e4-42c0-bc5c-f3c800cca76a"),
                            Address = "商鞅路1号",
                            AreaNumber = "320583106204",
                            ContactPhone = "0512-50310612",
                            GovernmentLevel = 5,
                            GroupCount = 20,
                            HighLevelAreaNumber = "320583106000",
                            SecretaryName = "汤明亮",
                            UrbanRuralClassification = 112,
                            VillageHeadName = "吴咏德",
                            VillageName = "七桥村"
                        },
                        new
                        {
                            Id = new Guid("97bf19d7-0a84-40b3-b539-85f7e81a1355"),
                            Address = "机场路与兴陵路交叉口往南200米",
                            AreaNumber = "320583106205",
                            ContactPhone = "0512-57441476",
                            GovernmentLevel = 5,
                            GroupCount = 27,
                            HighLevelAreaNumber = "320583106000",
                            SecretaryName = "邹俊雄",
                            UrbanRuralClassification = 220,
                            VillageHeadName = "程飞虎",
                            VillageName = "赵陵村"
                        },
                        new
                        {
                            Id = new Guid("cbd439b0-6bd3-4d4e-a630-aa65d9bd4bf0"),
                            Address = "川浩路22号",
                            AreaNumber = "320583106206",
                            ContactPhone = "0512-57441101",
                            GovernmentLevel = 5,
                            HighLevelAreaNumber = "320583106000",
                            SecretaryName = "丁弘亮",
                            UrbanRuralClassification = 220,
                            VillageHeadName = "龚炎彬",
                            VillageName = "吴加村"
                        },
                        new
                        {
                            Id = new Guid("c2e674ac-68c2-446a-bae8-e5aa0985287f"),
                            Address = "港浦东路8号",
                            AreaNumber = "320583106207",
                            ContactPhone = "0512-5736863220",
                            GovernmentLevel = 5,
                            GroupCount = 33,
                            HighLevelAreaNumber = "320583106000",
                            SecretaryName = "史光临",
                            UrbanRuralClassification = 111,
                            VillageHeadName = "陈浦和",
                            VillageName = "三家村"
                        },
                        new
                        {
                            Id = new Guid("1f3fe98d-49b0-4cb7-8060-0b34c6a52d3f"),
                            Address = "盛巷花园门卫北侧",
                            AreaNumber = "320583106209",
                            ContactPhone = "0512-57441616",
                            GovernmentLevel = 5,
                            GroupCount = 20,
                            HighLevelAreaNumber = "320583106000",
                            SecretaryName = "韩华藏",
                            UrbanRuralClassification = 111,
                            VillageHeadName = "萧泰河",
                            VillageName = "新塘村"
                        },
                        new
                        {
                            Id = new Guid("7afbc522-b769-4144-b64d-23ce7f99d1ff"),
                            Address = "震阳路与双娄路交叉口",
                            AreaNumber = "320583106210",
                            ContactPhone = "0512-57421150",
                            GovernmentLevel = 5,
                            GroupCount = 35,
                            HighLevelAreaNumber = "320583106000",
                            SecretaryName = "贺博艺",
                            UrbanRuralClassification = 122,
                            VillageHeadName = "冯鹏赋",
                            VillageName = "星金村"
                        },
                        new
                        {
                            Id = new Guid("f3e864e1-491f-4943-b5a4-4753ea64d276"),
                            Address = "陈邱家浜58号",
                            AreaNumber = "320583106211",
                            ContactPhone = "0512-50331469",
                            GovernmentLevel = 5,
                            GroupCount = 44,
                            HighLevelAreaNumber = "320583106000",
                            SecretaryName = "孙明杰",
                            UrbanRuralClassification = 220,
                            VillageHeadName = "谭睿诚",
                            VillageName = "新龙村"
                        },
                        new
                        {
                            Id = new Guid("1f988319-1dd4-4ada-a3c2-a12baacd4ef3"),
                            Address = "建林路往北到底向西100米",
                            AreaNumber = "320583106212",
                            ContactPhone = "0512-57120550",
                            GovernmentLevel = 5,
                            HighLevelAreaNumber = "320583106000",
                            SecretaryName = "万安怡",
                            UrbanRuralClassification = 220,
                            VillageHeadName = "萧波峻",
                            VillageName = "白米村"
                        },
                        new
                        {
                            Id = new Guid("814e62da-e80c-4bf6-a6d5-da8aceff66d7"),
                            Address = "南港文体站",
                            AreaNumber = "320583106214",
                            ContactPhone = "0512-57428327",
                            GovernmentLevel = 5,
                            GroupCount = 28,
                            HighLevelAreaNumber = "320583106000",
                            SecretaryName = "蒋英卓",
                            UrbanRuralClassification = 220,
                            VillageHeadName = "冯兴庆",
                            VillageName = "林庄村"
                        },
                        new
                        {
                            Id = new Guid("8e62970e-5d09-44ac-b270-ac770515bed1"),
                            Address = "安头村公交站台往南60米处",
                            AreaNumber = "320583106215",
                            ContactPhone = "0512-57428927",
                            GovernmentLevel = 5,
                            GroupCount = 25,
                            HighLevelAreaNumber = "320583106000",
                            SecretaryName = "郝嘉慕",
                            UrbanRuralClassification = 220,
                            VillageHeadName = "史意蕴",
                            VillageName = "安头村"
                        },
                        new
                        {
                            Id = new Guid("62be4d5b-a548-4d04-a91e-2e295c0a7502"),
                            Address = "江浦南路与C325交叉处",
                            AreaNumber = "320583106219",
                            ContactPhone = "0512-57272133",
                            GovernmentLevel = 5,
                            GroupCount = 23,
                            HighLevelAreaNumber = "320583106000",
                            SecretaryName = "漕文彦",
                            UrbanRuralClassification = 220,
                            VillageHeadName = "许高岑",
                            VillageName = "姜杭村"
                        },
                        new
                        {
                            Id = new Guid("75a74032-c72d-4c22-b24c-25cb645479fe"),
                            Address = "长江南路东侧与锦溪北交界",
                            AreaNumber = "320583106220",
                            ContactPhone = "0512-57256590",
                            GovernmentLevel = 5,
                            GroupCount = 21,
                            HighLevelAreaNumber = "320583106000",
                            SecretaryName = "汤英耀",
                            UrbanRuralClassification = 220,
                            VillageHeadName = "蒋嘉许",
                            VillageName = "尚明甸村"
                        },
                        new
                        {
                            Id = new Guid("36f1a282-ff79-462f-abf2-16f8c47afeaa"),
                            Address = "姚家港北首",
                            AreaNumber = "320583106221",
                            ContactPhone = "0512-57117756",
                            GovernmentLevel = 5,
                            GroupCount = 22,
                            HighLevelAreaNumber = "320583106000",
                            SecretaryName = "杨成仁",
                            UrbanRuralClassification = 220,
                            VillageHeadName = "谢高义",
                            VillageName = "南姚村"
                        },
                        new
                        {
                            Id = new Guid("00670456-6c33-4659-a096-ffbd932e3e0f"),
                            Address = "淞沪西路与江浦南路交叉口",
                            AreaNumber = "320583106226",
                            ContactPhone = "0512-57255236",
                            GovernmentLevel = 5,
                            GroupCount = 49,
                            HighLevelAreaNumber = "320583106000",
                            SecretaryName = "顾绍祺",
                            UrbanRuralClassification = 220,
                            VillageHeadName = "金和怡",
                            VillageName = "大市村"
                        },
                        new
                        {
                            Id = new Guid("8a23f0d1-b823-407b-922c-c6591f0821af"),
                            Address = "淞沪东路12号",
                            AreaNumber = "320583106227",
                            ContactPhone = "0512-57251131",
                            GovernmentLevel = 5,
                            HighLevelAreaNumber = "320583106000",
                            SecretaryName = "朱嘉石",
                            UrbanRuralClassification = 220,
                            VillageHeadName = "顾飞羽",
                            VillageName = "南吉山村"
                        });
                });

            modelBuilder.Entity("AspNetCore.Entity.VillagerGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("MemberNumber");

                    b.Property<string>("PrincipalAddress");

                    b.Property<string>("PrincipalEmail");

                    b.Property<string>("PrincipalName");

                    b.Property<string>("PrincipalPhone");

                    b.Property<string>("VillageGroupCode");

                    b.Property<string>("VillageName");

                    b.HasKey("Id");

                    b.ToTable("VillagerGroups");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f33c45d4-481b-4136-a126-1ed4b9415528"),
                            MemberNumber = 356,
                            PrincipalAddress = "张浦镇望江新村6幢206室",
                            PrincipalEmail = "wuxuefei@kszpwz.gov.cn",
                            PrincipalName = "吴雪峰",
                            PrincipalPhone = "0512-57841234",
                            VillageGroupCode = "001",
                            VillageName = "南港社区"
                        },
                        new
                        {
                            Id = new Guid("36b30ad7-2996-4f99-9f09-95c9dfad6d99"),
                            MemberNumber = 412,
                            PrincipalAddress = "张浦镇富都新村3幢204室",
                            PrincipalEmail = "fangjitong@kszpfd.gov.cn",
                            PrincipalName = "方季同",
                            VillageGroupCode = "002",
                            VillageName = "南港社区"
                        },
                        new
                        {
                            Id = new Guid("c4c8e94c-51f2-4add-b586-d2fde3fd8015"),
                            MemberNumber = 532,
                            PrincipalAddress = "张浦镇茶风新村1幢206室",
                            PrincipalEmail = "caogao@kszpcf.gov.cn",
                            PrincipalName = "蔡高",
                            VillageGroupCode = "003",
                            VillageName = "花园社区"
                        },
                        new
                        {
                            Id = new Guid("cf810ea4-85e7-47e3-a2dc-b9449becf860"),
                            MemberNumber = 253,
                            PrincipalAddress = "张浦镇富仁小区5幢102室",
                            PrincipalEmail = "changgaohan@kszpfr.gov.cn",
                            PrincipalName = "常高翰",
                            VillageGroupCode = "004",
                            VillageName = "大市社区"
                        },
                        new
                        {
                            Id = new Guid("fdeefc62-b9ab-43ee-8b76-4f64a5bd5271"),
                            MemberNumber = 512,
                            PrincipalAddress = "张浦镇风和日丽5幢1102室",
                            PrincipalEmail = "qianyancheng@kszpfhrl.gov.cn",
                            PrincipalName = "钱阳成",
                            VillageGroupCode = "005",
                            VillageName = "南港社区"
                        },
                        new
                        {
                            Id = new Guid("d35cee6b-c614-4126-9d72-6df55d2cc86f"),
                            MemberNumber = 567,
                            PrincipalAddress = "张浦镇枫情佳苑3幢306室",
                            PrincipalEmail = "kongzhiwen@kszpfqjy.gov.cn",
                            PrincipalName = "孔志文",
                            VillageGroupCode = "006",
                            VillageName = "新吴社区"
                        },
                        new
                        {
                            Id = new Guid("943e9a97-9fc1-4456-b40a-cf213d49854a"),
                            MemberNumber = 476,
                            PrincipalAddress = "张浦镇张浦村14号",
                            PrincipalEmail = "huhaorang@kszpzp.gov.cn",
                            PrincipalName = "胡浩壤",
                            VillageGroupCode = "007",
                            VillageName = "张浦社区"
                        },
                        new
                        {
                            Id = new Guid("5debdc32-2676-4f30-bf5f-5f9b87363321"),
                            MemberNumber = 345,
                            PrincipalAddress = "张浦镇张浦村142号",
                            PrincipalEmail = "xuexiuxian@kszpzp.gov.cn",
                            PrincipalName = "薛修贤",
                            VillageGroupCode = "008",
                            VillageName = "张浦社区"
                        },
                        new
                        {
                            Id = new Guid("855c3a7f-c1af-4db2-aa9b-8462c37100a3"),
                            MemberNumber = 452,
                            PrincipalAddress = "张浦镇银鹿新城3幢802室",
                            PrincipalEmail = "heliren@kszpylxc.gov.cn",
                            PrincipalName = "何立人",
                            VillageGroupCode = "009",
                            VillageName = "张浦社区"
                        },
                        new
                        {
                            Id = new Guid("d2c95fe0-4169-4913-a795-32db94f4e5b8"),
                            MemberNumber = 662,
                            PrincipalAddress = "张浦镇牡丹苑7幢502",
                            PrincipalEmail = "zhongjunde@kszpmdy.gov.cn",
                            PrincipalName = "钟俊德",
                            VillageGroupCode = "010",
                            VillageName = "周巷社区"
                        },
                        new
                        {
                            Id = new Guid("4e67a4aa-b94f-4766-bcd8-307c4a9326a0"),
                            MemberNumber = 341,
                            PrincipalAddress = "张浦镇江南春堤14号",
                            PrincipalEmail = "jiatianzong@kszpjnkd.gov.cn",
                            PrincipalName = "贾天纵",
                            VillageGroupCode = "011",
                            VillageName = "新巷社区"
                        },
                        new
                        {
                            Id = new Guid("fedfe912-c4ae-4f9d-9eb4-68f206579afd"),
                            MemberNumber = 543,
                            PrincipalAddress = "张浦镇安居小区24号",
                            PrincipalEmail = "duanxuehai@kszpanxq.gov.cn",
                            PrincipalName = "段学海",
                            VillageGroupCode = "012",
                            VillageName = "大市社区"
                        });
                });

            modelBuilder.Entity("AspNetCore.Entity.UserRole", b =>
                {
                    b.HasOne("AspNetCore.Entity.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AspNetCore.Entity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
